### PR TITLE
[Test] Fix test script

### PR DESCRIPTION
**Pull request by VoVAllen**
## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR

### CODE REVIEW

**Comment by BarclayII** [comment]
What is going on with this PR and #1256 ?

**Comment by VoVAllen** [comment]
There's a weird error when `CHECK` macro failed.

http://ci.dgl.ai/blue/organizations/jenkins/DGL/detail/PR-1256/1/pipeline/133
image

A normal way of raising error should be like the figure below
image

The first figure error is usually an illegal memory access error. The reason why this happen is because the UnitGraph I created should have only 9 nodes, but I used 9 as node id in the [COO construction](https://github.com/dmlc/dgl/blob/e8ae12547ca155b80e68e48b9322f0e1de2b75ae/tests/cpp/test_serialize.cc#L62). However, if no error raised, everything works fine. The weird error only happens when `CHECK` macro failed.

**Comment by BarclayII** [comment]
That indeed could happen.  An illegal memory write could wreak havoc in every possible way.  For instance, if you happen to change the `malloc` header that records the allocated chunk size, then the actual crash would happen in `malloc` or `free`.

**Comment by VoVAllen** [comment]
`UnitGraph::CreatefromCOO` didn't check the validity of the COO matrix that each entry should be smaller than `num_src/num_dst`. Is it checked elsewhere?

https://github.com/dmlc/dgl/blob/23893bb0a87b98c7193ba24c5f6b9e802eeb9dea/src/graph/unit_graph.cc#L984

**Comment by BarclayII** [comment]
I think it is checked in Python.  We probably need to move the check into C later.

**Pull request merged**
