### PR TITLE
fix tutorial

### PR DESCRIPTION
**Pull request by sufeidechabei**
## Description

Add self-edges in tutorials of GCN and GAT.

### CODE REVIEW

**Comment by HQ01** [comment]
LGTM

**Comment by HQ01** [comment]
@sufeidechabei Would you mind also editing tutorial in docs.dgl.ai to reflect the change?

**Comment by VoVAllen** [comment]
@HQ01 Tutorial will be auto builded when pr merged.

**Comment by HQ01** [comment]
I see.

**Pull request merged**
