### PR TITLE
[dev] compile dgl with c++17

### PR DESCRIPTION
**Pull request by Rhett-Ying**
## Description

Try to fix errors like [this](https://github.com/dmlc/dgl/pull/4341#issuecomment-1653209799).
```
CMake Error at gpu_cache_generated_nv_gpu_cache.cu.o.cmake:276 (message):
  Error generating file
  /dgl/build/CMakeFiles/gpu_cache.dir/third_party/HugeCTR/gpu_cache/src/./gpu_cache_generated_nv_gpu_cache.cu.o


make[2]: *** [CMakeFiles/gpu_cache.dir/build.make:77: CMakeFiles/gpu_cache.dir/third_party/HugeCTR/gpu_cache/src/gpu_cache_generated_nv_gpu_cache.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:182: CMakeFiles/gpu_cache.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [ ] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by Rhett-Ying** [comment]
@mfbalin Hi, I tried to build DGL gpu version with c++17 with this PR change(g++ 9.4.0) but failed to import dgl(though build is finished successfully.) with below error. Did you hit it?

```
File ~/workspace/dgl_1/python/dgl/_ffi/base.py:39, in _load_lib()
     37 """Load libary by searching possible path."""
     38 lib_path = libinfo.find_lib_path()
---> 39 lib = ctypes.CDLL(lib_path[0])
     40 dirname = os.path.dirname(lib_path[0])
     41 basename = os.path.basename(lib_path[0])

File ~/anaconda3/envs/dgl-dev-gpu-dgl-1/lib/python3.10/ctypes/__init__.py:374, in CDLL.__init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    371 self._FuncPtr = _FuncPtr
    373 if handle is None:
--> 374     self._handle = _dlopen(self._name, mode)
    375 else:
    376     self._handle = handle

OSError: /home/ubuntu/workspace/dgl_1/build/libdgl.so: undefined symbol: _ZN3dgl17DGLDataTypeTraitsI6__halfE5dtypeE
```

**Comment by Rhett-Ying** [comment]
> @mfbalin Hi, I tried to build DGL gpu version with c++17 with this PR change(g++ 9.4.0) but failed to import dgl(though build is finished successfully.) with below error. Did you hit it?
> 
> ```
> File ~/workspace/dgl_1/python/dgl/_ffi/base.py:39, in _load_lib()
>      37 """Load libary by searching possible path."""
>      38 lib_path = libinfo.find_lib_path()
> ---> 39 lib = ctypes.CDLL(lib_path[0])
>      40 dirname = os.path.dirname(lib_path[0])
>      41 basename = os.path.basename(lib_path[0])
> 
> File ~/anaconda3/envs/dgl-dev-gpu-dgl-1/lib/python3.10/ctypes/__init__.py:374, in CDLL.__init__(self, name, mode, handle, use_errno, use_last_error, winmode)
>     371 self._FuncPtr = _FuncPtr
>     373 if handle is None:
> --> 374     self._handle = _dlopen(self._name, mode)
>     375 else:
>     376     self._handle = handle
> 
> OSError: /home/ubuntu/workspace/dgl_1/build/libdgl.so: undefined symbol: _ZN3dgl17DGLDataTypeTraitsI6__halfE5dtypeE
> ```
The undefined symbols could be found if build with `g++ 11.3.0`. So the behavior varies on g++ versions.

**Comment by Rhett-Ying** [comment]
(dgl-dev-gpu-dgl-1) ubuntu@ip-:~/workspace/dgl_1$ g++ --version
```
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
```

(dgl-dev-gpu-dgl-1) ubuntu@ip-:~/workspace/dgl_1$ nm build/libdgl.so | grep -i dgldatatypetraits
```
                 U _ZN3dgl17DGLDataTypeTraitsI13__nv_bfloat16E5dtypeE
                 U _ZN3dgl17DGLDataTypeTraitsI6__halfE5dtypeE
                 U _ZN3dgl17DGLDataTypeTraitsIaE5dtypeE
00000000018765e0 u _ZN3dgl17DGLDataTypeTraitsIdE5dtypeE
0000000001875e7e u _ZN3dgl17DGLDataTypeTraitsIfE5dtypeE
00000000018765e8 u _ZN3dgl17DGLDataTypeTraitsIiE5dtypeE
00000000018765e4 u _ZN3dgl17DGLDataTypeTraitsIlE5dtypeE
```

**Comment by mfbalin** [comment]
@Rhett-Ying I also failed to build with g++-9 version as well after switching to C++17. There must be a fix we can employ so that it works across different compiler versions.

**Comment by mfbalin** [comment]
@TristonC, do you know why the undefined symbol issue might be arising with this PR and g++-9?

**Comment by Rhett-Ying** [comment]
Below is built with g++ 11.3.0 with c++14 and together with [patch](https://github.com/dmlc/dgl/pull/6072).
```
0000000001977ae6 R _ZN3dgl17DGLDataTypeTraitsI13__nv_bfloat16E5dtypeE
0000000001977aea R _ZN3dgl17DGLDataTypeTraitsI6__halfE5dtypeE
0000000001977b06 R _ZN3dgl17DGLDataTypeTraitsIaE5dtypeE
0000000001977ade R _ZN3dgl17DGLDataTypeTraitsIdE5dtypeE
0000000001977ae2 R _ZN3dgl17DGLDataTypeTraitsIfE5dtypeE
0000000001977b02 R _ZN3dgl17DGLDataTypeTraitsIhE5dtypeE
0000000001977afa R _ZN3dgl17DGLDataTypeTraitsIiE5dtypeE
0000000001977af2 R _ZN3dgl17DGLDataTypeTraitsIjE5dtypeE
0000000001977af6 R _ZN3dgl17DGLDataTypeTraitsIlE5dtypeE
0000000001977aee R _ZN3dgl17DGLDataTypeTraitsImE5dtypeE
0000000001977afe R _ZN3dgl17DGLDataTypeTraitsIsE5dtypeE
```

**Comment by TristonC** [comment]
LGTM

**Comment by TristonC** [comment]
@mfbalin I have not tried g++ 9 yet as we have been using g++ 11. I will see if I can test on g++ 9.

**Comment by TristonC** [comment]
@Rhett-Ying  Was your PyTorch also compiled with g++ 9?

**Comment by TristonC** [comment]
> 

Is this dgl::DGLDataTypeTraits<__half>::dtype not defined in your libdgl.so library?

**Comment by Rhett-Ying** [comment]
@TristonC I built with g++ 9.4, CUDA is ON. Compared to build with g++11.3.0, some symbols are missing even the code is same.

**Comment by Rhett-Ying** [comment]
https://github.com/dmlc/dgl/pull/6138 has successfully upgraded c++ std to `17`. let's close this PR.

**Pull request closed without merging**
