### PR TITLE
[Build] use c++17 to build DGL.

### PR DESCRIPTION
**Pull request by frozenbugs**
Related to: https://github.com/dmlc/dgl/pull/5791

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [ ] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Review by Rhett-Ying — APPROVED** [review]

**Review by Rhett-Ying — COMMENTED** [review]
no need to change `c++14` in `CMakeList.txt`?

**Comment by frozenbugs** [comment]
make[2]: *** [rpc_client] Error 1
CMakeFiles/Makefile2:283: recipe for target 'CMakeFiles/rpc_client.dir/all' failed
make[1]: *** [CMakeFiles/rpc_client.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
libdgl.so: undefined reference to `dgl::DGLDataTypeTraits&lt;signed char&gt;::dtype'
libdgl.so: undefined reference to `dgl::DGLDataTypeTraits&lt;__half&gt;::dtype'
collect2: error: ld returned 1 exit status
CMakeFiles/rpc_server.dir/build.make:95: recipe for target 'rpc_server' failed
make[2]: *** [rpc_server] Error 1
CMakeFiles/Makefile2:319: recipe for target 'CMakeFiles/rpc_server.dir/all' failed
make[1]: *** [CMakeFiles/rpc_server.dir/all] Error 2

**Comment by Rhett-Ying** [comment]
According to [pytorch release note](https://pytorch.org/blog/PyTorch-1.13-release/#introduction-of-cuda-116-and-117-and-deprecation-of-cuda-102-and-113), cuda 10.2 which is DGL CI is building on does not support c++17. So it failed in GPU build.

What's more, I'm afraid c++17 is not fully enabled(Below flag is applied to all required third-party libs as well?) in your PR as below line is not changed.
```
  set(CMAKE_CXX_FLAGS "-O2 -Wall -fPIC -std=c++14 ${CMAKE_CXX_FLAGS}")
```
https://github.com/dmlc/dgl/blob/5ada3fc94444244973b2ab0f9c23974c586e531d/CMakeLists.txt#LL91C7-L91C22

**Comment by frozenbugs** [comment]
Close for now until we deprecate CUDA 10.2

**Pull request closed without merging**
