### PR TITLE
[Dist] master port should be fixed for all trainers

### PR DESCRIPTION
**Pull request by Rhett-Ying**
## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by jermainewang** [comment]
What is the bug with the original code?

**Comment by Rhett-Ying** [comment]
trainers may have different value of `master_port` then those trainers will fail to connect the master and fail to finish the init of process group in `torch.distributed`.

**Comment by jermainewang** [comment]
But I don't see why does the change fix the problem. Variable `hosts` should be immutable inside the loop so why lifting `master_port` and `master_addr` outside of the loop fixes the problem?

**Comment by Rhett-Ying** [comment]
if inited outside the loop, they will be same for all the trainers inside the loop. the trainers are launched inside the loop.

**Comment by jermainewang** [comment]
Let's add some tests for `launch.py` to cover some basic usage.

**Review by jermainewang — APPROVED** [review]

**Pull request merged**
