### PR TITLE
[dev] update minimum torch version to 2.1.0

### PR DESCRIPTION
**Pull request by Rhett-Ying**
## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [ ] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by Rhett-Ying** [comment]
@TristonC 

We're updating the minimum pytorch version from `2.0.0` to `2.1.0` and CI is blocked by cugraph docker image: `rapidsai/cugraph_stable_torch-cuda:11.8-base-ubuntu20.04-py3.10-pytorch2.0.0-rapids23.04`. 

On the web page: https://hub.docker.com/r/rapidsai/cugraph_stable_torch-cuda, I cannot find any newer ones.

So do you have ideas about how to handle this?

**Review by frozenbugs — APPROVED** [review]

**Comment by frozenbugs** [comment]
@dgl-bot

**Comment by Rhett-Ying** [comment]
> @TristonC
> 
> We're updating the minimum pytorch version from `2.0.0` to `2.1.0` and CI is blocked by cugraph docker image: `rapidsai/cugraph_stable_torch-cuda:11.8-base-ubuntu20.04-py3.10-pytorch2.0.0-rapids23.04`.
> 
> On the web page: https://hub.docker.com/r/rapidsai/cugraph_stable_torch-cuda, I cannot find any newer ones.
> 
> So do you have ideas about how to handle this?

@chang-l  Hi, do you have any suggestion on this? Should we bypass the test on cugraph or upgrade docker image?

**Comment by chang-l** [comment]
@Rhett-Ying, can you please try switch to NVIDIA's public NGC DGL container for your CI/CD?(https://catalog.ngc.nvidia.com/orgs/nvidia/containers/dgl) `docker pull nvcr.io/nvidia/dgl:24.04-py3`

It includes latest PyTorch and latest RAPIDS (e.g., cugraph/wholegraph) for graph analysis.

**Comment by TristonC** [comment]
@Rhett-Ying We can pause (bypass) the cugraph test for now. cugraph is in the process of refactoring. We can add the test back once its ready.

**Comment by Rhett-Ying** [comment]
> @Rhett-Ying We can pause (bypass) the cugraph test for now. cugraph is in the process of refactoring. We can add the test back once its ready. Or as @chang-l suggested to use NVIDIA DGL container.

Sure. Let's pause the cugraph test for now.

And is there any ticket link to track the status of cugraph refactoring? we could link it here.

**Pull request merged**
