### PR TITLE
[Bugs] Fix distributed example error and import error

### LINKED ISSUE #3780: [Dist] graphsage crashed when following //examples/pytorch/graphsage/dist/README
## 🐛 Bug

|V|=2449029, eval batch size: 100000                                                                                  
|V|=2449029, eval batch size: 100000                                                                                  
|V|=2449029, eval batch size: 100000                                                                                  
|V|=2449029, eval batch size: 100000                                                                                  
7it [00:09,  1.36s/it]                                                                                                
5it [00:09,  1.91s/it]                                                                                                
Client [10701] waits on 172.31.15.181:59225                                                                           
Machine (0) group (0) client (7) connect to server successfuly!                                                       
Traceback (most recent call last):                                                                                    
  File "/home/ubuntu/workspace/dgl/python/dgl/distributed/dist_context.py", line 88, in init_process                  
    (dataloader_name, collate_fn_dict[dataloader_name](collate_args)))                                                  File "/home/ubuntu/workspace/dgl/examples/pytorch/graphsage/dist/train_dist.py", line 45, in sample_blocks          
    frontier = self.sample_neighbors(self.g, seeds, fanout, replace=True)                                               File "/home/ubuntu/workspace/dgl/python/dgl/distributed/graph_services.py", line 583, in sample_neighbors           
    frontier = _distributed_access(g, nodes, issue_remote_req, local_access)                                          
  File "/home/ubuntu/workspace/dgl/python/dgl/distributed/graph_services.py", line 379, in _distributed_access        
    src, dst, eids = local_access(g.local_partition, partition_book, local_nids)                                      
  File "/home/ubuntu/workspace/dgl/python/dgl/distributed/graph_services.py", line 582, in local_access               
    fanout, edge_dir, prob, replace)                                                                                  
  File "/home/ubuntu/workspace/dgl/python/dgl/distributed/graph_services.py", line 64, in _sample_neighbors           
    local_g, local_ids, fan_out, edge_dir, prob, replace, _dist_training=True)                                        
  File "/home/ubuntu/workspace/dgl/python/dgl/sampling/neighbor.py", line 293, in sample_neighbors                    
    copy_ndata=copy_ndata, copy_edata=copy_edata, exclude_edges=exclude_edges)                                        
  File "/home/ubuntu/workspace/dgl/python/dgl/sampling/neighbor.py", line 360, in _sample_neighbors                   
    edge_dir, prob_arrays, excluded_edges_all_t, replace)                                                             
  File "/home/ubuntu/workspace/dgl/python/dgl/_ffi/_ctypes/function.py", line 190, in __call__              
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))                                                       
  File "/home/ubuntu/workspace/dgl/python/dgl/_ffi/base.py", line 65, in check_call                 
    raise DGLError(py_str(_LIB.DGLGetLastError()))                                                            
dgl._ffi.base.DGLError: [02:21:54] /home/ubuntu/workspace/dgl/include/dgl/./aten/array_ops.h:377: Check failed: !first
: All input arrays are empty.
## To Reproduce

1. cd `//examples/pytorch/graphsage/dist/`
2. cp ../advanced/load_graph.py .
3. DGL_HOME=/home/ubuntu/workspace/dgl DGL_LIBRARY_PATH=$DGL_HOME/build PYTHONPATH=.:$DGL_HOME/python:$PYTHONPATH DGLBACKEND=pytorch DGLTESTDEV=cpu  python3 partition_graph.py --dataset ogb-product --num_parts 2 --balance_train --balance_edges
4. DGL_HOME=/home/ubuntu/workspace/dgl DGL_LIBRARY_PATH=$DGL_HOME/build PYTHONPATH=.:$DGL_HOME/python:$PYTHONPATH DGLBACKEND=pytorch DGLTESTDEV=cpu  python3 ~/workspace/dgl/tools/launch.py --workspace ~/workspace/dgl/examples/pytorch/graphsage/dist --num_trainers 2 --num_samplers 1 --num_servers 2 --part_config data/ogb-product.json --ip_config ~/workspace/ip_config.txt "python3 train_dist.py --graph_name ogb-product --ip_config ~/workspace/ip_config.txt --num_epochs 5 --batch_size 1024"

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

### PR DESCRIPTION
**Pull request by BarclayII**
Should fix #3780.  @Rhett-Ying Please take a look.

### CODE REVIEW

**Comment by BarclayII** [comment]
`sphinx-gallery` seems to have problem with `spawn` in multiprocessing.  Got this error when building the documentation for the multi-GPU tutorials:
```
AttributeError: Can't get attribute 'main' on <module '__main__' (built-in)>
```
So I disabled the `__main__` block that spawns the training processes in tutorials to get around it.
@VoVAllen

**Comment by Rhett-Ying** [comment]
Verified and it works well now.

**Comment by Rhett-Ying** [comment]
//examples/pytroch/rgcn/experimental works well...

**Review by Rhett-Ying — APPROVED** [review]
verified on graphsage and rgcn dist.

**Pull request merged**
