### PR TITLE
[Test] Use pytest and fix gather rows

### PR DESCRIPTION
**Pull request by VoVAllen**
## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR

### CODE REVIEW

**Comment by VoVAllen** [comment]
Need support for `@pytest.mark.skipif` to skip some test with tensorflow. TF doesn't support inplace mutate. And pytest has better error message when assert fails (would print out the assert values)

**Comment by yzh119** [comment]
Hi JJ, could you please explain why do we need pytest, is it for tf integration?
It seems many unittests haven to be re-written, the effort is not trivial...

**Comment by VoVAllen** [comment]
Only changes under `tests/scripts/` is for pytest. Others are for tensorflow. Because tf doesn't support get rows by `tensor[[0,2]]`, but only with `F.gather_row(tensor, (0,2))`

**Comment by jermainewang** [comment]
Shall we close this in favor of #1084?

**Pull request closed without merging**
