### PR TITLE
[DoNotMerge] Regression test btw 0.8.0 and 0.8.x

### PR DESCRIPTION
**Pull request by Rhett-Ying**
## Description

`0.8.0`:
commit 3521fbe9aec102f59e18f8336510f646c4759f29
Author: Quan (Andy) Gan <coin2028@hotmail.com>
Date:   Tue Mar 1 03:04:51 2022 +0800

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by Rhett-Ying** [comment]
@dgl-bot run g4dn.8xlarge all dmlc/0.8.x

**Comment by Rhett-Ying** [comment]
@dgl-bot run r6i.16xlarge all dmlc/0.8.x

**Comment by Rhett-Ying** [comment]
@dgl-bot run g4dn.8xlarge all dmlc/0.8.x

**Comment by Rhett-Ying** [comment]
@dgl-bot run g4dn.8xlarge all dmlc/0.8.x

**Comment by VoVAllen** [comment]
@dgl-bot run g4dn.8xlarge all dmlc/0.8.x

**Comment by VoVAllen** [comment]
@dgl-bot run g4dn.8xlarge all dmlc/0.8.x

**Comment by VoVAllen** [comment]
@dgl-bot run g4dn.8xlarge all dmlc/0.8.x

**Comment by Rhett-Ying** [comment]
@dgl-bot run g4dn.8xlarge all dmlc/0.8.x

**Comment by Rhett-Ying** [comment]
@dgl-bot run r6i.16xlarge all dmlc/0.8.x

**Comment by Rhett-Ying** [comment]
Highlights of `g4dn.8xlarge`  (0.8.x - 0.8.0) / 0.8.0
**>=10%**
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/ruying/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/ruying/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



220 | api.bench_knn_graph.track_time | 1000, 256, 8, 'nn-descent' | s | 0.03712141 | g4dn.8xlarge-gpu | 0.04379684 | 18%
-- | -- | -- | -- | -- | -- | -- | --
192 | api.bench_in_subgraph.track_time | 'reddit', 'csc', 200 | s | 0.00031539 | g4dn.8xlarge-gpu | 0.00035859 | 14%
230 | api.bench_knn_graph.track_time | 10000, 4, 64, 'bruteforce' | s | 0.0567392 | g4dn.8xlarge-gpu | 0.06309742 | 11%
223 | api.bench_knn_graph.track_time | 1000, 256, 64, 'bruteforce-sharemem' | s | 0.03033682 | g4dn.8xlarge-gpu | 0.03349793 | 10%
212 | api.bench_knn_graph.track_time | 1000, 32, 8, 'nn-descent' | s | 0.02769576 | g4dn.8xlarge-gpu | 0.03053628 | 10%
235 | api.bench_knn_graph.track_time | 10000, 32, 8, 'bruteforce-sharemem' | s | 0.03749212 | g4dn.8xlarge-gpu | 0.04110707 | 10%



</body>

</html>

**<=10%**
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/ruying/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/ruying/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



225 | api.bench_knn_graph.track_time | 10000, 4, 8, 'bruteforce-blas' | s | 0.04115983 | g4dn.8xlarge-gpu | 0.03722094 | -10%
-- | -- | -- | -- | -- | -- | -- | --
37 | api.bench_builtin_apply_edges_hetero.track_time | 50, 'coo', 128, 'u->e' | s | 0.01786018 | g4dn.8xlarge-gpu | 0.01614254 | -10%
159 | api.bench_edge_ids.track_time | 'livejournal', 'csc', 0.01, False | s | 0.02109861 | g4dn.8xlarge-gpu | 0.01887401 | -11%
193 | api.bench_in_subgraph.track_time | 'reddit', 'csc', 5000 | s | 0.00109982 | g4dn.8xlarge-gpu | 0.00096725 | -12%
158 | api.bench_edge_ids.track_time | 'livejournal', 'csc', 0.01, True | s | 0.04779489 | g4dn.8xlarge-gpu | 0.04128641 | -14%
214 | api.bench_knn_graph.track_time | 1000, 32, 64, 'bruteforce' | s | 0.03788672 | g4dn.8xlarge-gpu | 0.03247911 | -14%
402 | api.bench_sample_neighbors.track_time | 'reddit', 'csc', 5000, 40 | s | 0.00098847 | g4dn.8xlarge-gpu | 0.00084246 | -15%
281 | api.bench_node_subgraph.track_time | 'livejournal', 'csc', 20000 | s | 0.00132087 | g4dn.8xlarge-gpu | 0.00111634 | -15%
405 | api.bench_sample_neighbors.track_time | 'reddit', 'csc', 20000, 40 | s | 0.00348495 | g4dn.8xlarge-gpu | 0.00267674 | -23%



</body>

</html>

**Comment by Rhett-Ying** [comment]
Highlights of `r6i.16xlarge`, (0.8.x - 0.8.0) / 0.8.0
**>=10%**
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/ruying/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/ruying/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



646 | kernel.bench_gsddmm_u_dot_v.track_flops | 'ogbn-arxiv', 4, 4 | GFLOPS | 5.58 | r6i.16xlarge-cpu | 8.53 | 53%
-- | -- | -- | -- | -- | -- | -- | --
315 | api.bench_nn_graphconv.track_time | 'ogbn-arxiv', 4, 'mean' | s | 0.00232676 | r6i.16xlarge-cpu | 0.00344471 | 48%
647 | kernel.bench_gsddmm_u_dot_v.track_flops | 'ogbn-arxiv', 32, 0 | GFLOPS | 34.79 | r6i.16xlarge-cpu | 50.66 | 46%
265 | api.bench_knn_graph.track_time | 1000, 32, 8, 'kd-tree' | s | 0.00123323 | r6i.16xlarge-cpu | 0.00176071 | 43%
648 | kernel.bench_gsddmm_u_dot_v.track_flops | 'ogbn-arxiv', 32, 1 | GFLOPS | 37.33 | r6i.16xlarge-cpu | 51.41 | 38%
268 | api.bench_knn_graph.track_time | 1000, 32, 64, 'bruteforce' | s | 0.00188766 | r6i.16xlarge-cpu | 0.00253677 | 34%
87 | api.bench_builtin_update_all_csc.track_time | 'ogbn-arxiv', 'csc', 4, 'u_mul_e', 'sum' | s | 0.00100705 | r6i.16xlarge-cpu | 0.0013115 | 30%
447 | api.bench_readout.track_time | 256, 16, 'mean', 'edge' | s | 8.42E-05 | r6i.16xlarge-cpu | 0.00010812 | 28%
693 | kernel.bench_gspmm_u_mul_e_sum.track_flops | 'ogbn-arxiv', 32, 1 | GFLOPS | 16.53 | r6i.16xlarge-cpu | 20.67 | 25%
530 | api.bench_sample_neighbors.track_time | 'reddit', 'csc', 5000, 40 | s | 0.00042917 | r6i.16xlarge-cpu | 0.00052589 | 23%
673 | kernel.bench_gspmm_copy_u.track_flops | 'ogbn-arxiv', 32, 'sum' | GFLOPS | 38.33 | r6i.16xlarge-cpu | 46.26 | 21%
319 | api.bench_nn_graphconv.track_time | 'ogbn-arxiv', 32, 'gcn' | s | 0.00417442 | r6i.16xlarge-cpu | 0.00503588 | 21%
309 | api.bench_nn_graphconv.track_time | 'pubmed', 32, 'mean' | s | 0.00084582 | r6i.16xlarge-cpu | 0.00102024 | 21%
461 | api.bench_readout.track_time | 256, 512, 'min', 'edge' | s | 0.00153787 | r6i.16xlarge-cpu | 0.00184746 | 20%
259 | api.bench_knn_graph.track_time | 1000, 4, 64, 'bruteforce-blas' | s | 0.00293442 | r6i.16xlarge-cpu | 0.00341071 | 16%
485 | api.bench_readout.track_time | 1024, 512, 'min', 'edge' | s | 0.00526756 | r6i.16xlarge-cpu | 0.00609373 | 16%
285 | api.bench_knn_graph.track_time | 10000, 4, 64, 'kd-tree' | s | 0.0079746 | r6i.16xlarge-cpu | 0.00922529 | 16%
477 | api.bench_readout.track_time | 1024, 128, 'min', 'edge' | s | 0.00154926 | r6i.16xlarge-cpu | 0.00176417 | 14%
644 | kernel.bench_gsddmm_u_dot_v.track_flops | 'ogbn-arxiv', 4, 0 | GFLOPS | 13.9 | r6i.16xlarge-cpu | 15.63 | 12%
13 | api.bench_builtin_apply_edges.track_time | 'cora', 'csr', 8, 'u+v' | s | 0.00011731 | r6i.16xlarge-cpu | 0.00013159 | 12%
263 | api.bench_knn_graph.track_time | 1000, 32, 8, 'bruteforce-blas' | s | 0.00252847 | r6i.16xlarge-cpu | 0.00283019 | 12%
560 | api.bench_udf_apply_edges.track_time | 'ogbn-arxiv', 'coo', 32, 'u->e' | s | 0.01274286 | r6i.16xlarge-cpu | 0.01421461 | 12%
453 | api.bench_readout.track_time | 256, 128, 'min', 'edge' | s | 0.00047012 | r6i.16xlarge-cpu | 0.00051991 | 11%
561 | api.bench_udf_apply_edges.track_time | 'ogbn-arxiv', 'coo', 32, 'u+v' | s | 0.03422869 | r6i.16xlarge-cpu | 0.03766655 | 10%
25 | api.bench_builtin_apply_edges.track_time | 'ogbn-arxiv', 'csr', 8, 'u+v' | s | 0.00410061 | r6i.16xlarge-cpu | 0.00450448 | 10%
573 | api.bench_udf_apply_edges.track_time | 'pubmed', 'coo', 512, 'u+v' | s | 0.04037076 | r6i.16xlarge-cpu | 0.04420803 | 10%



</body>

</html>


**<=10%**
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/ruying/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/ruying/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



17 | api.bench_builtin_apply_edges.track_time | 'cora', 'csr', 512, 'u+v' | s | 0.00091012 | r6i.16xlarge-cpu | 0.00082344 | -10%
-- | -- | -- | -- | -- | -- | -- | --
351 | api.bench_random_walk.track_time | 'cora', 10, 20, '_random_walk' | s | 0.00015859 | r6i.16xlarge-cpu | 0.00014307 | -10%
16 | api.bench_builtin_apply_edges.track_time | 'cora', 'csr', 512, 'u->e' | s | 0.00082371 | r6i.16xlarge-cpu | 0.00074192 | -10%
651 | kernel.bench_gsddmm_u_dot_v.track_flops | 'ogbn-arxiv', 256, 1 | GFLOPS | 43.94 | r6i.16xlarge-cpu | 39.55 | -10%
454 | api.bench_readout.track_time | 256, 128, 'min', 'node' | s | 0.0002322 | r6i.16xlarge-cpu | 0.00020825 | -10%
401 | api.bench_random_walk.track_time | 'friendster', 100, 2, '_random_walk' | s | 0.00016435 | r6i.16xlarge-cpu | 0.0001473 | -10%
383 | api.bench_random_walk.track_time | 'livejournal', 100, 20, '_random_walk' | s | 0.00018771 | r6i.16xlarge-cpu | 0.00016746 | -11%
244 | api.bench_in_subgraph.track_time | 'livejournal', 'csc', 5000 | s | 0.00039502 | r6i.16xlarge-cpu | 0.00035155 | -11%
675 | kernel.bench_gspmm_copy_u.track_flops | 'ogbn-arxiv', 256, 'sum' | GFLOPS | 16.47 | r6i.16xlarge-cpu | 14.63 | -11%
403 | api.bench_random_walk.track_time | 'friendster', 100, 5, '_random_walk' | s | 0.00016641 | r6i.16xlarge-cpu | 0.00014694 | -12%
582 | api.bench_udf_multi_update_all.track_time | 128, 50, 'sum' | s | 4.64766698 | r6i.16xlarge-cpu | 4.1028973 | -12%
78 | api.bench_builtin_update_all_coo.track_time | 'ogbn-arxiv', 'coo', 256, 'copy_u', 'sum' | s | 0.10770719 | r6i.16xlarge-cpu | 0.09465993 | -12%
255 | api.bench_knn_graph.track_time | 1000, 4, 8, 'bruteforce-blas' | s | 0.0021477 | r6i.16xlarge-cpu | 0.00188551 | -12%
71 | api.bench_builtin_update_all_coo.track_time | 'ogbn-arxiv', 'coo', 4, 'u_mul_e', 'max' | s | 1.31136999 | r6i.16xlarge-cpu | 1.14911224 | -12%
215 | api.bench_homograph_scipy_construction.track_time | 'small', 'coo' | s | 6.84E-05 | r6i.16xlarge-cpu | 5.99E-05 | -12%
515 | api.bench_sample_neighbors.track_time | 'livejournal', 'csc', 20000, 40 | s | 0.00044487 | r6i.16xlarge-cpu | 0.0003883 | -13%
282 | api.bench_knn_graph.track_time | 10000, 4, 8, 'nn-descent' | s | 0.05011309 | r6i.16xlarge-cpu | 0.04349974 | -13%
90 | api.bench_builtin_update_all_csc.track_time | 'ogbn-arxiv', 'csc', 32, 'copy_u', 'sum' | s | 0.00106688 | r6i.16xlarge-cpu | 0.0009176 | -14%
280 | api.bench_knn_graph.track_time | 10000, 4, 8, 'bruteforce' | s | 0.03292178 | r6i.16xlarge-cpu | 0.02793768 | -15%
649 | kernel.bench_gsddmm_u_dot_v.track_flops | 'ogbn-arxiv', 32, 4 | GFLOPS | 34.53 | r6i.16xlarge-cpu | 29.13 | -16%
632 | kernel.bench_edgesoftmax.track_time | 'ogbn-arxiv', 1 | s | 0.00157553 | r6i.16xlarge-cpu | 0.00132601 | -16%
10 | api.bench_builtin_apply_edges.track_time | 'cora', 'coo', 512, 'u->e' | s | 0.00081696 | r6i.16xlarge-cpu | 0.00068652 | -16%
88 | api.bench_builtin_update_all_csc.track_time | 'ogbn-arxiv', 'csc', 4, 'u_mul_e', 'mean' | s | 0.00182156 | r6i.16xlarge-cpu | 0.00150438 | -17%
538 | api.bench_to_block.track_time | 'reddit', 256, 10 | s | 0.0014435 | r6i.16xlarge-cpu | 0.00118684 | -18%
192 | api.bench_format_conversion.track_time | 'cora', ('coo', 'csc') | s | 0.0001085 | r6i.16xlarge-cpu | 8.84E-05 | -19%
75 | api.bench_builtin_update_all_coo.track_time | 'ogbn-arxiv', 'coo', 32, 'u_mul_e', 'sum' | s | 0.02053231 | r6i.16xlarge-cpu | 0.01486687 | -28%
690 | kernel.bench_gspmm_u_mul_e_sum.track_flops | 'ogbn-arxiv', 4, 1 | GFLOPS | 11.83 | r6i.16xlarge-cpu | 7.86 | -34%
233 | api.bench_in_edges.track_time | 'cora', 'csc', 0.01 | s | 0.00041147 | r6i.16xlarge-cpu | 0.00026687 | -35%
72 | api.bench_builtin_update_all_coo.track_time | 'ogbn-arxiv', 'coo', 32, 'copy_u', 'sum' | s | 0.02262644 | r6i.16xlarge-cpu | 0.01418672 | -37%



</body>

</html>

**Comment by Rhett-Ying** [comment]
@jermainewang , some may require more attention:

`g4dn.8xlarge`
1. some `api.bench_knn_graph.track_time` increases around **10%**.

`r6i.16xlarge`
1. GFLOPS of `kernel.gspmm`, `kernel.gsddmm` may drop or increase heavily.

**Pull request closed without merging**
