### PR TITLE
[Feature] Edge Group Apply API 

### PR DESCRIPTION
**Pull request by VoVAllen**
## Description
Add group apply API
Refer to https://github.com/dmlc/dgl/issues/332
` group_apply_edges(self, group_by, func)`

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented
- [x] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [x] Related issue is referred in this PR

## Changes
- [x] Add edge group apply API
- [x] degree bucketing schedule for group apply
- [x] lowering edge grouping by node to c++
- [x] Add softmax to test backend
- [x] test cases

### CODE REVIEW

**Comment by ylfdq1118** [comment]
@VoVAllen I finished c++ part and rearranged group_apply scheduler code.

**Comment by VoVAllen** [comment]
Thanks! Looks good to me!

**Comment by VoVAllen** [comment]
Looks ready to merge!

**Comment by ylfdq1118** [comment]
@VoVAllen Thanks!

**Pull request merged**
