### PR TITLE
[User Guide] Update for User Guide 5.4 Graph Classification

### PR DESCRIPTION
**Pull request by mufeili**
## Description
To address #2224 along with some minor fix.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [x] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [x] Related issue is referred in this PR

### CODE REVIEW

**Comment by annihi1ation** [comment]
thank a lot<3
or more intimately:
谢谢大佬orz

**Comment by mufeili** [comment]
> thank a lot<3
> or more intimately:
> 谢谢大佬orz

No worries.

**Comment by annihi1ation** [comment]
Another question is： in this section, can you provide the exact dataset name for hetero graph classification?

https://docs.dgl.ai/en/0.5.x/guide/training-graph.html#heterogeneous-graph

thanks a lot again

**Comment by mufeili** [comment]
> Another question is： in this section, can you provide the exact dataset name for hetero graph classification?
> 
> https://docs.dgl.ai/en/0.5.x/guide/training-graph.html#heterogeneous-graph
> 
> thanks a lot again

I don't think DGL currently has a graph classification dataset for heterogeneous graphs so that part is more for a general idea.

**Pull request merged**
