### PR TITLE
[Doc] Add ArangoDB-DGL in DGL-powered projects

### PR DESCRIPTION
**Pull request by aMahanna**
## Description

Hi there, ArangoDB is currently maintaining an adapter to allow users to export their graphs into DGL and vice-versa. Would be cool to have it listed if possible!

### CODE REVIEW

**Comment by aMahanna** [comment]
As a side note, we are also curious if this would be something worth mentioning as part of a blog post? https://www.dgl.ai/pages/index.html

**Review by BarclayII — APPROVED** [review]

**Comment by BarclayII** [comment]
> As a side note, we are also curious if this would be something worth mentioning as part of a blog post?

Yes.  Since we are not experts on ArangoDB, would you like to write an article about how to use ArangoDB with DGL?
cc @jermainewang

**Comment by aMahanna** [comment]
> Yes. Since we are not experts on ArangoDB, would you like to write an article about how to use ArangoDB with DGL?

That would be great - Are there any article guidelines/templates I should follow? Otherwise I can draft something up and share it with you & your team for feedback

**Comment by BarclayII** [comment]
The blog article would be pretty free-form compared to documentations and tutorials.  You could start a Google Doc and share it here.

**Comment by aMahanna** [comment]
> The blog article would be pretty free-form compared to documentations and tutorials. You could start a Google Doc and share it here.

Hey!

Here's the draft: https://docs.google.com/document/d/12eLAC7hO40Xxhv_Jct5AFHlbpbcjylTv6UsAnldn-wM/edit?usp=sharing

**Comment by jermainewang** [comment]
Hi @aMahanna , are you in DGL's slack channel? We could discuss about the blog there.

**Pull request merged**
