### PR TITLE
[Hetero] Heterogeneous graph query interfaces

### PR DESCRIPTION
**Pull request by BarclayII**
## Description
Python interfaces to heterogeneous graphs.

One can read the docstrings for graph queries, but here is an example of creating a heterogeneous graph of the following:
image

```python
>>> follows = DGLBaseBipartite.from_coo(
...     'user', 'user', 'follows', 3, 3, [0, 1], [1, 2])
>>> plays = DGLBaseBipartite.from_coo(
...     'user', 'game', 'plays', 3, 2, [0, 1, 1, 2], [0, 0, 1, 1])
>>> develops = DGLBaseBipartite.from_coo(
...     'developer', 'game', 'develops', 2, 2, [0, 1], [0, 1])
>>> g = DGLHeteroGraph([follows, plays, develops])
```

Then one could query the graph as follows:

```python
>>> g['user'].number_of_nodes()
3
>>> g['plays'].number_of_edges()
4
>>> g['develops'].out_degrees() # out-degrees of source nodes of 'develops' relation
tensor([1, 1])
>>> g['develops'].in_edges(0)   # in-edges of destination node 0 of 'develops' relation
(tensor([0]), tensor([0]))
```

Currently unit tests haven't been completed yet.  Any comments and questions regarding to the user experience (or other issues) are welcome.

EDIT: see `tests/compute/test_heterograph.py` for more usages and their behaviors.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented
- [x] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by VoVAllen** [comment]
Minor suggestion:  
```
follows = DGLBaseBipartite.from_coo( ['user', 'user', 'follows'], [3, 3], [[0, 1], [1, 2]])
```
seems better to me.

**Comment by jermainewang** [comment]
```python
>>> follows = DGLBaseBipartite.from_coo(
...     'user', 'user', 'follows', 3, 3, [0, 1], [1, 2])
>>> plays = DGLBaseBipartite.from_coo(
...     'user', 'game', 'plays', 3, 2, [0, 1, 1, 2], [0, 0, 1, 1])
>>> develops = DGLBaseBipartite.from_coo(
...     'developer', 'game', 'develops', 2, 2, [0, 1], [0, 1])
>>> g = DGLHeteroGraph([follows, plays, develops])
```

Are these APIs for the end users? Some suggestions:
* DGLGraph supports conversion from (1) edge list (2) nx graph (3) scipy matrix. It'd be better to have the same set of supports here. I'm also thinking about adding a module `convert.py` to put all these conversion functions together.
```python
import dgl
follows = dgl.bipartite_from_edge_list('user', 'game', 'plays', [(0, 0), (1, 0), (1, 1), (2, 1)], 3, 2)
follows = dgl.bipartite_from_nx('user', 'game', 'plays', some_nx_graph)
follows = dgl.bipartite_from_scipy('user', 'game', 'plays', spmat)
```
Potential function signature:
```
def bipartite_from_edge_list(src_name, dst_name, edge_name, elist, num_src=None, num_dst=None):
    """
    src_name : str
    dst_name : str
    edge_name : str
    elist : list of pairs
    num_src : optional, int
        If none, infer from the given edge list.
    num_dst : optional, int
        If none, infer from the given edge list.
    """
    pass

def bipartite_from_nx(src_name, dst_name, edge_name, nx_graph):
    """
    src_name : str
    dst_name : str
    edge_name : str
    nx_graph : networkx.DiGraph
        All the nodes with zero in-degree will be the src node group and
        all the nodes with zero out-degree will be the dst node group. If there
        is node with both non-zero in-degree and out-degree, throw error.
    “”“
    pass

def bipartite_from_scipy(src_name, dst_name, edge_name, spmat):
    """
    src_name : str
    dst_name : str
    edge_name : str
    spmat : scipy.sparse_matrix
        A scipy sparse matrix of shape (N, M), the result bipartite graph will have N src
        nodes and M dst nodes.
    “”“
    pass
```
* So your suggestion is to put the type name in the constructor of bipartite graph and remove the metagraph argument in Heterograph? I think that makessense.

```python
>>> g['user'].number_of_nodes()
3
>>> g['plays'].number_of_edges()
4
>>> g['develops'].out_degrees() # out-degrees of source nodes of 'develops' relation
tensor([1, 1])
>>> g['develops'].in_edges(0)   # in-edges of destination node 0 of 'develops' relation
(tensor([0]), tensor([0]))
```

Is `g` a heterograph or bipartite graph? If a heterograph, then `g['user']` does not make sense. It should be `g.number_of_nodes('user')`. `g[xxx]` is only for edge type.

**Comment by jermainewang** [comment]
Also, do we need `DGLBaseBipartite` and `DGLHeteroBipartite`? I feel they are not necessary we don't have any type polymorphism. I also feel `DGLBaseGraph` should be deleted and `NodeFlow` is just an alias of heterograph in the fugure.

**Comment by BarclayII** [comment]
For NetworkX I'm thinking of providing an interface that directly converts from a NetworkX graph to a DGL heterogeneous graph.  I'm leaving that for future work.

**Comment by BarclayII** [comment]
Temporarily (?) closing this PR.  Working on unifying heterogeneous/homogeneous/batched graph now.  That will result in a large PR though.

**Comment by jermainewang** [comment]
@BarclayII Would you mind opening a RFC on that? It would be quite a huge change and I hope we could settle down some details.

**Comment by BarclayII** [comment]
> @BarclayII Would you mind opening a RFC on that? It would be quite a huge change and I hope we could settle down some details.

Of course.

**Comment by futurely** [comment]
One of the gnn frameworks that support heterogeneous graph is Euler.

Its query interface is `sample_fanout(nodes, edge_types, counts, default_node)`. 

https://github.com/alibaba/euler/blob/653bb010a4c70ab608d989c39c0727fb770cc951/tf_euler/python/euler_ops/neighbor_ops.py#L64

The edge types to sample in each layer are called metapath in the example usage.

https://github.com/alibaba/euler/blob/653bb010a4c70ab608d989c39c0727fb770cc951/tf_euler/python/encoders.py#L387

https://github.com/alibaba/euler/blob/653bb010a4c70ab608d989c39c0727fb770cc951/tf_euler/python/models/lasgnn.py#L130

https://github.com/alibaba/euler/blob/653bb010a4c70ab608d989c39c0727fb770cc951/tf_euler/python/models/lasgnn.py#L101

Users need to convert their data with potentially multiple node types and edge types to binary format graph data. This is also related to Data format https://github.com/dmlc/dgl/pull/728.

https://github.com/alibaba/euler/blob/69651bfb7ffd44de1b83b56e199f348665158f50/examples/ppi_data.py#L122

https://github.com/alibaba/euler/blob/master/euler/tools/json2dat.py

The underlying data strusture is quite simple. Nodes and edges of different types are stored in a vector of FastWeightedCollection respectively.

https://github.com/alibaba/euler/blob/69651bfb7ffd44de1b83b56e199f348665158f50/euler/core/fast_graph.h

https://github.com/alibaba/euler/blob/69651bfb7ffd44de1b83b56e199f348665158f50/euler/core/compact_graph.cc#L127

**Pull request closed without merging**
