### PR TITLE
[GraphBolt] Fix GPUCachedFeature docstring typo

### PR DESCRIPTION
**Pull request by pyynb**
## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [ ] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Review by Rhett-Ying — APPROVED** [review]

**Comment by Rhett-Ying** [comment]
@mfbalin FYI

**Comment by mfbalin** [comment]
Does it always require us to say `Examples` for the codeblock to render?

Thank you very much for fixing this.

**Comment by pyynb** [comment]
> Does it always require us to say `Examples` for the codeblock to render?
> 
> Thank you very much for fixing this.
Not using "examples" will cause the doc to display incorrectly.
image
image

**Comment by mfbalin** [comment]
> > Does it always require us to say `Examples` for the codeblock to render?
> > Thank you very much for fixing this.
> > Not using "examples" will cause the doc to display incorrectly.
> 
> image image

Why is the `r` prefix needed before the multiline string?

**Comment by pyynb** [comment]
> Why is the `r` prefix needed before the multiline string?

Just in case there are escape characters in the string

**Pull request merged**
