### PR TITLE
[Sparse] Solved the problem that DGLGraph.formats with list input doesn't work 

### PR DESCRIPTION
**Pull request by keli-wen**
## Description

I have resolved the previous [issue#5545 -- DGLGraph.formats with list input doesn't work](https://github.com/dmlc/dgl/issues/5545). I identified that the issue was in the `UnitGraph::GetGraphInFormat` function within `src/graph/unit_graph.cc`. Now, the `DGLGraph.formats` function can correctly create the corresponding sparse format.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [x] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [x] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by mufeili** [comment]
@dgl-bot

**Comment by mufeili** [comment]
@dgl-bot

**Comment by frozenbugs** [comment]
@dgl-bot

**Comment by mufeili** [comment]
Could you rename the unit test [here](https://github.com/dmlc/dgl/blob/master/tests/python/common/test_heterograph.py#L2527) to `test_formats` and expand it to cover the cases previously DGL failed to handle?

**Comment by mufeili** [comment]
@Rhett-Ying Do you think if we need to trigger a regression test for this change?

**Comment by frozenbugs** [comment]
> @Rhett-Ying Do you think if we need to trigger a regression test for this change?

Why we have concern about regression after we update unit test? Does this PR affect performance?

**Comment by frozenbugs** [comment]
@dgl-bot

**Comment by frozenbugs** [comment]
The error likely related to this line.

https://github.com/dmlc/dgl/blob/53714ca83112f0747061b53b4f1d3e0b5fd80611/tests/distributed/test_distributed_sampling.py#L33

Since the fix, the formats time will increase, which caused the timeout.

**Comment by keli-wen** [comment]
> 



> The error likely related to this line.
> 
> https://github.com/dmlc/dgl/blob/53714ca83112f0747061b53b4f1d3e0b5fd80611/tests/distributed/test_distributed_sampling.py#L33
> 
> Since the fix, the formats time will increase, which caused the timeout.

Actually, when I checked the log, I found that the error **might** come from:

`dgl._ffi.base.DGLError: [15:59:30] /root/jenkins/workspace/dgl_PR-5708/src/array/cpu/./rowwise_pick.h:340: Check failed: (j + 1 == len) || (et[et_idx[j]] <= et[et_idx[j + 1]]): Edge type is not sorted. Please sort in advance or specify 'rowwise_etype_sorted' as false.`

Because I noticed that after this error occurred, it started to time out.

Before the repair of the `formats` function, there was actually only one Edge type, so could it be possible that this CHECK has not been functioning before the repair of the `formats` function?

**Pull request closed without merging**
