### PR TITLE
[Bug] fix inference for labor example

### PR DESCRIPTION
**Pull request by mfbalin**
The last PR adding inferencing code wasn't working for the `use_uva=True` argument and some other combinations of args, so here is a quick patch to fix it.

### CODE REVIEW

**Comment by mfbalin** [comment]
@frozenbugs This is hopefully the last fix I am making to this example. There still seems to be a bug when we use CPU sampling with inference, but I couldn't figure out why it happens.

**Comment by frozenbugs** [comment]
If you can paste the log here, maybe we can help.

**Comment by mfbalin** [comment]
> If you can paste the log here, maybe we can help.

```
Traceback (most recent call last):
  File "/content/dgl-1/examples/pytorch/labor/train_lightning.py", line 511, in <module>
    pred = model.module.inference(
  File "/content/dgl-1/examples/pytorch/labor/model.py", line 88, in inference
    y[output_nodes[0] : output_nodes[-1] + 1] = h.to(y.device)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:44 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7b5ce21af4d7 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7b5ce217936b in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7b5d0c4adb58 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x1c36b (0x7b5d0c47e36b in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_cuda.so)
frame #4: <unknown function> + 0x2b930 (0x7b5d0c48d930 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_cuda.so)
frame #5: <unknown function> + 0x4d5a16 (0x7b5cdb778a16 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x3ee77 (0x7b5ce2194e77 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #7: c10::TensorImpl::~TensorImpl() + 0x1be (0x7b5ce218d69e in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #8: c10::TensorImpl::~TensorImpl() + 0x9 (0x7b5ce218d7b9 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #9: <unknown function> + 0x75afc8 (0x7b5cdb9fdfc8 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_python.so)
frame #10: THPVariable_subclass_dealloc(_object*) + 0x305 (0x7b5cdb9fe355 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #20: <unknown function> + 0x29d90 (0x7b5d0d023d90 in /lib/x86_64-linux-gnu/libc.so.6)
frame #21: __libc_start_main + 0x80 (0x7b5d0d023e40 in /lib/x86_64-linux-gnu/libc.so.6)
```

**Comment by Rhett-Ying** [comment]
@mfbalin The issue you pasted above happens with current example no matter whether this PR is merged?

**Comment by mfbalin** [comment]
@Rhett-Ying Yes, this PR currently fixes UVA inference. However, I couldn't fix the CPU sampling and GPU inferencing combination.

**Comment by Rhett-Ying** [comment]
got it. Let me try to look into this

**Review by frozenbugs — APPROVED** [review]

**Comment by frozenbugs** [comment]
Feel free to merge this PR if the other error is unrelated.

**Comment by Rhett-Ying** [comment]
Not figured out the root cause yet. Below are several findings that might help.

I tried with smaller dataset `--num-epochs 1 --data-cpu --dataset cora --batch-size 100` and it works well.

If choose `neighbor` sampler, it crashed in train(forward) stage.

According to the callstacks shown below(run with `python3 examples/pytorch/labor/train_lightning.py --dataset ogbn-arxiv --num-epochs 1 --data-cpu`), it crashed when trying to releasing cuda memory blocks. More specifically, I guess system(pytorch/cuda) is trying to releasing some tensors which are still in use.

```
Evaluating model in ./tb_logs/ogbn-arxiv_labor_0_False_1/version_43
  5%|██████▊                                                                                                                                       | 2/42 [00:00<00:03, 12.69it/s]
Traceback (most recent call last):
  File "/home/ubuntu/workspace/dgl_2/examples/pytorch/labor/train_lightning.py", line 520, in <module>
    pred = model.module.inference(
  File "/home/ubuntu/workspace/dgl_2/examples/pytorch/labor/model.py", line 81, in inference
    h = layer(blocks[0], x)
  File "/home/ubuntu/anaconda3/envs/dgl-dev-gpu-dgl-2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/workspace/dgl_2/python/dgl/nn/pytorch/conv/sageconv.py", line 237, in forward
    graph.update_all(msg_fn, fn.mean("m", "neigh"))
  File "/home/ubuntu/workspace/dgl_2/python/dgl/heterograph.py", line 5110, in update_all
    ndata = core.message_passing(
  File "/home/ubuntu/workspace/dgl_2/python/dgl/core.py", line 398, in message_passing
    ndata = invoke_gspmm(g, mfunc, rfunc)
  File "/home/ubuntu/workspace/dgl_2/python/dgl/core.py", line 368, in invoke_gspmm
    z = op(graph, x)
  File "/home/ubuntu/workspace/dgl_2/python/dgl/ops/spmm.py", line 215, in func
    return gspmm(g, "copy_lhs", reduce_op, x, None)
  File "/home/ubuntu/workspace/dgl_2/python/dgl/ops/spmm.py", line 111, in gspmm
    deg = g.in_degrees()
  File "/home/ubuntu/workspace/dgl_2/python/dgl/heterograph.py", line 3669, in in_degrees
    v = self.dstnodes(dsttype)
  File "/home/ubuntu/workspace/dgl_2/python/dgl/view.py", line 49, in __call__
    ret = F.arange(
  File "/home/ubuntu/workspace/dgl_2/python/dgl/backend/pytorch/tensor.py", line 407, in arange
    return th.arange(start, stop, dtype=dtype, device=ctx)
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:44 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f33ce7904d7 in /home/ubuntu/anaconda3/envs/dgl-dev-gpu-dgl-2/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f33ce75a36b in /home/ubuntu/anaconda3/envs/dgl-dev-gpu-dgl-2/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7f33ce82cb58 in /home/ubuntu/anaconda3/envs/dgl-dev-gpu-dgl-2/lib/python3.10/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x1c36b (0x7f33ce7fd36b in /home/ubuntu/anaconda3/envs/dgl-dev-gpu-dgl-2/lib/python3.10/site-packages/torch/lib/libc10_cuda.so)
frame #4: <unknown function> + 0x2b930 (0x7f33ce80c930 in /home/ubuntu/anaconda3/envs/dgl-dev-gpu-dgl-2/lib/python3.10/site-packages/torch/lib/libc10_cuda.so)
frame #5: <unknown function> + 0x4d5a16 (0x7f34256e4a16 in /home/ubuntu/anaconda3/envs/dgl-dev-gpu-dgl-2/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x3ee77 (0x7f33ce775e77 in /home/ubuntu/anaconda3/envs/dgl-dev-gpu-dgl-2/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #7: c10::TensorImpl::~TensorImpl() + 0x1be (0x7f33ce76e69e in /home/ubuntu/anaconda3/envs/dgl-dev-gpu-dgl-2/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #8: c10::TensorImpl::~TensorImpl() + 0x9 (0x7f33ce76e7b9 in /home/ubuntu/anaconda3/envs/dgl-dev-gpu-dgl-2/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #9: <unknown function> + 0x75afc8 (0x7f3425969fc8 in /home/ubuntu/anaconda3/envs/dgl-dev-gpu-dgl-2/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #10: THPVariable_subclass_dealloc(_object*) + 0x305 (0x7f342596a355 in /home/ubuntu/anaconda3/envs/dgl-dev-gpu-dgl-2/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #20: __libc_start_main + 0xf3 (0x7f3445ac7083 in /lib/x86_64-linux-gnu/libc.so.6)

Aborted (core dumped)
```

**Comment by Rhett-Ying** [comment]
Add several envs to control CUDA memory management helps. Below works:
`CUDA_LAUNCH_BLOCKING=1  PYTORCH_CUDA_ALLOC_CONF=backend:cudaMallocAsync python3 examples/pytorch/labor/train_lightning.py --dataset ogbn-arxiv --num-epochs 1 --data-cpu`

**Comment by mfbalin** [comment]
@Rhett-Ying this is such a strange behavior. What do you think causes it? I thought maybe I made a bug in my inference code but it more or less looks the same as the official example.

**Comment by Rhett-Ying** [comment]
@mfbalin I haven't figured out the root cause yet. But I guess memory allocator went wrong when trying to release no-longer-needed memory blocks/objects.

Which official example you're meaning?

**Comment by mfbalin** [comment]
@Rhett-Ying https://github.com/dmlc/dgl/blob/master/examples/sampling/node_classification.py#L77

I had meant the example above. So, if you think my changes are good, maybe we can merge this and open an issue?

**Comment by Rhett-Ying** [comment]
@mfbalin Yes, I think we could merge this PR and open a ticket to track the remaining issue.

**Review by Rhett-Ying — APPROVED** [review]

**Comment by mfbalin** [comment]
@Rhett-Ying thanks for the help!

**Pull request merged**
