### PR TITLE
[Bug?] This PR can make model to run on FB15k-237 successfully.

### PR DESCRIPTION
**Pull request by guotong1988**

### CODE REVIEW

**Comment by BarclayII** [comment]
Thanks for the fix!  I cannot merge it somehow.  Did you delete your branch containing this commit?

**Comment by guotong1988** [comment]
Yes. I delete it.

**Comment by guotong1988** [comment]
Do I need to do the PR again without delete it?

**Comment by VoVAllen** [comment]
Seems yes, otherwise we are not able to merge this.

**Comment by guotong1988** [comment]
I will do it tomorrow and close this PR at the same time.

**Comment by guotong1988** [comment]
https://github.com/dmlc/dgl/pull/1032

**Pull request closed without merging**
