### PR TITLE
[dev] fix build error on windows+cu118

### PR DESCRIPTION
**Pull request by Rhett-Ying**
## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [ ] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by Rhett-Ying** [comment]
Failed to build GPU version on CI. So the `thrust` is too up-to-date? or cuda driver should be updated?

**Comment by Rhett-Ying** [comment]
Passed in CI but failed in windows yet

image

**Comment by mfbalin** [comment]
@Rhett-Ying The latest versions of thrust, cub, etc. are now in the https://github.com/NVIDIA/cccl repository.

Why is there a difference in behavior between the CI and when it comes to compiling for a new release?

**Comment by mfbalin** [comment]
DeviceCopy was added recently to CUB. To make use of it, we updated the submodule thrust version. However, I don't know why it would break the existing release workflow of windows.

**Comment by mfbalin** [comment]
@Rhett-Ying Is it possible to modify the CI to include the windows+cu118 case as well? Then, this kind of issue won't arise as new functionalities are added to DGL.

**Comment by mfbalin** [comment]
I was able to reproduce the problem with windows visual studio 17 2022 + cuda 12.2 build. I am getting the following error:
```
10>C:\Users\Muhammed Fatih Balin\dgl-1\third_party\cccl\libcudacxx\include\cuda\std\detail\libcxx\include\__functional/invoke.h(413):
        error : "cuda" is ambiguous [C:\Users\Muhammed Fatih Balin\dgl-1\build\dgl.vcxproj]
             static decltype(cuda::std::__4::__invoke(cuda::std::__4::declval<_XFp>(), cuda::std::__4::declval<_XArgs>()...)) __try_call(
         int);
                             ^
                   detected during:
                     instantiation of class "cuda::std::__4::__invokable_r<_Ret, _Fp, _Args...> [with _Ret=void, _Fp=dgl::aten::impl::<un
         named>::IndptrFunc<int32_t>, _Args=<signed int>]" at line 475
                     instantiation of class "cuda::std::__4::__invoke_of<_Fp, _Args...> [with _Fp=dgl::aten::impl::<unnamed>::IndptrFunc<
         int32_t>, _Args=<signed int>]" at line 542
                     instantiation of class "cuda::std::__4::invoke_result<_Fn, _Args...> [with _Fn=dgl::aten::impl::<unnamed>::IndptrFun
         c<int32_t>, _Args=<signed int>]" at line 547
                     instantiation of type "cuda::std::__4::invoke_result_t<dgl::aten::impl::<unnamed>::IndptrFunc<int32_t>, signed int>"
          at line 699 of C:/Users/Muhammed Fatih Balin/dgl-1/third_party/cccl/thrust\thrust/detail/type_traits.h
                     instantiation of type "dgl::thrust::detail::invoke_result_t<dgl::aten::impl::<unnamed>::IndptrFunc<int32_t>, signed
         int>" at line 41 of C:/Users/Muhammed Fatih Balin/dgl-1/third_party/cccl/thrust\thrust/detail/type_traits/result_of_adaptable_fu
         nction.h
                     [ 2 instantiation contexts not shown ]
                     instantiation of class "dgl::thrust::detail::eval_if<true, Then, Else> [with Then=dgl::thrust::detail::result_of_ada
         ptable_function<dgl::aten::impl::<unnamed>::IndptrFunc<int32_t> (signed int), void>, Else=dgl::thrust::detail::identity_<dgl::th
         rust::use_default>]" at line 49 of C:/Users/Muhammed Fatih Balin/dgl-1/third_party/cccl/thrust\thrust/iterator/detail/iterator_a
         daptor_base.h
                     instantiation of class "dgl::thrust::detail::ia_dflt_help<T, DefaultNullaryFn> [with T=dgl::thrust::use_default, Def
         aultNullaryFn=dgl::thrust::detail::result_of_adaptable_function<dgl::aten::impl::<unnamed>::IndptrFunc<int32_t> (signed int), vo
         id>]" at line 44 of C:/Users/Muhammed Fatih Balin/dgl-1/third_party/cccl/thrust\thrust/iterator/detail/transform_iterator.inl
                     instantiation of class "dgl::thrust::detail::transform_iterator_base<UnaryFunc, Iterator, Reference, Value> [with Un
         aryFunc=dgl::aten::impl::<unnamed>::IndptrFunc<int32_t>, Iterator=dgl::thrust::counting_iterator<int32_t, dgl::thrust::use_defau
         lt, dgl::thrust::use_default, dgl::thrust::use_default>, Reference=dgl::thrust::use_default, Value=dgl::thrust::use_default]" at
          line 190 of C:/Users/Muhammed Fatih Balin/dgl-1/third_party/cccl/thrust\thrust/iterator/transform_iterator.h
                     instantiation of class "dgl::thrust::transform_iterator<AdaptableUnaryFunction, Iterator, Reference, Value> [with Ad
         aptableUnaryFunction=dgl::aten::impl::<unnamed>::IndptrFunc<int32_t>, Iterator=dgl::thrust::counting_iterator<int32_t, dgl::thru
         st::use_default, dgl::thrust::use_default, dgl::thrust::use_default>, Reference=dgl::thrust::use_default, Value=dgl::thrust::use
         _default]" at line 564 of C:\Users\Muhammed Fatih Balin\dgl-1\src\array\cuda\labor_sampling.cu
                     instantiation of "std::pair<dgl::aten::COOMatrix, dgl::IdArray> dgl::aten::impl::CSRLaborSampling<XPU,IdType,FloatTy
         pe>(dgl::aten::CSRMatrix, dgl::IdArray, int64_t, dgl::FloatArray, int, dgl::IdArray, float, dgl::IdArray) [with XPU=kDGLCUDA, Id
         Type=int32_t, FloatType=float]" at line 819 of C:\Users\Muhammed Fatih Balin\dgl-1\src\array\cuda\labor_sampling.cu
         ```

**Comment by mfbalin** [comment]
@yaox12 any clue what might be going on?

**Comment by mfbalin** [comment]
I guess they don't have a CI for Windows builds yet. https://github.com/NVIDIA/cccl/issues/248.
So, we can possibly revert #5648 for now and wait for the cccl repository to get a Windows CI.

**Comment by Rhett-Ying** [comment]
> @Rhett-Ying Is it possible to modify the CI to include the windows+cu118 case as well? Then, this kind of issue won't arise as new functionalities are added to DGL.

For now, CI runs on windows+cpu only. We do need to include windows+gpu as well in the near future.

**Comment by Rhett-Ying** [comment]
As upgrade to c++17 does not resolve this build issue, let's wait to see if CCCL resolves the build issue. And c++ has already updated to `17` on master branch. Let's close this one.

**Pull request closed without merging**
