### PR TITLE
[Doc] The drawing will not disappear.

### PR DESCRIPTION
**Pull request by guotong1988**
## Description
The drawing will not disappear.

## Changes
The drawing will not disappear.

### CODE REVIEW

**Comment by guotong1988** [comment]
How to fix?

**Comment by VoVAllen** [comment]
I think it's properly displayed at my side. 
image
Could you check whether it's the network issue on your side?

**Comment by guotong1988** [comment]
On Mac,  Pycharm

**Comment by VoVAllen** [comment]
I think the problem is there are multiple figures drawed in this tutorial. Therefore if you run the file, the figure drawed before would be replaced by the figure drawed later. You could solve this with jupyter notebook, or run the code block by block.

image
I think you can click the back button to show the figure drawed before.

**Comment by guotong1988** [comment]
THX

**Pull request closed without merging**
