### PR TITLE
[Doc] Some functions used in the tutorial are deprecated

### PR DESCRIPTION
**Pull request by cruyffturn**
I'm receiving register_message_func and register_reduce_func are deprecated error. I have updated the code such that message and reduce functions are passed to g.send and g.recv

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [x] Code is well-documented
- [ ] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [x] Related issue is referred in this PR

### CODE REVIEW

**Review by yzh119 — APPROVED** [review]
LGTM

**Comment by yzh119** [comment]
But I just noticed you were editing a file `.py.bak` which should not appear in our documentation, where did you find this?

**Comment by yzh119** [comment]
Also, please remove the related text:
```
# Register the message function and reduce function, which will be called
# later by DGL.
```

**Review by cruyffturn — COMMENTED** [review]
I have removed the "# Register the message function ..." message from the comments.

**Comment by cruyffturn** [comment]
@yzh119 
> But I just noticed you were editing a file `.py.bak` which should not appear in our documentation, where did you find this?

I was following the page rank [tutorial](https://docs.dgl.ai/en/latest/tutorials/basics/3_pagerank.html?highlight=pagerank) and got an error. I have searched the "dgl github" with keywords page rank and find the code.

**Pull request merged**
