### PR TITLE
Doc: adapt send_and_recv example

### PR DESCRIPTION
**Pull request by ab-10**
## Description
This PR adapts a `send_and_recv` [example](https://docs.dgl.ai/en/0.4.x/generated/dgl.DGLGraph.send_and_recv.html) from version `0.4` to the latest version.

### CODE REVIEW

**Comment by jermainewang** [comment]
Hi @ab-10 , thanks for the contribution. Would you mind putting your example after the `**heterogeneous graph**` example and change the example title to `**send_and_recv using UDFs**`? We'd like readers to first know about the recommended `copy_u` + `sum` syntax.

**Comment by ab-10** [comment]
Done, I used the expanded abreviation (user-defined functions) to make the example more accessible to newcomers.

**Comment by ab-10** [comment]
@jermainewang could you please take another look at the PR?

**Review by BarclayII — APPROVED** [review]

**Comment by BarclayII** [comment]
Thanks!

**Pull request merged**
