### PR TITLE
[Model]Implementation of diffpool and a dataset loader for TU dataset.

### PR DESCRIPTION
**Pull request by HQ01**
## Description

This PR implement the batched version of diffpool model, together with a re-factored simple graphsage(without sampling) with LSTM/Maxpool/Mean aggregator, and a simple dataset loader for graph dataset available in https://ls11-www.cs.tu-dortmund.de/staff/morris/graphkerneldatasets.
## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [x] Code is well-documented
- [x] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [x] Related issue is referred in this PR

## Changes

Essentially, this PR uses DGL's batchedGraph API to implement diffpool. The graph convolution layer is handled by DGL, but computation of the pooled adjacency matrix is still done by Pytorch sparse mm. Batched Normalization is not implemented, as we batch graphs into a large graph. This implementation match the paper's accuracy on ENZYMES.

### CODE REVIEW

**Comment by HQ01** [comment]
This current implementation is not very efficient. It uses pytorch sparse mm and seg_max, seg_sum are also heavily used (but not optimized). Current API does not support creating graph in the forward pass very well, particularly when the input graph is a BatchedGraph.

**Comment by jermainewang** [comment]
Please add a readme about (1) dependencies (2) how to run (3) what's the result (accuracy? speed?). You could refer to other example folder.

**Comment by HQ01** [comment]
Sure! Will work on it.

**Comment by zheng-da** [comment]
any progress on this PR?

**Comment by HQ01** [comment]
Closed. See PR #665

**Pull request closed without merging**
