### PR TITLE
[DoNotMerge] regression test based on 1.0.x

### PR DESCRIPTION
**Pull request by Rhett-Ying**
## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [ ] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by Rhett-Ying** [comment]
@dgl-bot run g4dn.12xlarge all dmlc/0.9.x

**Comment by Rhett-Ying** [comment]
@dgl-bot run r6i.12xlarge all dmlc/0.9.x

**Comment by Rhett-Ying** [comment]
Pytorch: `1.13.1+cu116`
CUDA: `11.6`
Instance: `g4dn.12xlarge, 4 GPUs`.

I have checked all the highlights shown below( cases that differ beyond `10%`), all look good to me.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/ruying/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/ruying/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



  | test_name | params | unit | (1.0.x - 0.9.x)/0.9.x * 100% | 1.0.x | machine | 0.9.x
-- | -- | -- | -- | -- | -- | -- | --




</body>

</html>

**> 10%**

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/ruying/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/ruying/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



383 | api.bench_sample_neighbors.track_time | 'ogbn-arxiv', 'csc', 20000, 40 | s | 45% | 0.000533363 | g4dn.12xlarge-gpu | 0.00036876
-- | -- | -- | -- | -- | -- | -- | --
285 | api.bench_node_subgraph.track_time | 'reddit', 'csc', 200 | s | 31% | 0.000598699 | g4dn.12xlarge-gpu | 0.00045747
382 | api.bench_sample_neighbors.track_time | 'ogbn-arxiv', 'csc', 20000, 20 | s | 30% | 0.000499098 | g4dn.12xlarge-gpu | 0.00038248
296 | api.bench_readout.track_time | 4, 128, 'sum', 'edge' | s | 23% | 0.000133688 | g4dn.12xlarge-gpu | 0.00010855
159 | api.bench_edge_ids.track_time | 'livejournal', 'csc', 0.01, False | s | 22% | 0.013120715 | g4dn.12xlarge-gpu | 0.01071983
12 | api.bench_builtin_apply_edges.track_time | 'cora', 'csr', 8, 'u->e' | s | 22% | 0.000161997 | g4dn.12xlarge-gpu | 0.00013292
381 | api.bench_sample_neighbors.track_time | 'ogbn-arxiv', 'csc', 20000, 5 | s | 21% | 0.000427786 | g4dn.12xlarge-gpu | 0.00035413
182 | api.bench_in_degrees.track_time | 'cora', 'csc', 0.1 | s | 19% | 6.02E-05 | g4dn.12xlarge-gpu | 5.05E-05
13 | api.bench_builtin_apply_edges.track_time | 'cora', 'csr', 8, 'u+v' | s | 17% | 0.000172874 | g4dn.12xlarge-gpu | 0.00014803
345 | api.bench_readout.track_time | 1024, 128, 'sum', 'node' | s | 16% | 0.000115025 | g4dn.12xlarge-gpu | 9.92E-05
6 | api.bench_builtin_apply_edges.track_time | 'cora', 'coo', 8, 'u->e' | s | 15% | 0.000168416 | g4dn.12xlarge-gpu | 0.00014602
188 | api.bench_in_edges.track_time | 'livejournal', 'csc', 0.1 | s | 15% | 0.005568311 | g4dn.12xlarge-gpu | 0.00485663
410 | api.bench_udf_apply_edges.track_time | 'pubmed', 'coo', 8, 'u->e' | s | 14% | 0.000279712 | g4dn.12xlarge-gpu | 0.00024439
220 | api.bench_knn_graph.track_time | 1000, 256, 8, 'nn-descent' | s | 14% | 0.045338303 | g4dn.12xlarge-gpu | 0.0396389
222 | api.bench_knn_graph.track_time | 1000, 256, 64, 'bruteforce' | s | 13% | 0.066571161 | g4dn.12xlarge-gpu | 0.05899872
380 | api.bench_sample_neighbors.track_time | 'ogbn-arxiv', 'csc', 5000, 40 | s | 13% | 0.000335136 | g4dn.12xlarge-gpu | 0.0002977
304 | api.bench_readout.track_time | 4, 512, 'sum', 'edge' | s | 12% | 0.000120838 | g4dn.12xlarge-gpu | 0.00010744
326 | api.bench_readout.track_time | 256, 128, 'mean', 'edge' | s | 12% | 0.000190776 | g4dn.12xlarge-gpu | 0.00017077
305 | api.bench_readout.track_time | 4, 512, 'sum', 'node' | s | 11% | 0.000112886 | g4dn.12xlarge-gpu | 0.00010135
329 | api.bench_readout.track_time | 256, 512, 'sum', 'node' | s | 11% | 0.000112666 | g4dn.12xlarge-gpu | 0.00010189
279 | api.bench_node_subgraph.track_time | 'livejournal', 'csc', 200 | s | 11% | 0.000456597 | g4dn.12xlarge-gpu | 0.00041301



</body>

</html>


< -10%

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/ruying/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/ruying/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



270 | api.bench_nn_heterographconv.track_time | 32, 5 | s | -87% | 5.01E-05 | g4dn.12xlarge-gpu | 0.00038961
-- | -- | -- | -- | -- | -- | -- | --
273 | api.bench_nn_heterographconv.track_time | 256, 5 | s | -87% | 5.13E-05 | g4dn.12xlarge-gpu | 0.00038203
267 | api.bench_nn_heterographconv.track_time | 4, 5 | s | -86% | 5.28E-05 | g4dn.12xlarge-gpu | 0.0003843
271 | api.bench_nn_heterographconv.track_time | 32, 50 | s | -80% | 0.000820903 | g4dn.12xlarge-gpu | 0.0041755
274 | api.bench_nn_heterographconv.track_time | 256, 50 | s | -80% | 0.000831816 | g4dn.12xlarge-gpu | 0.00415187
268 | api.bench_nn_heterographconv.track_time | 4, 50 | s | -80% | 0.000829992 | g4dn.12xlarge-gpu | 0.00413413
287 | api.bench_node_subgraph.track_time | 'reddit', 'csc', 20000 | s | -74% | 0.005536853 | g4dn.12xlarge-gpu | 0.02155281
275 | api.bench_nn_heterographconv.track_time | 256, 200 | s | -63% | 0.007948382 | g4dn.12xlarge-gpu | 0.02149277
272 | api.bench_nn_heterographconv.track_time | 32, 200 | s | -63% | 0.007920579 | g4dn.12xlarge-gpu | 0.02135163
269 | api.bench_nn_heterographconv.track_time | 4, 200 | s | -63% | 0.007912514 | g4dn.12xlarge-gpu | 0.02132947
50 | api.bench_builtin_multi_update_all.track_time | 32, 50, 'sum' | s | -40% | 0.008825984 | g4dn.12xlarge-gpu | 0.01475789
51 | api.bench_builtin_multi_update_all.track_time | 32, 50, 'stack' | s | -36% | 0.009350794 | g4dn.12xlarge-gpu | 0.01451216
48 | api.bench_builtin_multi_update_all.track_time | 32, 5, 'sum' | s | -33% | 0.001150123 | g4dn.12xlarge-gpu | 0.00171132
53 | api.bench_builtin_multi_update_all.track_time | 32, 500, 'stack' | s | -32% | 0.120365316 | g4dn.12xlarge-gpu | 0.17576823
52 | api.bench_builtin_multi_update_all.track_time | 32, 500, 'sum' | s | -31% | 0.119928619 | g4dn.12xlarge-gpu | 0.17494971
49 | api.bench_builtin_multi_update_all.track_time | 32, 5, 'stack' | s | -30% | 0.00112368 | g4dn.12xlarge-gpu | 0.00161415
365 | api.bench_reverse.track_time | 'livejournal', 'csr' | s | -22% | 1.66E-05 | g4dn.12xlarge-gpu | 2.13E-05
280 | api.bench_node_subgraph.track_time | 'livejournal', 'csc', 5000 | s | -19% | 0.000465504 | g4dn.12xlarge-gpu | 0.00057268
281 | api.bench_node_subgraph.track_time | 'livejournal', 'csc', 20000 | s | -16% | 0.000728256 | g4dn.12xlarge-gpu | 0.00086781
26 | api.bench_builtin_apply_edges.track_time | 'ogbn-arxiv', 'csr', 128, 'u->e' | s | -16% | 0.020237462 | g4dn.12xlarge-gpu | 0.02410043
364 | api.bench_reverse.track_time | 'livejournal', 'csc' | s | -15% | 1.70E-05 | g4dn.12xlarge-gpu | 2.01E-05
0 | api.bench_add_self_loop.track_time | 'cora', 'coo' | s | -15% | 0.000558389 | g4dn.12xlarge-gpu | 0.00065861
58 | api.bench_builtin_multi_update_all.track_time | 128, 500, 'sum' | s | -14% | 0.151193593 | g4dn.12xlarge-gpu | 0.17646242
120 | api.bench_builtin_update_all_csc.track_time | 'ogbn-proteins', 'csc', 4, 'copy_u', 'sum' | s | -14% | 0.03050769 | g4dn.12xlarge-gpu | 0.03531933
55 | api.bench_builtin_multi_update_all.track_time | 128, 5, 'stack' | s | -12% | 0.001611787 | g4dn.12xlarge-gpu | 0.0018309
223 | api.bench_knn_graph.track_time | 1000, 256, 64, 'bruteforce-sharemem' | s | -11% | 0.029551419 | g4dn.12xlarge-gpu | 0.03334233
193 | api.bench_in_subgraph.track_time | 'reddit', 'csc', 5000 | s | -11% | 0.000966101 | g4dn.12xlarge-gpu | 0.00108539
527 | kernel.bench_gspmm_copy_u.track_flops | 'ogbn-proteins', 4, 'sum' | GFLOPS | -11% | 8.94 | g4dn.12xlarge-gpu | 10.03



</body>

</html>

**Comment by Rhett-Ying** [comment]
@dgl-bot run g4dn.12xlarge kernel.bench_gspmm_copy_u dmlc/0.9.x

**Comment by Rhett-Ying** [comment]
@dgl-bot run g4dn.12xlarge multigpu dmlc/0.9.x

**Comment by Rhett-Ying** [comment]
@dgl-bot run g4dn.12xlarge multigpu dmlc/0.9.x

**Comment by Rhett-Ying** [comment]
@dgl-bot run g4dn.metal multigpu dmlc/0.9.x

**Comment by Rhett-Ying** [comment]
@dgl-bot run g4dn.12xlarge api.bench_add dmlc/0.9.x

**Comment by Rhett-Ying** [comment]
Pytorch: `1.13.1+cu116`
Instance: `r6i.12xlarge, 4 GPUs`
cmd: `@dgl-bot run r6i.12xlarge all dmlc/0.9.x`
results: https://github.com/dmlc/dgl/pull/5124#issuecomment-1376333760

I have checked all the highlights shown below( cases that differ beyond 10%), all look good to me.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/ruying/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/ruying/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



  | test_name | params | unit | (1.0.x - 0.9.x) / 0.9.x * 100% | 1.0.x | machine | 0.9.x
-- | -- | -- | -- | -- | -- | -- | --




</body>

</html>

`>10%`
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/ruying/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/ruying/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



482 | api.bench_readout.track_time | 1024, 512, 'mean', 'node' | s | 94% | 0.000667397 | r6i.12xlarge-cpu | 0.00034462
-- | -- | -- | -- | -- | -- | -- | --
667 | kernel.bench_gspmm_copy_u.track_flops | 'ogbn-arxiv', 32, 'sum' | GFLOPS | 65% | 36.23 | r6i.12xlarge-cpu | 22.02
72 | api.bench_builtin_update_all_coo.track_time | 'ogbn-arxiv', 'coo', 32, 'copy_u', 'sum' | s | 52% | 0.023384133 | r6i.12xlarge-cpu | 0.01536709
626 | kernel.bench_edgesoftmax.track_time | 'ogbn-arxiv', 1 | s | 39% | 0.00186627 | r6i.12xlarge-cpu | 0.00134176
509 | api.bench_sample_neighbors.track_time | 'livejournal', 'csc', 20000, 40 | s | 38% | 0.00054947 | r6i.12xlarge-cpu | 0.00039689
16 | api.bench_builtin_apply_edges.track_time | 'cora', 'csr', 512, 'u->e' | s | 31% | 0.001096347 | r6i.12xlarge-cpu | 0.00083571
91 | api.bench_builtin_update_all_csc.track_time | 'ogbn-arxiv', 'csc', 32, 'copy_u', 'mean' | s | 30% | 0.003495885 | r6i.12xlarge-cpu | 0.00268092
532 | api.bench_to_block.track_time | 'reddit', 256, 10 | s | 28% | 0.001551482 | r6i.12xlarge-cpu | 0.00121289
508 | api.bench_sample_neighbors.track_time | 'livejournal', 'csc', 20000, 20 | s | 19% | 0.000480009 | r6i.12xlarge-cpu | 0.00040219
555 | api.bench_udf_apply_edges.track_time | 'ogbn-arxiv', 'coo', 32, 'u+v' | s | 17% | 0.039095483 | r6i.12xlarge-cpu | 0.03334293
526 | api.bench_sample_neighbors.track_time | 'reddit', 'csc', 20000, 20 | s | 16% | 0.000997417 | r6i.12xlarge-cpu | 0.00085707
147 | api.bench_edge_ids.track_time | 'cora', 'csc', 0.01, False | s | 15% | 0.000209654 | r6i.12xlarge-cpu | 0.00018166
348 | api.bench_random_walk.track_time | 'cora', 100, 2, '_node2vec' | s | 15% | 0.000119519 | r6i.12xlarge-cpu | 0.00010358
143 | api.bench_edge_ids.track_time | 'cora', 'csr', 0.01, False | s | 15% | 0.000208111 | r6i.12xlarge-cpu | 0.00018045
425 | api.bench_readout.track_time | 4, 128, 'mean', 'edge' | s | 15% | 9.29E-05 | r6i.12xlarge-cpu | 8.08E-05
566 | api.bench_udf_apply_edges.track_time | 'pubmed', 'coo', 512, 'u->e' | s | 15% | 0.015146208 | r6i.12xlarge-cpu | 0.01321277
362 | api.bench_random_walk.track_time | 'cora', 1000, 20, '_node2vec' | s | 15% | 0.001199967 | r6i.12xlarge-cpu | 0.00104686
216 | api.bench_in_degrees.track_time | 'cora', 'csc', 0.1 | s | 14% | 3.19E-05 | r6i.12xlarge-cpu | 2.80E-05
349 | api.bench_random_walk.track_time | 'cora', 100, 5, '_random_walk' | s | 13% | 0.000156238 | r6i.12xlarge-cpu | 0.00013818
77 | api.bench_builtin_update_all_coo.track_time | 'ogbn-arxiv', 'coo', 32, 'u_mul_e', 'max' | s | 13% | 9.050523754 | r6i.12xlarge-cpu | 8.0163217
308 | api.bench_nn_graphconv.track_time | 'pubmed', 256, 'pool' | s | 13% | 0.011396113 | r6i.12xlarge-cpu | 0.01009605
554 | api.bench_udf_apply_edges.track_time | 'ogbn-arxiv', 'coo', 32, 'u->e' | s | 13% | 0.013835167 | r6i.12xlarge-cpu | 0.01228588
556 | api.bench_udf_apply_edges.track_time | 'ogbn-arxiv', 'coo', 128, 'u->e' | s | 13% | 0.047520647 | r6i.12xlarge-cpu | 0.042217
330 | api.bench_node_subgraph.track_time | 'livejournal', 'csc', 200 | s | 12% | 0.000325991 | r6i.12xlarge-cpu | 0.00028998
149 | api.bench_edge_ids.track_time | 'cora', 'csc', 0.1, False | s | 12% | 0.000212522 | r6i.12xlarge-cpu | 0.00018953
523 | api.bench_sample_neighbors.track_time | 'reddit', 'csc', 5000, 20 | s | 11% | 0.000371391 | r6i.12xlarge-cpu | 0.00033348
352 | api.bench_random_walk.track_time | 'cora', 100, 10, '_node2vec' | s | 11% | 0.000159888 | r6i.12xlarge-cpu | 0.0001437
187 | api.bench_format_conversion.track_time | 'cora', ('csc', 'coo') | s | 11% | 0.000103348 | r6i.12xlarge-cpu | 9.32E-05



</body>

</html>


`<-10%`
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/ruying/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/ruying/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



301 | api.bench_nn_graphconv.track_time | 'pubmed', 4, 'gcn' | s | -100% |   | r6i.12xlarge-cpu | 0.00064843
-- | -- | -- | -- | -- | -- | -- | --
304 | api.bench_nn_graphconv.track_time | 'pubmed', 32, 'gcn' | s | -100% |   | r6i.12xlarge-cpu | 0.00090289
307 | api.bench_nn_graphconv.track_time | 'pubmed', 256, 'gcn' | s | -100% |   | r6i.12xlarge-cpu | 0.00454575
310 | api.bench_nn_graphconv.track_time | 'ogbn-arxiv', 4, 'gcn' | s | -100% |   | r6i.12xlarge-cpu | 0.0019322
313 | api.bench_nn_graphconv.track_time | 'ogbn-arxiv', 32, 'gcn' | s | -100% |   | r6i.12xlarge-cpu | 0.00408653
316 | api.bench_nn_graphconv.track_time | 'ogbn-arxiv', 256, 'gcn' | s | -100% |   | r6i.12xlarge-cpu | 0.07416058
719 | model_acc.bench_rgcn_ns.track_acc | 'ogbn-mag' | % | -100% |   | r6i.12xlarge-cpu | 0.37943203
321 | api.bench_nn_heterographconv.track_time | 32, 5 | s | -85% | 5.97E-05 | r6i.12xlarge-cpu | 0.00039236
318 | api.bench_nn_heterographconv.track_time | 4, 5 | s | -85% | 6.06E-05 | r6i.12xlarge-cpu | 0.00039195
324 | api.bench_nn_heterographconv.track_time | 256, 5 | s | -84% | 6.10E-05 | r6i.12xlarge-cpu | 0.00039215
319 | api.bench_nn_heterographconv.track_time | 4, 50 | s | -76% | 0.001034773 | r6i.12xlarge-cpu | 0.00428336
322 | api.bench_nn_heterographconv.track_time | 32, 50 | s | -76% | 0.001036298 | r6i.12xlarge-cpu | 0.00428019
325 | api.bench_nn_heterographconv.track_time | 256, 50 | s | -76% | 0.001036433 | r6i.12xlarge-cpu | 0.00426309
323 | api.bench_nn_heterographconv.track_time | 32, 200 | s | -56% | 0.010166933 | r6i.12xlarge-cpu | 0.02333434
326 | api.bench_nn_heterographconv.track_time | 256, 200 | s | -56% | 0.010288649 | r6i.12xlarge-cpu | 0.02313127
320 | api.bench_nn_heterographconv.track_time | 4, 200 | s | -55% | 0.010514655 | r6i.12xlarge-cpu | 0.02343893
447 | api.bench_readout.track_time | 256, 128, 'min', 'edge' | s | -34% | 0.000608986 | r6i.12xlarge-cpu | 0.00092791
249 | api.bench_knn_graph.track_time | 1000, 4, 8, 'bruteforce-blas' | s | -34% | 0.001463654 | r6i.12xlarge-cpu | 0.00220687
253 | api.bench_knn_graph.track_time | 1000, 4, 64, 'bruteforce-blas' | s | -33% | 0.001872971 | r6i.12xlarge-cpu | 0.00278966
309 | api.bench_nn_graphconv.track_time | 'ogbn-arxiv', 4, 'mean' | s | -33% | 0.001934974 | r6i.12xlarge-cpu | 0.00288069
239 | api.bench_in_subgraph.track_time | 'livejournal', 'csc', 20000 | s | -31% | 0.003170053 | r6i.12xlarge-cpu | 0.00456755
49 | api.bench_builtin_multi_update_all.track_time | 32, 5, 'stack' | s | -30% | 0.001431058 | r6i.12xlarge-cpu | 0.00205634
69 | api.bench_builtin_update_all_coo.track_time | 'ogbn-arxiv', 'coo', 4, 'u_mul_e', 'sum' | s | -29% | 0.00328224 | r6i.12xlarge-cpu | 0.00465375
639 | kernel.bench_gsddmm_u_dot_v.track_flops | 'ogbn-arxiv', 4, 1 | GFLOPS | -29% | 14.44 | r6i.12xlarge-cpu | 20.45
53 | api.bench_builtin_multi_update_all.track_time | 32, 500, 'stack' | s | -29% | 0.287127778 | r6i.12xlarge-cpu | 0.40612239
17 | api.bench_builtin_apply_edges.track_time | 'cora', 'csr', 512, 'u+v' | s | -28% | 0.000638103 | r6i.12xlarge-cpu | 0.00088345
59 | api.bench_builtin_multi_update_all.track_time | 128, 500, 'stack' | s | -25% | 0.764741777 | r6i.12xlarge-cpu | 1.02554492
51 | api.bench_builtin_multi_update_all.track_time | 32, 50, 'stack' | s | -25% | 0.025000189 | r6i.12xlarge-cpu | 0.03341736
93 | api.bench_builtin_update_all_csc.track_time | 'ogbn-arxiv', 'csc', 32, 'u_mul_e', 'sum' | s | -23% | 0.005429979 | r6i.12xlarge-cpu | 0.00707238
186 | api.bench_format_conversion.track_time | 'cora', ('coo', 'csc') | s | -23% | 6.39E-05 | r6i.12xlarge-cpu | 8.31E-05
11 | api.bench_builtin_apply_edges.track_time | 'cora', 'coo', 512, 'u+v' | s | -22% | 0.000949608 | r6i.12xlarge-cpu | 0.00121269
640 | kernel.bench_gsddmm_u_dot_v.track_flops | 'ogbn-arxiv', 4, 4 | GFLOPS | -20% | 10.1 | r6i.12xlarge-cpu | 12.66
638 | kernel.bench_gsddmm_u_dot_v.track_flops | 'ogbn-arxiv', 4, 0 | GFLOPS | -19% | 11.04 | r6i.12xlarge-cpu | 13.63
85 | api.bench_builtin_update_all_csc.track_time | 'ogbn-arxiv', 'csc', 4, 'copy_u', 'mean' | s | -18% | 0.00082294 | r6i.12xlarge-cpu | 0.00100644
453 | api.bench_readout.track_time | 256, 512, 'max', 'edge' | s | -18% | 0.00205373 | r6i.12xlarge-cpu | 0.00249201
455 | api.bench_readout.track_time | 256, 512, 'min', 'edge' | s | -17% | 0.002027579 | r6i.12xlarge-cpu | 0.00245264
635 | kernel.bench_edgesoftmax.track_time | 'pubmed', 1 | s | -17% | 0.000147231 | r6i.12xlarge-cpu | 0.00017793
445 | api.bench_readout.track_time | 256, 128, 'max', 'edge' | s | -17% | 0.000613415 | r6i.12xlarge-cpu | 0.00073976
57 | api.bench_builtin_multi_update_all.track_time | 128, 50, 'stack' | s | -17% | 0.06799856 | r6i.12xlarge-cpu | 0.08183195
563 | api.bench_udf_apply_edges.track_time | 'pubmed', 'coo', 32, 'u+v' | s | -17% | 0.001575077 | r6i.12xlarge-cpu | 0.00189096
533 | api.bench_to_block.track_time | 'reddit', 256, 20 | s | -16% | 0.001293662 | r6i.12xlarge-cpu | 0.00154568
10 | api.bench_builtin_apply_edges.track_time | 'cora', 'coo', 512, 'u->e' | s | -16% | 0.000928353 | r6i.12xlarge-cpu | 0.00110832
50 | api.bench_builtin_multi_update_all.track_time | 32, 50, 'sum' | s | -16% | 0.028340089 | r6i.12xlarge-cpu | 0.03369322
52 | api.bench_builtin_multi_update_all.track_time | 32, 500, 'sum' | s | -15% | 0.30117254 | r6i.12xlarge-cpu | 0.35525848
421 | api.bench_readout.track_time | 4, 128, 'max', 'edge' | s | -14% | 0.000115735 | r6i.12xlarge-cpu | 0.00013489
477 | api.bench_readout.track_time | 1024, 512, 'max', 'edge' | s | -14% | 0.006485061 | r6i.12xlarge-cpu | 0.0075235
479 | api.bench_readout.track_time | 1024, 512, 'min', 'edge' | s | -14% | 0.006449872 | r6i.12xlarge-cpu | 0.00747374
747 | model_speed.bench_sage_unsupervised_ns.track_time | 'reddit', 32, 2048 | s | -14% | 0.156665397 | r6i.12xlarge-cpu | 0.18124402
219 | api.bench_in_degrees.track_time | 'livejournal', 'csc', 0.01 | s | -13% | 0.000421852 | r6i.12xlarge-cpu | 0.00048503
14 | api.bench_builtin_apply_edges.track_time | 'cora', 'csr', 128, 'u->e' | s | -13% | 0.000334509 | r6i.12xlarge-cpu | 0.0003838
463 | api.bench_readout.track_time | 1024, 16, 'min', 'edge' | s | -12% | 0.000315598 | r6i.12xlarge-cpu | 0.00036016
469 | api.bench_readout.track_time | 1024, 128, 'max', 'edge' | s | -12% | 0.001956846 | r6i.12xlarge-cpu | 0.00222925
471 | api.bench_readout.track_time | 1024, 128, 'min', 'edge' | s | -12% | 0.001928996 | r6i.12xlarge-cpu | 0.00219164



</body>

</html>

**Comment by Rhett-Ying** [comment]
@dgl-bot run r6i.12xlarge  api.bench_builtin_update_all_coo,api.bench_udf_apply_edges,kernel.bench_gsddmm_u_dot_v dmlc/0.9.x

**Comment by Rhett-Ying** [comment]
@dgl-bot run g4dn.12xlarge multigpu.bench_multigpu dmlc/0.9.x

**Comment by Rhett-Ying** [comment]
@dgl-bot run r6i.12xlarge "api.bench_builtin_update_all_coo,api.bench_udf_apply_edges,kernel.bench_gsddmm_u_dot_v" dmlc/0.9.x

**Comment by Rhett-Ying** [comment]
@dgl-bot run r6i.12xlarge kernel.bench_gsddmm_u_dot_v dmlc/0.9.x

**Comment by Rhett-Ying** [comment]
@dgl-bot run r6i.12xlarge api.bench_builtin_update_all_coo dmlc/0.9.x

**Comment by Rhett-Ying** [comment]
@dgl-bot run r6i.12xlarge kernel.bench_gsddmm_u_dot_v dmlc/0.9.x

**Comment by Rhett-Ying** [comment]
@dgl-bot run g4dn.12xlarge api.bench_nn_graphconv dmlc/0.9.x

**Comment by Rhett-Ying** [comment]
> Finished the Regression test. Result table is at https://dgl-asv-data.s3-us-west-2.amazonaws.com/3e2b87dae378e25fce7abcd5b7488f199eeabb22_g4dn12xlarge/results/result.csv. Jenkins job link is https://dgl-jenkins-eksvpc-2136217999.us-west-2.elb.amazonaws.com/job/dgl/job/PR-5124/20/display/redirect.

`@dgl-bot run g4dn.12xlarge api.bench_nn_graphconv dmlc/0.9.x` looks good to me.

**Comment by Rhett-Ying** [comment]
@jermainewang @frozenbugs @BarclayII 
Benchmark tests are done except `//benchmarks/multigpu`. Please check the results and summaries in [CPU results](https://github.com/dmlc/dgl/pull/5124#issuecomment-1376593894), [GPU results](https://github.com/dmlc/dgl/pull/5124#issuecomment-1375259003). Both generally look good to me. I have highlighted the ones need your comments at the top.

**Comment by Rhett-Ying** [comment]
@dgl-bot run g4dn.12xlarge multigpu.bench_multigpu dmlc/0.9.x

**Comment by Rhett-Ying** [comment]
[Results](https://github.com/dmlc/dgl/pull/5124#issuecomment-1378374351) of `@dgl-bot run g4dn.12xlarge multigpu.bench_multigpu dmlc/0.9.x` looks good to me.

**Comment by Rhett-Ying** [comment]
@dgl-bot run g4dn.12xlarge api.bench_sample_neigh dmlc/0.9.x

**Comment by Rhett-Ying** [comment]
@dgl-bot run g4dn.12xlarge api.bench_sample_neigh dmlc/0.9.x

**Comment by Rhett-Ying** [comment]
@dgl-bot run g4dn.12xlarge api.bench_readout dmlc/0.9.x

**Comment by Rhett-Ying** [comment]
@dgl-bot run r6i.12xlarge kernel.bench_edgesoftmax dmlc/0.9.x

**Comment by Rhett-Ying** [comment]
@dgl-bot run r6i.12xlarge api dmlc/0.9.x

**Comment by Rhett-Ying** [comment]
Some tests seem to have performance issue according to the [results](https://github.com/dmlc/dgl/pull/5124#issuecomment-1376593894) in first run with `@dgl-bot run r6i.12xlarge api dmlc/0.9.x`, so I have re-run it and the [results](https://github.com/dmlc/dgl/pull/5124#issuecomment-1381080459) show the performance issue is not consistent. So all look good to me.

**Comment by Rhett-Ying** [comment]
Conclusion: Regress tests pass on `1.0.x` compared to `0.9.x`.

**Comment by frozenbugs** [comment]
Thanks for the great work, let's rerun it next week after all PR checkin.

**Pull request closed without merging**
