### PR TITLE
[Bug Fix][Example] hgp-sl: More info for running

### PR DESCRIPTION
**Pull request by lygztq**
## Description
Related to issue #2625 

The CUDA error is caused by out-of-memory problem.

Add more information about how to run experiments.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented
- [x] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [x] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Review by hetong007 — COMMENTED** [review]
Can we put the long summary of the datasets into a table?

**Comment by lygztq** [comment]
Changed. Actually this is from https://github.com/zhjwy9343/MVP4ModelExample

**Comment by hetong007** [comment]
The problem of our README is having multiple datasets. Table indeed looks better. 

Could you also update the README files for GXN and SAGPool?

**Comment by lygztq** [comment]
all changed

**Review by hetong007 — APPROVED** [review]
LGTM

**Pull request merged**
