### PR TITLE
[examples] fix Graphormer as key in state_dict has changed

### PR DESCRIPTION
**Pull request by songqing**
## Description

It seems the pre-trained model in the example Graphormer has changed and a key name has changed to another one, so, the example will fail as the original key can't be found.

f1

Change the key to the right name to solve the problem.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [x] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [x] All changes have test coverage
- [x] Code is well-documented
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by Rhett-Ying** [comment]
@dgl-bot

**Comment by songqing** [comment]
@Rhett-Ying Could you help to review the PR?

**Comment by Rhett-Ying** [comment]
@songqing Have you run this example and does it work as expected?

**Comment by songqing** [comment]
> @songqing Have you run this example and does it work as expected?

Yes, this is my test.
f1

**Review by Rhett-Ying — APPROVED** [review]

**Pull request merged**
