### PR TITLE
[Doc] Add distributed link prediction tutorial

### PR DESCRIPTION
**Pull request by ruisizhang123**
## Description

Add distributed link prediction tutorial which is compatible with new DGL 0.8 APIs

## Checklist

Please feel free to remove inapplicable items for your PR.

- [x]  The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x]  Changes are complete (i.e. I finished coding on this PR)
- [x]  All changes have test coverage
- [x]  Code is well-documented
- [x]  To the best of my knowledge, examples are either not affected by this change,
or have been fixed to be compatible with this change
- [x]  Related issue is referred in this PR
- [x]  If the PR is for a new model/paper, I've updated the example index [[here](https://www.notion.so/examples/README.md)](https://www.notion.so/examples/README.md).

## Changes

The new APIs in DGL 0.8 includes:

- [x]  Use `dgl.data.AsLinkPredDataset` for link prediction preprocessing
- [x]  Use `dgl.dataloading.DistEdgeDataLoader` for distributed edge iteration
- [x]  Use `EdgePredictor` for edge score computation

### CODE REVIEW

**Comment by mufeili** [comment]
Why did you include `link.pdf`?

**Comment by ruisizhang123** [comment]
> * To insert a figure in the tutorial, you can share the figure with us and we will upload it to our s3 bucket for hosting it.
> * Why did you use `.pdf` extension for the figure?
> * Have you tried building the doc locally?

1. For the pdf file, you may access it with this link: https://drive.google.com/file/d/1JS2xJurUIGey9FpzzE8AuKHiVVWbV9b1/view?usp=sharing
2. I use .pdf because it's more clear and precise when user zooms the figure. It's alright to change to other format.
3. I built the code in the doc locally and I also built the doc with .rst format. But I actually didn't built the .py doc format because I didn't find the instruction to do it.

**Comment by BarclayII** [comment]
@ruisizhang123 As long as you built the documentation within `docs` directory and didn't find any problem in the rendered HTML then you should be good.

You could build the documentation as follows:
```
cd docs
make html   # or make html-noexec if you don't want to execute the actual code there
```
And you can find the built HTMLs in `docs/build/html`.

@classicsong @zheng-da It will be appreciated if you could also take a look on this PR and see if it matches your scenario.

**Comment by ruisizhang123** [comment]
Thanks for the info @BarclayII ! 

@mufeili Yeah, I built the docs locally and found the .pdf file cannot be displayed properly. Could I have the link after u uploading it to the  s3 bucket? Other stuffs works well on my side. Thanks for the feedback!

**Comment by mufeili** [comment]
> Thanks for the info @BarclayII !
> 
> @mufeili Yeah, I built the docs locally and found the .pdf file cannot be displayed properly. Could I have the link after u uploading it to the s3 bucket? Other stuffs works well on my side. Thanks for the feedback!

You can use https://data.dgl.ai/tutorial/link.png

**Review by jermainewang — APPROVED** [review]
LGTM. Thanks for the great effort!

**Pull request merged**
