### PR TITLE
[Doc] the drawing will not disappear

### PR DESCRIPTION
**Pull request by guotong1988**
https://github.com/dmlc/dgl/pull/1004

### CODE REVIEW

**Comment by guotong1988** [comment]
On Mac, Pycharm

**Comment by yzh119** [comment]
Thanks for your contribution, however I don't think it's necessary to add such comments:
1. The [tutorial page](https://docs.dgl.ai/tutorials/basics/1_first.html) is generated from the `1_first.py`, `pause` would hang the doc generation. Even if you comment these lines, the text would appear in the tutorial, which is confusing.
2. We assume users running tutorials block by block, in this case the problem you mention will not happen.
3. Even if they run the entire `1_first.py` code, as @VoVAllen mentioned, user could browse previous generated figures by clicking at "back" button.

**Comment by guotong1988** [comment]
> 3. Even if they run the entire `1_first.py` code, as @VoVAllen mentioned, user could browse previous generated figures by clicking at "back" button.

The previous generated figures can not be found.

**Comment by yzh119** [comment]
I see where the problem is, in this tutorial we did not call `plt.show()` so the figure would not appear when you run `1_basics.py` in command line.

One solution is to add a line: `plt.show()` before `plt.close()`.

**Pull request closed without merging**
