### PR TITLE
[Determinism] Enable environment var to use cusparse spmm deterministic algorithm

### PR DESCRIPTION
**Pull request by TristonC**
## Description
Use environment variable USE_DETERMINISTIC_ALG to enable user to pick deterministic cusparse algorithm
for the issue like [7241](https://github.com/dmlc/dgl/issues/7241)

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [x] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [x] Code is well-documented
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [x] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

## Changes
- Add new environment variable USE_DETERMINISTIC_ALG
- C++ function SpMMCsr and SpMMCsrHetero will read this environment variable and pass it into CusparseCsrmm2 function
-  If set, cusparseSpMM will use the deterministic CUSPARSE_SPMM_CSR_ALG3 algo

### CODE REVIEW

**Comment by mfbalin** [comment]
Hi Triston, you can use `lintrunner -a` command to apply linting. I believe simply running `pip install lintrunner` should install it.

**Comment by TristonC** [comment]
@frozenbugs Should we update the .clang-format file? The original .clang-format failed on local machine. I then generated my local .clang-format and did the lintrunner. But it seems there are some difference here.

**Comment by frozenbugs** [comment]
@dgl-bot

**Comment by mfbalin** [comment]
@dgl-bot

**Comment by mfbalin** [comment]
@dgl-bot

**Comment by mfbalin** [comment]
@dgl-bot

**Pull request merged**
