### PR TITLE
[bugfix] Solve the boundary issue in backward function of segment sum

### PR DESCRIPTION
**Pull request by yzh119**
## Description
When apply `segment_sum` on segments with trailing zeros. The backward function would trigger out-of-boundary issue because we tried to access the `m`'th element of indices, which does not exist (the largest available index in `indices` is `m-1`).

The right solution would be adding a pseudo element in `indices` array and remove it after `scatter` and `cumsum`.

This PR also adds a unittest for this case.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented
- [x] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [x] Related issue is referred in this PR
- [x] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Review by BarclayII — APPROVED** [review]
Don't understand why this will cause a segfault though since everything is in Python.  I'm good with the PR.  Could you add a comment in the changes referring to this PR?

**Comment by yzh119** [comment]
@BarclayII it does not trigger segment fault. Just python-side index error.

**Comment by yzh119** [comment]
There is no related issue, a user found this bug when he tried to apply `sum_nodes` on batched graphs.

**Comment by IceCapriccio** [comment]
Fortunately I encounter this bug in dgl-0.5.3, and I find it was fixed in the next version.
There I will provide a simple program to reproduce this code
```python
import dgl.backend as F
data = torch.ones(6, dtype=torch.float32, requires_grad=True)
seglen = torch.tensor([1, 2, 3, 0], dtype=torch.int64)  # when trailing zeros exist in seglen, error will occur
print(F.context(seglen))
offsets = F.cumsum(F.cat([F.zeros((1,), torch.int64, 'cpu'), seglen], 0), 0)
rst = F.segment_reduce('sum', data, offsets).sum()
rst.backward()
```

**Pull request merged**
