### PR TITLE
Bring back thrust for backward compatibility

### PR DESCRIPTION
**Pull request by VoVAllen**
## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Review by BarclayII — APPROVED** [review]

**Comment by mfbalin** [comment]
How can I include thrust in src/array/cuda/rowwise_sampling.cu without it breaking the cub build? Right now, just including any header from thrust seems to break the build somehow, it seems related to CUB.

**Comment by VoVAllen** [comment]
@mfbalin Include https://github.com/dmlc/dgl/blob/f5102145a7ce753355d95d6091d2c1d7f86bba43/src/array/cuda/dgl_cub.cuh instead of directly include cub.h from official cuda

**Comment by VoVAllen** [comment]
@mfbalin thrust is no longer used in dgl. Do you want to use thrust or cub?

**Comment by mfbalin** [comment]
I needed thrust::shuffle and was able to modify dgl_cub to safely include thrust as well. I changed its contents to the following:

```/*!
 *  Copyright (c) 2021 by Contributors
 * \file cuda_common.h
 * \brief Wrapper to place cub in dgl namespace. 
 */

#ifndef DGL_ARRAY_CUDA_DGL_CUB_CUH_
#define DGL_ARRAY_CUDA_DGL_CUB_CUH_

// include cub in a safe manner
#define THRUST_CUB_WRAPPED_NAMESPACE dgl
#include "thrust/execution_policy.h"
#include "thrust/shuffle.h"
#include "thrust/random.h"

#include "cub/cub.cuh"
#undef THRUST_CUB_WRAPPED_NAMESPACE

#endif
```

I tried implementing shuffle myself using SortPairs from CUB with random keys but for some reason it didn't seem to work.

**Comment by VoVAllen** [comment]
@mfbalin Can you open a new issue to describe the problem you met?

**Comment by mfbalin** [comment]
Is including thrust in DGL discouraged? For now, I am using it for shuffle but I am planning to create a pull request after the NeuRIPS deadline. Then, I can probably replace it with some other code to avoid including thrust. I am working on a brand new sampling algorithm that seems to be faster than neighbor sampling on the GPU :)

**Comment by VoVAllen** [comment]
@mfbalin CUB is generally favored over thrust. We've also seen Pytorch replace many thrust function to cub. We won't say thrust is discouraged, but we don't have enough experience with it. If your function need to use something only available in thrust, we'll be happy to accept it.

**Pull request merged**
