### PR TITLE
[Kernel] Use omp flush in CSRIsSorted

### PR DESCRIPTION
**Pull request by classicsong**
## Description
Win CI will crash sometime on CSRIsSorted. This PR try to fix it.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR

### CODE REVIEW

**Comment by BarclayII** [comment]
LGTM.  The issue itself is quite strange since [one of the official VS tutorials](https://docs.microsoft.com/en-us/cpp/parallel/concrt/convert-an-openmp-loop-that-uses-cancellation?view=vs-2019) has very similar OpenMP code.

**Comment by classicsong** [comment]
> LGTM. The issue itself is quite strange since [one of the official VS tutorials](https://docs.microsoft.com/en-us/cpp/parallel/concrt/convert-an-openmp-loop-that-uses-cancellation?view=vs-2019) has very similar OpenMP code.

Did you encountered CI failure due to CSRIsSorted? I suppose it is a sync problem for omp shared variable.

**Comment by BarclayII** [comment]
> > LGTM. The issue itself is quite strange since [one of the official VS tutorials](https://docs.microsoft.com/en-us/cpp/parallel/concrt/convert-an-openmp-loop-that-uses-cancellation?view=vs-2019) has very similar OpenMP code.
> 
> Did you encountered CI failure due to CSRIsSorted? I suppose it is a sync problem for omp shared variable.

I did.  This is very strange as [writing the *same* value of a *primitive* type to the same memory location should work fine even if we have races](https://stackoverflow.com/questions/8315931/does-writing-the-same-value-to-the-same-memory-location-cause-a-data-race).

**Comment by classicsong** [comment]
The problem is related to omp code compiling: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=92672
Skip this problem by removing omp

**Pull request merged**
