### PR TITLE
[Dev] Resolve compile issue with gcc 11.3.0

### PR DESCRIPTION
**Pull request by mfbalin**
## Description
#4341  was creating compilation problems with later `g++` versions. This small patch seems to make DGL compilable both with g++-9, CUDA11.7 and g++-12, CUDA12.2.

@frozenbugs, @Rhett-Ying, @yaox12, @TristonC FYI. Does this patch solve the other CI problems?

### CODE REVIEW

**Comment by Rhett-Ying** [comment]
@mfbalin This patch resolves the issue mentioned [here](https://github.com/dglai/DGL_scripts/pull/43) with g++ 11.3.0 + cu117.

**Comment by mfbalin** [comment]
@caojy1998 could you check if the compilation issue is resolved on your end as well?

**Review by Rhett-Ying — APPROVED** [review]

**Comment by caojy1998** [comment]
> @caojy1998 could you check if the compilation issue is resolved on your end as well?

Seems work to me, thanks!

**Comment by TristonC** [comment]
We are moving to C++17 (align with PyTorch) which solves our CI issue. Thx

**Pull request merged**
