### PR TITLE
[Feature] Add multi-GPU UnifiedTensor unit test

### PR DESCRIPTION
**Pull request by davidmin7**
## Description
This is a followup PR of #3086, which adds a multi-gpu unit test case for the PyTorch backend using UnifiedTensor.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

## Changes
- [ ] Add multi-gpu unified tensor test.

### CODE REVIEW

**Comment by VoVAllen** [comment]
Bus error is probably related to the docker settings. Will take a look at this tommorow

**Comment by davidmin7** [comment]
> 
> 
> Bus error is probably related to the docker settings. Will take a look at this tommorow

@VoVAllen Thanks for the quick reply! Based on my quick research, I believe the docker's shared memory space is too small. Here is the relevant link: [https://github.com/pytorch/pytorch/issues/2244](url).

**Comment by classicsong** [comment]
> Bus error is probably related to the docker settings. Will take a look at this tommorow

Do we extend the shm size for the docker container?

**Comment by VoVAllen** [comment]
Fixed shared memory problem

**Review by classicsong — APPROVED** [review]
LGTM

**Pull request merged**
