### PR TITLE
[Distributed] Change rsync to scp of copy_files.py

### PR DESCRIPTION
**Pull request by aksnzhy**
## Description
Change rsync to scp of copy_files.py because rsync is very slow for big files.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR

### CODE REVIEW

**Comment by VoVAllen** [comment]
It's weird rsync is slower than scp. How much slower did you find?

**Comment by aksnzhy** [comment]
> It's weird rsync is slower than scp. How much slower did you find?

If the file is already in the remote machine, sync will do diff before sending the file.

**Comment by VoVAllen** [comment]
You can remove the `-c` option, which will only use file and creation time to diff, without calculating the checksum

**Comment by aksnzhy** [comment]
> You can remove the `-c` option, which will only use file and creation time to diff, without calculating the checksum

It seems that we don't use `-c` option here?

**Comment by VoVAllen** [comment]
The option here is ` -arvc`, removing c should be `-arv`

**Pull request merged**
