### PR TITLE
[Misc] Add clang-format.

### PR DESCRIPTION
**Pull request by frozenbugs**
## Description

Mostly auto generated from "clang-format -style=Google -dump-config > .clang-format"

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by jermainewang** [comment]
How to use this to enforce the code style?

**Comment by frozenbugs** [comment]
> 

It is doced here: https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit#heading=h.4p68oec5ndrr

**Review by jermainewang — APPROVED** [review]
Will it work for .cu and .cuh files?

**Comment by frozenbugs** [comment]
> 

Yes, it works.

**Pull request merged**
