### PR TITLE
[GraphBolt] `torch.compile()` support for `gb.expand_indptr`.

### PR DESCRIPTION
**Pull request by mfbalin**
## Description
Details in this document by PyTorch developers: https://docs.google.com/document/d/1W--T6wz8IY8fOI0Vm8BF44PdBgs283QvpelJZWieQWQ/edit?usp=sharing

This PR utilizes `torch>=2.2.0` features.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [ ] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by mfbalin** [comment]
There is an issue, I hope pytorch developers can help fix it: https://github.com/pytorch/pytorch/issues/121080

**Comment by frozenbugs** [comment]
@mfbalin can you fix the build?

**Comment by mfbalin** [comment]
> @mfbalin can you fix the build?

I can not, we need to start depending on Torch 2.2 instead of 2.0.

**Comment by frozenbugs** [comment]
> > @mfbalin can you fix the build?
> 
> I can not, we need to start depending on Torch 2.2 instead of 2.0. The CI needs to be updated.

We are deprecating Torch 1.3 (oldest Torch version: 2.0) in DGL 2.1, likely we will not move to 2.2 in near future. If it requires 2.2, let's table the change until then?

**Comment by mfbalin** [comment]
> > > @mfbalin can you fix the build?
> > 
> > 
> > I can not, we need to start depending on Torch 2.2 instead of 2.0. The CI needs to be updated.
> 
> We are deprecating Torch 1.3 (oldest Torch version: 2.0) in DGL 2.1, likely we will not move to 2.2 in near future. If it requires 2.2, let's table the change until then?

Sure. Which release of DGL do you think will move to 2.2 do you think?

**Comment by mfbalin** [comment]
> > > @mfbalin can you fix the build?
> > 
> > 
> > I can not, we need to start depending on Torch 2.2 instead of 2.0. The CI needs to be updated.
> 
> We are deprecating Torch 1.3 (oldest Torch version: 2.0) in DGL 2.1, likely we will not move to 2.2 in near future. If it requires 2.2, let's table the change until then?

Also, it may be possible to still get this PR through by adding version checks on certain parts of the code. I will see if it is easily doable. Then, maybe we won't have to wait that long.

**Comment by mfbalin** [comment]
The CI will hopefully pass now.

**Comment by mfbalin** [comment]
@frozenbugs got the CI to pass. I think it is ready to review.

**Comment by mfbalin** [comment]
@Rhett-Ying Can we add torch 2.2 to the CI also so that the code that is blocked can be checked? I tested locally with a docker container that has `2.2.0a0+81ea7a4`.

**Review by frozenbugs — APPROVED** [review]

**Pull request merged**
