### PR TITLE
[NN]: EdgeWeightNorm for tensorflow backend

### PR DESCRIPTION
**Pull request by aramakus**
## Description
Support for Tensorflow backend for EdgeWeightNorm and GraphConv

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [x] Code is well-documented
- [x] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

## Changes
<!-- You could use following template
- [ ] EdgeWeightNorm, TF support (currently Pytorch only)
- [ ] GraphConv support for EdgeWeightNorm

## Comments
This PR does not add new functionality, only extends existing one to support Tensorflow backend (currently PyTorch only)

### CODE REVIEW

**Comment by aramakus** [comment]
Guys, I am using this functionality for my project and would like to share it with everyone. Please consider review this PR and adding the code to the next release of DGL

**Comment by Rhett-Ying** [comment]
@dgl-bot

**Comment by frozenbugs** [comment]
Hi @aramakus , can you also add unit test for your change to prevent regression when other people touches your code?

**Comment by Rhett-Ying** [comment]
@aramakus  pls fix the lint check failure

**Comment by aramakus** [comment]
@Rhett-Ying fixed linting, get no errors for the file I added to
@frozenbugs copied unittest from respective pytorch file, no changes but one line

**Comment by Rhett-Ying** [comment]
@dgl-bot

**Comment by Rhett-Ying** [comment]
@dgl-bot

**Comment by Rhett-Ying** [comment]
@aramakus  is it possible to verify on your local side before submit commit?

**Comment by Rhett-Ying** [comment]
@dgl-bot

**Comment by aramakus** [comment]
@Rhett-Ying , I was not able to easily set up environment to run tests you requested, hence fixes based of logs. Will set more time aside to set it up in the upcoming week.

**Comment by Rhett-Ying** [comment]
@aramakus
1. build DGL on your own
2. run the test you modified via specifying the DGL path you just built: `DGL_HOME=/home/ubuntu/dgl DGL_LIBRARY_PATH=$DGL_HOME/build PYTHONPATH=tests:$DGL_HOME/python:$PYTHONPATH DGLBACKEND=tensorflow python3 -m pytest tests/compute/test_nn.py`

**Comment by mufeili** [comment]
1. You also need to import `EdgeWeightNorm` [here](https://github.com/dmlc/dgl/blob/master/python/dgl/nn/tensorflow/conv/__init__.py#L8).
2. You can also move the unit test you defined to a new script and test your module/function there.

**Comment by jermainewang** [comment]
Hi @aramakus , we are closing this PR as it hasn't been active for a while. Feel free to reopen if you wish to keep working on it.

**Pull request closed without merging**
