### PR TITLE
[CI]upgrade pytorch to 1.13+cpu_cu116

### PR DESCRIPTION
**Pull request by Rhett-Ying**
## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [ ] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by mfbalin** [comment]
Does this PR deprecate CUDA 10.2 support?

**Comment by Rhett-Ying** [comment]
This PR is deprecating pytorch 1.12 in CI and as pytorch 1.13 requires CUDA >=11.6, so cu102/113 are being deprecated as well.
And in the next DGL release, the minimum pytorch version is 1.13 and cu116. @BarclayII @frozenbugs please add more comments on this.

**Comment by frozenbugs** [comment]
Also change https://github.com/dmlc/dgl/blob/master/script/create_dev_conda_env.sh?

**Comment by frozenbugs** [comment]
> This PR is deprecating pytorch 1.12 in CI and as pytorch 1.13 requires CUDA >=11.6, so cu102/113 are being deprecated as well. And in the next DGL release, the minimum pytorch version is 1.13 and cu116. @BarclayII @frozenbugs please add more comments on this.

Yes, CUDA 10.2 is pretty old now, pytorch is deprecating 11.6, so it is time to catch up.

**Review by frozenbugs — APPROVED** [review]

**Comment by Rhett-Ying** [comment]
As tesnsorflow 2.3.0 does not support cuda 11.6, let's skip it for now.

**Pull request merged**
