### PR TITLE
[Bug] Fix problem with ShaDowKHopSampler working with reverse edge type exclusion

### PR DESCRIPTION
**Pull request by BarclayII**
See https://discuss.dgl.ai/t/providing-reverse-edge-type-with-shadowkhop-sampler/2999 for details.

### CODE REVIEW

**Comment by BarclayII** [comment]
@jermainewang Can I have this fix in the next post-release with PyTorch 1.12 + CUDA 11.6 support?  This seems to be an issue with no workaround.

**Comment by jermainewang** [comment]
Could you pls add a ut?

**Comment by BarclayII** [comment]
> Could you pls add a ut?

Already added.

**Review by jermainewang — APPROVED** [review]
LGTM

**Pull request merged**
