### PR TITLE
[Model] Simplify labor example, add proper inference code

### PR DESCRIPTION
**Pull request by mfbalin**
## Description
Clean the code after initial PR, add instructions on how to run and plot results.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [x] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by mfbalin** [comment]
@frozenbugs @peizhou001 could you take a look?

**Comment by frozenbugs** [comment]
> @frozenbugs @peizhou001 could you take a look? Any suggestions on how to improve this example further?

The key to a usage-demonstration example is, to make it as simple as possible and highlight the demonstrated usage.
In the long run, we will start promote the examples in the new example structure as we kicked off in the https://github.com/dmlc/dgl/tree/master/examples. You can see there are various example directories that groups examples for different purpose.

For labor sample, I would suggest you focus on the sampling part, and make it an advanced example in examples/advanced/labor/. You can use this [code](https://github.com/dmlc/dgl/blob/master/examples/sampling/node_classification.py), which focuses on highlighting neighbor sampling, as an example for your labor example, to create an similar example but only replace the sampling code with your sampler and GPU cache, and highlight them with consistent format, such that you can attract users' eyes without adding frictions when they read your example.

**Comment by frozenbugs** [comment]
For the examples in example zoo which demonstrates users' research work, I think your current code is good enough.

**Review by frozenbugs — APPROVED** [review]

**Comment by mfbalin** [comment]
Then I will create more PRs in the future that follow similar conventions to the DGL example you pointed out to better highlight different features.

**Pull request merged**
