### PR TITLE
[Misc] Mofidy cugraph tests to avoid `import dgl`

### PR DESCRIPTION
**Pull request by Skeleton003**
## Description

Mofidy cugraph test files to avoid `import dgl`.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [ ] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by mfbalin** [comment]
What happens when `dgl` is imported directly? I just wanted to know as the PR description is not very clear about the reason.

**Comment by Skeleton003** [comment]
> What happens when `dgl` is imported directly? I just wanted to know as the PR description is not very clear about the reason.

These changes are suggested by @Rhett-Ying . The PR [#6986], which makes use of `dgl.sparse`, failed CI in stage **PyTorch Cugraph GPU Unit test**, reporting "_FileNotFoundError: Cannot find DGL C++ sparse library at /home/ubuntu/jenkins/workspace/dgl_PR-6986/build/dgl_sparse/libdgl_sparse_pytorch_2.0.0.so_". We guess this is because `dgl.sparse` is not built in **PyTorch Cugraph GPU Unit test** of CI.

However, I am still not sure whether these changes will help PR [#6986] pass **PyTorch Cugraph GPU Unit test**. I will be more than excited to learn other solutions if you @mfbalin  have more insights into this problem.

**Comment by mfbalin** [comment]
> > What happens when `dgl` is imported directly? I just wanted to know as the PR description is not very clear about the reason.
> 
> These changes are suggested by @Rhett-Ying . The PR [#6986], which makes use of `dgl.sparse`, failed CI in stage **PyTorch Cugraph GPU Unit test**, reporting "_FileNotFoundError: Cannot find DGL C++ sparse library at /home/ubuntu/jenkins/workspace/dgl_PR-6986/build/dgl_sparse/libdgl_sparse_pytorch_2.0.0.so_". We guess this is because `dgl.sparse` is not built in **PyTorch Cugraph GPU Unit test** of CI.
> 
> However, I am still not sure whether these changes will help PR [#6986] pass **PyTorch Cugraph GPU Unit test**. I will be more than excited to learn other solutions if you @mfbalin have more insights into this problem.

Thank you for the reply. I asked because I wanted to learn from you, not the other way around :).

I suspect the changes in this PR will not help solve the CI issue. Let me think about it as well.

**Comment by mfbalin** [comment]
https://softwareengineering.stackexchange.com/a/187471

Here, it says that `import dgl` and `from dgl import bla bla` is doing the same thing.

**Pull request closed without merging**
