### PR TITLE
[Model][MXNet] MXNet Tree LSTM example

### PR DESCRIPTION
**Pull request by szha**

### CODE REVIEW

**Comment by szha** [comment]
@yzh119 no I haven’t. MXNet supports automatically downloading glove embeddings so I will do that instead.

**Comment by szha** [comment]
@jermainewang I ran the default setting as is, so 25?

**Comment by szha** [comment]
Actually I just realized that there’s coupling with embedding in the SST class, and we cannot add other libraries as dependencies yet so I’d have to use it for now. I’m adding an extra option to automatically download the glove embedding (since there’s download function in dgl.data) in the training script. Feel free to let me know if this is inappropriate and I can revert.

**Comment by jermainewang** [comment]
You could put the download and dependencies in your example folder. Just need to clearly state the dependency in the readme.

**Comment by szha** [comment]
I wanted to use gluonnlp for this. The thing is, the vocabulary of SST is never exposed, so I cannot shuffle the embedding outside of SST class beforehand.

**Pull request closed without merging**
