### PR TITLE
[NN] Added activation function as an optional parameter to GINConv

### PR DESCRIPTION
**Pull request by SwamySriharshAI**
## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [x] Code is well-documented
- [x] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [x] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Review by jermainewang — APPROVED** [review]
LGTM. Thanks for the contribution!

**Comment by SwamySriharshAI** [comment]
@jermainewang As the PR is still open, I made new commits to it.

**Comment by jermainewang** [comment]
Your latest commit changed the module interface. I'd like to hear authors' opinions @VoVAllen @hetong007 .

**Comment by hetong007** [comment]
If I understand it correctly, the original interface allows users to pass an arbitrarily complex function, while the current proposed change only supports a `nn.Linear` layer. IMHO this compromises too much flexibility.

**Comment by SwamySriharshAI** [comment]
I agree with @hetong007 
After using the other models (like SAGEConv), When I try to use GIN, It just seems a bit odd because of the way it takes input, unlike other models.

If we don't want to apply this change at the moment, I can revert that back and make a new commit by only leaving bias and activation as optional parameters.

**Comment by hetong007** [comment]
@SwamySriharshAI The idea of a new commit sounds great. Would be good already to include the bias and activation as optional parameters, without breaking the interface.

**Comment by SwamySriharshAI** [comment]
@hetong007 Sure, I will make the changes and commit again.

**Review by jermainewang — APPROVED** [review]

**Review by hetong007 — APPROVED** [review]

**Pull request merged**
