### PR TITLE
[dev] limit numpy < 2.0.0 for compatibility

### PR DESCRIPTION
**Pull request by Rhett-Ying**
## Description

let's limit the numpy < 2.0.0 for now. we need to support 2.0.0 in near future.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [ ] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by Rhett-Ying** [comment]
This PR is replacing https://github.com/dmlc/dgl/pull/7478

**Comment by Rhett-Ying** [comment]
related to https://github.com/dmlc/dgl/issues/7468

**Comment by Rhett-Ying** [comment]
@dgl-bot

**Comment by jakirkham** [comment]
Thanks Rhett! 🙏

It's good to be safe 🙂

Though am wondering if this is actually needed ( https://github.com/dmlc/dgl/issues/7468#issuecomment-2196270492 )?

**Comment by Skeleton003** [comment]
> Thanks Rhett! 🙏
> 
> It's good to be safe 🙂
> 
> Though am wondering if this is actually needed ( [#7468 (comment)](https://github.com/dmlc/dgl/issues/7468#issuecomment-2196270492) )?

Thank you @jakirkham . To support numpy>=2.0.0 we need to set the minimum supported torch version to 2.3.0. Our team will discuss this issue at the Monday meeting.

**Comment by jakirkham** [comment]
Thanks for following up! 🙏

That's certainly one approach

Am wondering if another might simply be to inform users they need to update PyTorch if they want to use NumPy 2

Thinking this as in many ways this is a problem with old PyTorch packages' metadata in that they don't explicitly disallow being installed with NumPy 2. If they did, then users would not be able to install older PyTorch packages with NumPy 2. It doesn't sound like this is an issue with DGL itself

**Comment by Rhett-Ying** [comment]
As this issue is not directly caused by DGL, we'd like to revert this PR. And if anyone hit this issue while using torch < 2.3, it's user's responsibility to either downgrade numpy or upgrade torch.

**Comment by Rhett-Ying** [comment]
> > Thanks Rhett! 🙏
> > It's good to be safe 🙂
> > Though am wondering if this is actually needed ( [#7468 (comment)](https://github.com/dmlc/dgl/issues/7468#issuecomment-2196270492) )?
> 
> Thank you @jakirkham . To support numpy>=2.0.0 we need to set the minimum supported torch version to 2.3.0. Our team will discuss this issue at the Monday meeting.

No. DGL will not set the minimum of torch to 2.3.0.

**Comment by jakirkham** [comment]
Thank you both! 🙏

**Pull request merged**
