### PR TITLE
[Performance] Prefer parallelized conversion to CSC from COO instead of transposing CSR

### PR DESCRIPTION
**Pull request by BarclayII**
This makes `g.create_formats_()` significantly faster for large graphs such as OGB-MAG240M.

### CODE REVIEW

**Review by jermainewang — APPROVED** [review]

**Comment by jermainewang** [comment]
Approved but would you mind adding some comments to these methods for what is the preference order of different formats?

**Comment by BarclayII** [comment]
Do you think this is the proper solution?  I'm not sure if this will have any side effects such as regressions on say GPU conversions.

**Comment by jermainewang** [comment]
@VoVAllen This is an example PR that needs benchmark tests triggered. How to test it right now?

**Comment by BarclayII** [comment]
I would like to have this PR merged since #2810 depends on this PR performance-wise.

**Pull request merged**
