### PR TITLE
[Doc] Fix a typo in edgeconv.py

### PR DESCRIPTION
**Pull request by Michael1015198808**
## Description

Fix typos in `zero-in-degree`, which were misspelled as `zere-in-degree`.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [x] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] ~~All changes have test coverage~~
- [ ] ~~Code is well-documented~~
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] ~~Related issue is referred in this PR~~
- [ ] ~~If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).~~

## Changes

- [x] Fix typos in `zero-in-degree` in following modules
  + `dgl.nn.tensorflow.conv.edgeconv`

### CODE REVIEW

**Review by BarclayII — APPROVED** [review]

**Comment by BarclayII** [comment]
@dgl-bot

**Comment by Michael1015198808** [comment]
Hello, could you please check the log? I have no idea why simply fixing typos in comments will result in fail of CI 😢

**Comment by mufeili** [comment]
> Hello, could you please check the log? I have no idea why simply fixing typos in comments will result in fail of CI 😢

I think this is due to another random failure irrelevant to your changes. Let me try re-triggering the CI.

**Comment by mufeili** [comment]
@dgl-bot

**Comment by Michael1015198808** [comment]
> > Hello, could you please check the log? I have no idea why simply fixing typos in comments will result in fail of CI 😢
> 
> I think this is due to another random failure irrelevant to your changes. Let me try re-triggering the CI.

Thanks! I have created another PR and when it was merged, it triggered a failure. I felt sorry at first, and later realized it may due to some randomness (Because the following commits irrelevant to my changes passed tests.). :joy:

**Comment by mufeili** [comment]
@dgl-bot

**Comment by Michael1015198808** [comment]
🤔 Quite strange, is it allowed to directly merge a PR without passing CI/CD?

**Comment by mufeili** [comment]
> 🤔 Quite strange, is it allowed to directly merge a PR without passing CI/CD?

It finally works. I've merged the PR. Thanks for your patience :)

**Pull request merged**
