### PR TITLE
[Graphbolt][CUDA] Benchmark for `index_select_csc`

### PR DESCRIPTION
**Pull request by mfbalin**
## Description
Benchmarks the functionality in #6645.

### CODE REVIEW

**Comment by mfbalin** [comment]
@caojy1998

**Comment by mfbalin** [comment]
The benchmark can be found here: https://github.com/mfbalin/gnn_dataloading_primitives/tree/main/benchmarks/graphbolt

**Comment by caojy1998** [comment]
This benchmark has been finished. Here is a result for reference.
Time:
image
image
image
image
image
image

Throughput:
image
image
image
image
image

**Comment by mfbalin** [comment]
@caojy1998 benchmark result image links are broken.

**Comment by caojy1998** [comment]
> @caojy1998 benchmark result image links are broken.

That's strange. I can see the image. Is there a probable reason for this?

**Comment by caojy1998** [comment]
> @caojy1998 benchmark result image links are broken.

Oh I see. You do not have the access to the link. I will re-paste it here.

**Comment by mfbalin** [comment]
Incorporated into benchmarks repository, so closing this.

**Pull request closed without merging**
