### PR TITLE
[Feature] Cache node embeddings in GPUs

### PR DESCRIPTION
**Pull request by zheng-da**
## Description
This PR is to cache node embeddings in GPUs. for subgraph training. the entire node features are stored in CPU memory. to reduce data movement, we can cache some of the node features in GPU (because of power-law distribution, caching a small number of node features can reduce majority of data movement).

The current implementation supports caching in a single GPU. I'll add multi-GPU support in the next PR.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR

### CODE REVIEW

**Comment by jermainewang** [comment]
What's the scenario of this change?

**Comment by zheng-da** [comment]
for subgraph training. the entire node features are stored in CPU memory. to reduce data movement, we can cache some of the node features in GPU (because of power-law distribution, caching a small number of node features can reduce majority of data movement).

**Comment by jermainewang** [comment]
Spent some time with @ylfdq1118 reading the codes and discussed about this. Our major concerns are the semantics. For example, what will happen for the following situations (suppose we have a graph of 10 nodes):

1. Cached nodes and fetched nodes are different.
```python
g.ndata['h'] = ... # some data on cpu
g.cache_nodes([1, 2, 3], mx.gpu(0))
g.nodes[[4, 5, 6]].data['h']  # which device is this?
```

2. Cached nodes and fetched nodes overlap:
```python
g.ndata['h'] = ... # some data on cpu
g.cache_nodes([1, 2, 3], mx.gpu(0))
g.nodes[[3, 4, 5]].data['h']  # which device is this?
```

3. Multiple cached devices:
```python
g.ndata['h'] = ... # some data on cpu
g.cache_nodes([1, 2, 3], mx.gpu(0))
g.cache_nodes([2, 3, 4], mx.gpu(1))
g.nodes[[3, 4, 5]].data['h']  # which device is this?
```

4. Cache invalidation:
```python
g.ndata['h'] = ... # some data on cpu
g.cache_nodes([1, 2, 3], mx.gpu(0))
g.nodes[[2, 3]].data['h'] = ...  # some new value
g.nodes[[2, 3, 4]].data['h']  # what value should this be?
```


Another question is how much gain we could actually get by caching? Although we can save the amount of data transferred from CPU -> GPU, but we also introduce an extra GPU->GPU copy to assemble the required data.

**Comment by zheng-da** [comment]
This is mainly designed for sampled subgraphs. But you are right that API added to DGLGraph may not be appropriate. Maybe the better place is at the subgraph sampler. We can add a new flag in the sampler to turn on caching when the sampling starts and clear caching when sampling ends.

**Comment by zheng-da** [comment]
We can safely assume that GPU->GPU copy (200-300GB/s) is much faster than CPU->GPU copy (~10GB/s)

**Comment by jermainewang** [comment]
Yeah, putting it in sampler is a good idea.

**Comment by eric-haibin-lin** [comment]
What will the cache API for sampler be like? It doesn't sound very intuitive..

**Comment by zheng-da** [comment]
like this: https://github.com/dmlc/dgl/pull/316/files#diff-2d5c43ba57d0c4ef5fd9194f472f6045R65

**Comment by jermainewang** [comment]
Da, could you paste the interface here so it's easier to discuss?

**Comment by zheng-da** [comment]
I would suggest something like this: add two arguments `cache_nodes` and `subgraph_ctx`.
`cache_nodes` specifies which nodes should be cached. `subgraph_ctx` specifies the context where the returned subgraph should be. `subgraph_ctx` can be a list of contexts. We can use `subgraph_ctx` to infer where the node embeddings should be cached.
What do you think?

```python
def NeighborSampler(g, batch_size, expand_factor, num_hops=1,
                    neighbor_type='in', node_prob=None, seed_nodes=None,
                    shuffle=False, num_workers=1, max_subgraph_size=None,
                    return_seed_id=False, prefetch=False, cache_nodes=None, subgraph_ctx=F.cpu()):
```

**Comment by zheng-da** [comment]
It should be both. If the graph uses adjacency matrix for computation, the context should specify the context of the adjacency matrix.

**Comment by jermainewang** [comment]
Currently, user needs to specify the context when getting the adjacency matrix:
https://github.com/dmlc/dgl/blob/534ea8c97037b74fafadebc53693848073919132/python/dgl/graph.py#L2700-L2721

What do you mean by putting the graph adj in GPU?

**Comment by zheng-da** [comment]
It seems I didn't make this modification in this PR. I'm not sure what you mean.

**Comment by jermainewang** [comment]
```python
import mxnet as mx
g = ... # some graph.
sampler = NeighborSampler(g, batch_size=10, expand_factor, num_hops=1,
                    neighbor_type='in', node_prob=None, seed_nodes=None,
                    shuffle=False, num_workers=1, max_subgraph_size=None,
                    return_seed_id=False, prefetch=False, cache_nodes=None,
                    subgraph_ctx=mx.gpu(0)):
for sg in sampler:
  adj = sg.adjacency_matrix()
  print(adj.context)   # what will be the context here?
```

**Comment by zheng-da** [comment]
Because the API requires users to provide a context, the returned adjacency matrix will be in the context specified by the user.

**Comment by jermainewang** [comment]
So the adj will be copied from GPU(0) to CPU?

**Comment by jermainewang** [comment]
What happened when the CSR graph index is moved to DGL? Did we plan to support graph on GPU?

**Comment by zheng-da** [comment]
It shouldn't affect the adjacency_matrix API. the CSR graph index will be in CPU, but it's not seen by users, so the context of the CSR graph index isn't important, as long as we make its interaction with other components correct.

**Comment by jermainewang** [comment]
I didn't get it. Isn't the graph index on GPU if `subgraph_ctx` is specifed as GPU?

**Comment by zheng-da** [comment]
`subgraph_ctx` should be the context observable by users. The graph index is the underlying implementation. It's not seen by users. `subgraph_ctx` isn't necessary to specify how exactly the underying system works. After all, `subgraph_ctx` is just part of API.

**Comment by jermainewang** [comment]
I'm confused. So I was a user, what should I expect when `subgraph_ctx` is GPU? What will be on GPU then?

**Comment by zheng-da** [comment]
When `subgraph_ctx` is GPU, users should see that the node data and edge data are stored in GPU. I think what you are confused is why `g.adjacency_matrix()` by default returns an adjacency matrix stored in CPU. To solve the problem, I think we should make the default context `None`, which means the context where the graph is stored.

**Comment by jermainewang** [comment]
> To solve the problem, I think we should make the default context None, which means the context where the graph is stored.

I'm afraid this will be more confusing because there is no "default" context for a `DGLGraph`.

**Pull request closed without merging**
