### PR TITLE
[Misc] Make code compilable with GCC 13

### PR DESCRIPTION
**Pull request by mfbalin**
## Description
Updating METIS to the latest master branch. GKlib was taken out of METIS so adding it manually as a submodule. Adding missing include. The code compiles with GCC 13 (shipped with Ubuntu 24.04) with this PR.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [ ] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by Rhett-Ying** [comment]
@mfbalin why do we need to be compatible with gcc 13? and gklib is the only blocker to be compatible with gcc 13?

**Comment by mfbalin** [comment]
> @mfbalin why do we need to be compatible with gcc 13? and gklib is the only blocker to be compatible with gcc 13?

Old METIS code had a compile error with GCC 13. GKLib shipped inside METIS before but now it is not so we add it as a submodule. Updating the software version should improve the experience.

We don't have to be compatible but GCC 13 ships with Ubuntu 24.04.

**Comment by mfbalin** [comment]
It is better to be compatible with this little effort.

**Comment by Rhett-Ying** [comment]
@classicsong Please help review change on `GKlib` as it's quite long ago since last change, so I'm not sure if it's safe to change it to latest.

**Comment by Rhett-Ying** [comment]
@mfbalin As there's large time gap between the current one we're using and the new one you'd apply, it's risky and requires more reviews from other team member even the author. Let's hold on for now.

**Comment by frozenbugs** [comment]
Let's aim GS 0.3 release around July 2024, before the release there will be comprehensive test.

**Comment by mfbalin** [comment]
@frozenbugs I think GS 0.3 release is out.

**Review by frozenbugs — APPROVED** [review]

**Comment by Rhett-Ying** [comment]
@frozenbugs 
do we or GS run comprehensive test over this PR? As I just disabled the whole distributed tests, please run them manually.

**Comment by frozenbugs** [comment]
> @frozenbugs do we or GS run comprehensive test over this PR? As I just disabled the whole distributed tests, please run them manually.

GS will do it.

**Comment by Rhett-Ying** [comment]
As we discussed offline, let's merge it into master and ask GS to help test it thoroughly.
@mfbalin As I've just disabled all distributed test in CI, please run them manually before merge it into master branch. Thanks.

**Comment by Rhett-Ying** [comment]
I checked the CI and it runs distributed tests. Let's merge it.

**Pull request merged**
