### PR TITLE
[Misc] Fix the directory of DGL_DOWNLOAD_DIR

### PR DESCRIPTION
**Pull request by songqing**
## Description

DGL_DOWNLOAD_DIR's default value is '${HOME}/.dgl', see [doc](https://github.com/dmlc/dgl/blob/master/docs/source/env_var.rst).
However, the value of DGL_DOWNLOAD_DIR in some scripts is '${PWD}', and it'll be the DGL home directory, which will cause to download all the data files in the code directory, and can make people feel confused.
So, changing all the value of DGL_DOWNLOAD_DIR to '${HOME}/.dgl'.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [.] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [.] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [.] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [.] All changes have test coverage
- [.] Code is well-documented
- [.] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by songqing** [comment]
Or I can change the value of DGL_DOWNLOAD_DIR to '${DGL_HOME}/_download', I see '_download' is used in some places.

**Comment by songqing** [comment]
@frozenbugs Could you help to review this PR?

**Comment by frozenbugs** [comment]
@dgl-bot

**Comment by frozenbugs** [comment]
@songqing what about change it to ${DGL_HOME}/build or ${DGL_HOME}/downloads?

Both of them are reserved in .[gitingore](https://github.com/dmlc/dgl/blob/master/.gitignore#L14).

**Comment by songqing** [comment]
> @songqing what about change it to ${DGL_HOME}/build or ${DGL_HOME}/downloads?
> 
> Both of them are reserved in .[gitingore](https://github.com/dmlc/dgl/blob/master/.gitignore#L14).

OK, I have changed it to ${DGL_HOME}/_download, which is also in .gitignore and maybe used before. 
f1

**Comment by frozenbugs** [comment]
@Rhett-Ying FYI.

**Pull request merged**
