### PR TITLE
[Bugfix] Fix Correct&Smooth

### PR DESCRIPTION
**Pull request by skepsun**
## Description

There are some problems in DGL implementation of C&S, including:
1. wrong variable usage in Smooth:
```
self.prop2 = LabelPropagation(num_smoothing_layers,
                              smoothing_alpha,
                              correction_adj)
```
2. autoscale does not work:
```
cs = CorrectAndSmooth(num_correction_layers=args.num_correction_layers,
                      correction_alpha=args.correction_alpha,
                      correction_adj=args.correction_adj,
                      num_smoothing_layers=args.num_smoothing_layers,
                      smoothing_alpha=args.smoothing_alpha,
                      smoothing_adj=args.smoothing_adj,
                      scale=args.scale)
```
The metrics in example README.MD should be updated, here are my results:
##### ogbn-arxiv

* **MLP + C&S**

```bash
python main.py --dropout 0.5
python main.py --pretrain --correction-adj DA --smoothing-adj AD --autoscale
```

* **Linear + C&S**

```bash
python main.py --model linear --dropout 0.5 --epochs 1000
python main.py --model linear --pretrain --correction-alpha 0.8 --smoothing-alpha 0.6 --correction-adj AD --autoscale
```

##### ogbn-products

* **Linear + C&S**

```bash
python main.py --dataset ogbn-products --model linear --dropout 0.5 --epochs 1000 --lr 0.1
python main.py --dataset ogbn-products --model linear --pretrain --correction-alpha 1. --smoothing-alpha 0.9
```

#### ogbn-arxiv

|                 |  MLP  | MLP + C&S | Linear | Linear + C&S |
| :-------------: | :---: | :-------: | :----: | :----------: |
| Results(Author) | 55.58 |   68.72   | 51.06  |    70.24     |
|  Results(DGL)   | 56.55 |   70.93   | 52.48  |    72.60     |

#### ogbn-products

|                 | Linear | Linear + C&S |
| :-------------: | :----: | :----------: |
| Results(Author) | 47.67  |    82.34     |
|  Results(DGL)   | 47.65  |    82.86     |

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [x] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by VoVAllen** [comment]
@xnuohz Can you take a look?
cc @mufei

**Comment by mufeili** [comment]
Thank you for the fix. Can you also update the README file?

**Comment by skepsun** [comment]
README.md has been updated.

**Review by mufeili — APPROVED** [review]
LGTM

**Pull request merged**
