### PR TITLE
[Model] Implemented SubgraphX Explainer for Homogeneous graph

### PR DESCRIPTION
**Pull request by kunmukh**
## Description
Implemented SubgraphX Explainer (https://arxiv.org/pdf/2102.05152.pdf) for Homogeneous Graphs. Original PR: https://github.com/dmlc/dgl/pull/4913, this PR was created as the original PR went out of date. 

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [x] All changes have test coverage
- [x] Code is well-documented
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [x] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

## Changes
- [x] Added a new class, SubgraphXExplainer for homogeneous graph explanation.

The output of the model has been manually verified on MUTAG dataset. A visualization script was created to visualize the mutag dataset (external ref: https://gist.github.com/kunmukh/06d948b6b730447baa932873026e15da). Unfortunately, there's no ground truth for the explanation except for what is mentioned in the research paper, so we cannot quantify the model's performance. Instead, we manually investigated the results and confirmed that they aligned well with human intuition and findings of the research paper.

Inline documentation is added following the original style, and an example of using the module is included in the documentation.

### CODE REVIEW

**Comment by mufeili** [comment]
@dgl-bot

**Comment by mufeili** [comment]
@dgl-bot

**Comment by mufeili** [comment]
@dgl-bot

**Comment by mufeili** [comment]
@dgl-bot

**Comment by mufeili** [comment]
```
tests/python/pytorch/nn/test_nn.py::test_subgraphx[False-2-idtype0-g5] Cancelling nested steps due to timeout
```

**Comment by mufeili** [comment]
@kunmukh  Did you locally test all possible test graphs that might be triggered by the CI?

**Comment by mufeili** [comment]
@dgl-bot

**Comment by mufeili** [comment]
@dgl-bot

**Comment by mufeili** [comment]
@Rhett-Ying It seems that this PR always failed for Torch CPU (Win64) Unit test with "Sending interrupt signal to process" after 30m. Is this timeout? Any clues or suggestions?

**Comment by mufeili** [comment]
@kunmukh Currently the unit tests are invoked for 6 graphs in total with

```
@pytest.mark.parametrize("g", get_cases(["homo"], exclude=["zero-degree"]))
```

Could you try only invoking the test for a single small graph and see if it works?

**Comment by Rhett-Ying** [comment]
@kunmukh could you profile how much time it takes for the newly added test?  it may take too long time than expected.

**Comment by kunmukh** [comment]
@mufeili I chose the first homogeneous graph defined, which has 10 nodes and 17 edges. It was completed in ~3 mins. Can you trigger the `dgl-bot`?

image

**Comment by mufeili** [comment]
@dgl-bot

**Comment by mufeili** [comment]
That's great! Is it possible to reduce the test time to say 20 seconds? Let's say the CI will time out after 1 hour and we might have at least 100 things to test. We will not want to spend too much time on testing SubgraphX alone.

**Review by mufeili — APPROVED** [review]

**Comment by kunmukh** [comment]
@mufeili got it under 20 sec. I changed the parameters to focus less on exploration. 
image

**Comment by mufeili** [comment]
@dgl-bot

**Comment by mufeili** [comment]
@dgl-bot

**Pull request merged**
