### PR TITLE
[Model] Support Multi-GPU for Transformer model

### PR DESCRIPTION
**Pull request by ylfdq1118**
## Description
This PR uses mutli-process to parallelize training of Transformer model. With batch size 128, 4 GPU gives 3.3x speed up. With batch size 4096, 4 GPU give 3.8x speed up.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] Code is well-documented
- [x] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by yzh119** [comment]
`torch.distributed` hangs at initialization if we do not specify the first `gpu_id` as 0.

**Comment by yzh119** [comment]
I have no write access to your repo, so I put the updated version [here](https://github.com/yzh119/dgl/commit/6e40f2996e664cc9f949ed8841dfc2b17180a2b8).
The issue of not converge may result from incorrect schedule settings, I've fixed the problem and now it successfully converges in 4-GPU setting. (But I think in small data like multi30k, shuffle first then divide is a better choice)

**Comment by ylfdq1118** [comment]
@yzh119 just added you as collaborator. Can you move your changes here?

**Comment by ylfdq1118** [comment]
@yzh119 I think I have finished this PR and fixed the synchronization bug. And now the 4 GPU behaves like single GPU.

Can you review again and then we can merge.

**Pull request merged**
