### PR TITLE
[Feature] get_attention parameter in GlobalAttentionPooling

### PR DESCRIPTION
**Pull request by decoherencer**
## Description
@mufeili Added `get_attention` optional parameter to return node attention weights from GlobalAttentionPooling
from the https://discuss.dgl.ai/t/about-globalattentionpooling/2766

## Checklist
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented
- [x] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change

## Changes
- [x] optional parameter addition in forward

### CODE REVIEW

**Review by mufeili — APPROVED** [review]
LGTM. Thanks!

**Comment by mufeili** [comment]
@decoherencer Could you fix these issues caught by CI?

```
python/dgl/nn/pytorch/glob.py:458:0: C0303: Trailing whitespace (trailing-whitespace)
python/dgl/nn/pytorch/glob.py:1268:0: C0304: Final newline missing (missing-final-newline)
```

You need to remove the extra empty spaces at the end of L458 and add a new empty line after L1268.

**Comment by decoherencer** [comment]
Sorry. I got into this [weird state](https://stackoverflow.com/q/70596518) with my pip, which I only noticed now. 
I tried with lint packages locally now. Thanks.

**Comment by mufeili** [comment]
> Sorry. I got into this [weird state](https://stackoverflow.com/q/70596518) with my pip, which I only noticed now. I tried with lint packages locally now. Thanks. And instead of noticing the line number in CI issues for trailing whitespace, I removed the final newline in the last commit 😅

No worries. There is something wrong with the CI. If you don't mind, I can directly modify your code when CI is back.

**Comment by decoherencer** [comment]
> If you don't mind, I can directly modify your code when CI is back. Thanks.
Sure. I pushed lint fix, it seems to have passed in last CI lint checks, you can modify any other errors

**Comment by mufeili** [comment]
@decoherencer Thanks for your patience. The PR has been merged.

**Comment by decoherencer** [comment]
nice. Looking forward to help more

**Comment by mufeili** [comment]
Thanks. That will be great!

**Pull request merged**
