### PR TITLE
[Dist] Add argument in dispatch_data.py to allow user-defined metadata JSON filename.

### PR DESCRIPTION
**Pull request by thvasilo**
## Description
Adds an argument to allow custom-named metadata JSON files for `dispatch_data.py`. We provide the previous value as a default to ensure backwards compatibility.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [x] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [x] Code is well-documented
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by thvasilo** [comment]
Ping @Rhett-Ying for review.

**Comment by Rhett-Ying** [comment]
@dgl-bot

**Review by Rhett-Ying — APPROVED** [review]

**Comment by thvasilo** [comment]
Any idea why the CI is failing @Rhett-Ying ? I couldn't spot an obvious error, but the script returned a non-zero code so it might be hidden in the printouts. 

May I suggest that we reduce the logging in the tests as well? There's almost 300k lines of printouts to sort through, this makes it very hard to spot test failures.

**Comment by thvasilo** [comment]
I can see this in the logs but the test still passes?

```
[293bd1551cb8 INFO 2023-03-10 01:13:30,306 PID:5372] loading node to partition-ids from files... 
Traceback (most recent call last):
  File "tools/verify_partitions.py", line 246, in &lt;module&gt;
    _validate_results(params)
  File "tools/verify_partitions.py", line 187, in _validate_results
    node_partids = get_node_partids(params.partitions_dir, graph_schema)
  File "/root/jenkins/workspace/dgl_PR-5445@4/tools/verification_utils.py", line 207, in get_node_partids
    graph_schema[constants.STR_NODE_TYPE_COUNTS],
AttributeError: module 'constants' has no attribute 'STR_NODE_TYPE_COUNTS'
```

**Comment by frozenbugs** [comment]
@dgl-bot

**Comment by thvasilo** [comment]
I think this should be good to merge right @Rhett-Ying ? A bit of concern for intermittently failing distributed CI tests, should look to harden those.

**Pull request merged**
