### PR TITLE
Improving the Capsule Network example.

### PR DESCRIPTION
**Pull request by drivanov**
## Description

By using `dgl.graph()` instead of the previously used `dgl.DGLGraph()` we not only remove the warning:
```
/usr/local/lib/python3.10/dist-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
```

but we also make the Capsule Network example approximately 10.7% faster". 

Here is the execution time for 5 epochs:

```
          Before:           After:     
real    16m 42.777s      14m 55.046s
user    17m 37.111s      15m 49.642s
```

Changes to `python/dgl/convert.py` make it easier to remove similar warnings for other examples.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [x] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [x] All changes have test coverage
- [x] Code is well-documented
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by frozenbugs** [comment]
@dgl-bot

**Comment by frozenbugs** [comment]
@dgl-bot

**Comment by jermainewang** [comment]
Hi @drivanov , thanks for the contribution. I like your fix to remove those warnings. My suggestion is to keep the changes to the capsule network example and try to avoid modifying the core library code such as `convert.py`. Could you help update the PR as follows:
* Revert the changes to `convert.py`.
* Refactor the `init_graph` function to first generate an edge list (e.g., two integer list `u` and `v`) and then pass them to `dgl.graph` call. This is the intended way of constructing a graph in DGL right now.

Thanks!

**Comment by drivanov** [comment]
Hi @jermainewang, In fact, both integer lists **u** and **v** that you talked about in this example must be empty. So the simplest solution to this problem would be to replace the call
```
g = dgl.DGLGraph()
```
in `init_graph` by one of the following calls
```
g = dgl.graph(data=([], []), num_nodes=0)
g = dgl.graph(data=([], []))
g = dgl.graph(data=[])
g = dgl.graph([])
```

Unfortunately, it's not possible to just use
```
g = dgl.graph()
```
because `dgl.graph(...)` requires positional argument `data`.
The changes I made to  `convert.py` remove this limitation and make it easier to remove similar warnings for other examples. As I could see, the `dgl.DGLGraph()` call is used in 49 different places and I think it would be easier to replace
```
g = dgl.DGLGraph()
```
by 
```
g = dgl.graph()
```
in these places.

**Comment by jermainewang** [comment]
@drivanov What I mean is to change the `init_graph` function to something like follows:
```python
def init_graph(in_nodes, out_nodes, f_size, device="cpu"):
    src, dst = [], []
    in_indx = list(range(in_nodes))
    out_indx = list(range(in_nodes, in_nodes + out_nodes))
    # add edges use edge broadcasting
    for u in in_indx:
        src += [u] * len(out_indx)
        dst += out_indx
    ...   # other logics
    g = dgl.graph((src,dst))  # dgl.graph once;
    ...   # other logics
```

Basically, replace all `add_nodes` and `add_edges` with logics for manipulating the src and dst list directly.

**Comment by drivanov** [comment]
@jermainewang: As you previously suggested, I 
- reverted my changes to `convert.py`
- refactored the `init_graph` function.

With these changes, I see a 7x (700%) runtime improvement, and with my initial changes, I only saw a 1.1x (10%) runtime improvement.

**Comment by frozenbugs** [comment]
@dgl-bot

**Comment by jermainewang** [comment]
@drivanov Nice work! Thanks for the contribution!

**Review by jermainewang — APPROVED** [review]

**Pull request merged**
