### PR TITLE
[Dataset] Change the Data Type of the Node Features in GINDataset/TUDataset from Float64 to Float32

### PR DESCRIPTION
**Pull request by mufeili**
## Description
As reported in [this thread](https://discuss.dgl.ai/t/data-type-of-node-features-of-gindataset-is-th-float64-instead-of-float32/1718) by @hengruizhang98 , the node feature `attr` of the graphs in `GINDataset` has a data type of float64 rather than float32. This PR addresses the issue in instantiating the datasets. 

@BarclayII @jermainewang This is not a critical issue and we may merge it after we are done with 0.6 release.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [x] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [x] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Review by VoVAllen — APPROVED** [review]

**Comment by hetong007** [comment]
Should we apply this as a standard practice to other graph classification datasets (e.g. TU)? 

Currently in the example, we have lines converting the dtype:

https://github.com/dmlc/dgl/blob/master/examples/pytorch/gin/main.py#L25-L26
https://github.com/dmlc/dgl/blob/master/examples/pytorch/sagpool/main.py#L85-L86
https://github.com/dmlc/dgl/blob/master/examples/pytorch/hgp_sl/main.py#L93-L94

**Comment by mufeili** [comment]
> Should we apply this as a standard practice to other graph classification datasets (e.g. TU)?
> 
> Currently in the example, we have lines converting the dtype:
> 
> https://github.com/dmlc/dgl/blob/master/examples/pytorch/gin/main.py#L25-L26
> https://github.com/dmlc/dgl/blob/master/examples/pytorch/sagpool/main.py#L85-L86
> https://github.com/dmlc/dgl/blob/master/examples/pytorch/hgp_sl/main.py#L93-L94

Good point. Updated.

**Comment by hetong007** [comment]
Sorry I just found these two files have the same lines, could you please clean them up together?

https://github.com/dmlc/dgl/blob/master/examples/pytorch/gxn/main.py
https://github.com/dmlc/dgl/blob/master/examples/pytorch/gxn/main_early_stop.py

Otherwise LGTM, thanks!

**Comment by mufeili** [comment]
> Sorry I just found these two files have the same lines, could you please clean them up together?
> 
> https://github.com/dmlc/dgl/blob/master/examples/pytorch/gxn/main.py
> https://github.com/dmlc/dgl/blob/master/examples/pytorch/gxn/main_early_stop.py
> 
> Otherwise LGTM, thanks!

Done.

**Review by hetong007 — APPROVED** [review]

**Pull request merged**
