### PR TITLE
[Misc] Simplify the data path's assignment in python utils

### PR DESCRIPTION
**Pull request by songqing**
## Description

1 The assignment of data path name of different datasets are duplicated, and it may be easy to misspelled and may be missed somewhere when changing it.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [.] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [.] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [.] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [.] All changes have test coverage
- [.] Code is well-documented
- [.] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by songqing** [comment]
@BarclayII Could you help to review this PR?

**Comment by frozenbugs** [comment]
@dgl-bot

**Comment by frozenbugs** [comment]
Thanks for the fixing, can you break 2 unrelated changes to 2 PRs?

For extract_archive, instead of changing the default value to True, what about change the documentation to False since our customer may already have code that works without setting the overwrite, we don't want to accidentally break them.

**Comment by songqing** [comment]
> Thanks for the fixing, can you break 2 unrelated changes to 2 PRs?
> 
> For extract_archive, instead of changing the default value to True, what about change the documentation to False since our customer may already have code that works without setting the overwrite, we don't want to accidentally break them.

OK, I have removed the change of extract_archive().

**Comment by frozenbugs** [comment]
@dgl-bot

**Review by frozenbugs — APPROVED** [review]

**Comment by songqing** [comment]
CI failed, but it seems that the fail has nothing to do with my PR, as the UT test_gat with GPU succeed, but the UT failed with  CPU. And the UT passed in my local environment.

**Comment by frozenbugs** [comment]
@dgl-bot

**Pull request merged**
