### PR TITLE
[GraphBolt][CUDA] Use deque instead of Queue for Bufferer.

### PR DESCRIPTION
**Pull request by mfbalin**
## Description
`deque` is a much more efficient container than `Queue`.
https://stackoverflow.com/a/20330499

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [ ] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Review by frozenbugs — APPROVED** [review]

**Comment by Rhett-Ying** [comment]
do you profile with python 37+ as the link you pasted is almost 10 years ago and it's python 2.7?

**Comment by mfbalin** [comment]
> do you profile with python 37+ as the link you pasted is almost 10 years ago and it's python 2.7?

https://colab.research.google.com/drive/1-__8Ud09DiXcnjBstBZGuLR-OOMIBBun?usp=sharing

Runtimes below:
```
deque 0.04945635795593262
Queue 0.6552836894989014
```

**Comment by Rhett-Ying** [comment]
any detailed reason for such difference? is `queue` implemented based on `deque`?

**Comment by mfbalin** [comment]
See the end of the page: https://docs.python.org/3/library/queue.html

image

**Pull request merged**
