### PR TITLE
[Contrib][Sampling] Temporal neighbor sampling

### PR DESCRIPTION
**Pull request by jermainewang**
## Description

The PR adds a new API `temporal_sample_neighbors` under `dgl.contrib.sampling`.

cc @frozenbugs 

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [x] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [x] All changes have test coverage
- [x] Code is well-documented
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [x] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by jermainewang** [comment]
> HGT proposes that during sampling, as soon as a neighbor without timestamp is accessed from a seed node, we assign the seed node's timestamp to it (Alg. 2, Line 6 in https://arxiv.org/pdf/2003.01332.pdf).

This is the same to including them during sampling. Should be a easy patch.

> Another possible option is not to require the neighbors on each layer has timestamps earlier than the nodes on the next layer, but instead just require all the sampled nodes with a timestamp in all the layers is no later than the seed nodes at the last layer.

I will suggest to create a new sampling operator so we keep both options open for experiments. Also, what if there are multiple seed nodes? Does this require the sampled nodes to have timestamp smaller than *any* of the seed nodes? or depending on their connectivity?

**Comment by BarclayII** [comment]
> what if there are multiple seed nodes?

In this case, a seed node should have its own computation graph.

**Comment by jermainewang** [comment]
> 

I see. That will be a more fundamental change to the existing pipeline.

**Comment by BarclayII** [comment]
> > HGT proposes that during sampling, as soon as a neighbor without timestamp is accessed from a seed node, we assign the seed node's timestamp to it (Alg. 2, Line 6 in https://arxiv.org/pdf/2003.01332.pdf).
> 
> This is the same to including them during sampling. Should be a easy patch.

Do you want to include this patch in this PR or open up a separate PR?

**Comment by jermainewang** [comment]
Let's suspend this PR until we are crystal clear about the request.

**Comment by mfbalin** [comment]
@jermainewang Does the temporal sampling functionality cover what is implemented here?

**Pull request closed without merging**
