### PR TITLE
[Bugfix] Cython CAPI holding GIL causes deadlock when Python callback is asynchronous

### PR DESCRIPTION
**Pull request by jermainewang**
## Description

Cython will not release GIL (global interpreter lock) when calling into C++ APIs. A deadlock will happen when a thread A calls a C++ API that is waiting for a callback back to Python in thread B. Because thread B tries to grab GIL in order to finish the callback but is held by thread A, a deadlock happens. The bug has been in DGL since the beginning of the project but is recently triggered in a corner case in distributed training.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented
- [x] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [x] Related issue is referred in this PR

### CODE REVIEW

**Comment by BarclayII** [comment]
Should we also make other Cython functions `nogil`?

**Comment by jermainewang** [comment]
> Should we also make other Cython functions `nogil`?

No. Only APIs that could be blocking need to release GIL.

**Comment by VoVAllen** [comment]
Where did dgl use a python callback in C++?

**Comment by VoVAllen** [comment]
This is also consistent we've seen that ctypes works well because ctypes function call will release the GIL automatically

**Comment by jermainewang** [comment]
There are some reference counting problem when using NDArray argument in python callback. It is not related to the GIL issue so I disabled the unit test for now. Will fix it in another PR.

**Comment by jermainewang** [comment]
@dgl-bot run g4dn.4xlarge model_speed dmlc/0.8.x

**Review by Rhett-Ying — APPROVED** [review]

**Pull request merged**
