### PR TITLE
[CI] fix device configure when run on GPU

### PR DESCRIPTION
**Pull request by Rhett-Ying**
## Description

some benchmark tests are not really run on GPU, let's fix them.
## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [ ] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by Rhett-Ying** [comment]
@dgl-bot run g4dn.12xlarge api.bench_.*(subgraph|sample_) dmlc/0.9.x

**Comment by Rhett-Ying** [comment]
@dgl-bot run g4dn.12xlarge api.bench_.*subgraph dmlc/0.9.x

**Comment by Rhett-Ying** [comment]
@dgl-bot run g4dn.12xlarge api dmlc/0.9.x

**Comment by Rhett-Ying** [comment]
Results of `api.bench_sample_neighbors` looks good to me (<10%). details [here](https://github.com/dmlc/dgl/pull/5154#issuecomment-1379775899).

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/ruying/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/ruying/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



30 | api.bench_sample_neighbors.track_time | 'reddit', 'csc', 5000, 5 | s | 7% | 0.00030442 | g4dn.12xlarge-gpu | 0.00032431
-- | -- | -- | -- | -- | -- | -- | --
31 | api.bench_sample_neighbors.track_time | 'reddit', 'csc', 5000, 20 | s | 4% | 0.00031438 | g4dn.12xlarge-gpu | 0.0003277
33 | api.bench_sample_neighbors.track_time | 'reddit', 'csc', 20000, 5 | s | 3% | 0.00031334 | g4dn.12xlarge-gpu | 0.00032414
16 | api.bench_sample_neighbors.track_time | 'ogbn-arxiv', 'csc', 20000, 20 | s | 3% | 0.00030529 | g4dn.12xlarge-gpu | 0.00031293
29 | api.bench_sample_neighbors.track_time | 'reddit', 'csc', 200, 40 | s | 2% | 0.00030579 | g4dn.12xlarge-gpu | 0.00031235
9 | api.bench_sample_neighbors.track_time | 'ogbn-arxiv', 'csc', 200, 5 | s | 2% | 0.00029693 | g4dn.12xlarge-gpu | 0.00030319
28 | api.bench_sample_neighbors.track_time | 'reddit', 'csc', 200, 20 | s | 2% | 0.00030589 | g4dn.12xlarge-gpu | 0.00031205
11 | api.bench_sample_neighbors.track_time | 'ogbn-arxiv', 'csc', 200, 40 | s | 2% | 0.00030181 | g4dn.12xlarge-gpu | 0.00030753
32 | api.bench_sample_neighbors.track_time | 'reddit', 'csc', 5000, 40 | s | 2% | 0.00030948 | g4dn.12xlarge-gpu | 0.00031519
17 | api.bench_sample_neighbors.track_time | 'ogbn-arxiv', 'csc', 20000, 40 | s | 2% | 0.00030442 | g4dn.12xlarge-gpu | 0.00030921
27 | api.bench_sample_neighbors.track_time | 'reddit', 'csc', 200, 5 | s | 1% | 0.00030986 | g4dn.12xlarge-gpu | 0.00031426
35 | api.bench_sample_neighbors.track_time | 'reddit', 'csc', 20000, 40 | s | 1% | 0.00041427 | g4dn.12xlarge-gpu | 0.00041991
14 | api.bench_sample_neighbors.track_time | 'ogbn-arxiv', 'csc', 5000, 40 | s | 1% | 0.00030593 | g4dn.12xlarge-gpu | 0.00030911
13 | api.bench_sample_neighbors.track_time | 'ogbn-arxiv', 'csc', 5000, 20 | s | 1% | 0.0003009 | g4dn.12xlarge-gpu | 0.00030402
10 | api.bench_sample_neighbors.track_time | 'ogbn-arxiv', 'csc', 200, 20 | s | 0% | 0.0002953 | g4dn.12xlarge-gpu | 0.00029643
15 | api.bench_sample_neighbors.track_time | 'ogbn-arxiv', 'csc', 20000, 5 | s | 0% | 0.00030474 | g4dn.12xlarge-gpu | 0.00030454
12 | api.bench_sample_neighbors.track_time | 'ogbn-arxiv', 'csc', 5000, 5 | s | -2% | 0.00030684 | g4dn.12xlarge-gpu | 0.00030142
34 | api.bench_sample_neighbors.track_time | 'reddit', 'csc', 20000, 20 | s | -4% | 0.000341 | g4dn.12xlarge-gpu | 0.00032733
  | test_name | params | unit |   | number_remotes/dmlc/0.9.x | machine | number_5154



</body>

</html>

**Comment by Rhett-Ying** [comment]
> Finished the Regression test. Result table is at https://dgl-asv-data.s3-us-west-2.amazonaws.com/934868fb80f26f5da056c8edebac6300ccb66255_g4dn12xlarge/results/result.csv. Jenkins job link is https://dgl-jenkins-eksvpc-2136217999.us-west-2.elb.amazonaws.com/job/dgl/job/PR-5154/5/display/redirect.

Results of `api.bench_.*subgraph` look good to me.

**Review by jermainewang — APPROVED** [review]

**Review by frozenbugs — APPROVED** [review]

**Pull request merged**
