### PR TITLE
[Graphbolt][CUDA] Graphbolt UVA benchmark script

### PR DESCRIPTION
**Pull request by mfbalin**
## Description
Started from the script in #6589. Benchmarks the UVAIndexSelect functionality for various different scenarios, and summarizes the total sum of runtimes of runs at the end. Any future PR improving on the UVAIndexSelect should improve the final summarized runtime number when it is run before and after the new PR.

### CODE REVIEW

**Comment by mfbalin** [comment]
@frozenbugs where should the benchmark scripts be stored for Graphbolt?

**Comment by frozenbugs** [comment]
@caojy1998 from our team will help you take care of merging this benchmark.

**Comment by caojy1998** [comment]
> @frozenbugs where should the benchmark scripts be stored for Graphbolt?

Currently, we decide to put this test in the private repo of regression test.

**Comment by caojy1998** [comment]
> @frozenbugs where should the benchmark scripts be stored for Graphbolt?

Does this benchmark test only support on GPU?

**Comment by frozenbugs** [comment]
> Yes, only GPU. Can I get access to the benchmark repo?

You can have access but you can't kick off any run so it might not easy for you to test it. We will find a way to allow outside contributor to contribute to benchmark, at this stage we will help on the migration.

**Comment by caojy1998** [comment]
throughput
throughput result
time
time result

**Comment by mfbalin** [comment]
I will maintain this benchmark here: https://github.com/mfbalin/gnn_dataloading_primitives/tree/main/benchmarks/graphbolt

**Pull request closed without merging**
