### PR TITLE
[Bug] Fixed optimizer definition in gnn_explainer (#3944)

### PR DESCRIPTION
**Pull request by sharique1006**
## Description
Fixed bug #3944 
optimizer needs to be defined only on the mask since the model is fixed.

@mufeili @zhjwy9343

### CODE REVIEW

**Review by mufeili — APPROVED** [review]
LGTM. Thanks.

**Comment by mufeili** [comment]
Have you tried running the updated example code on your machine?

**Comment by sharique1006** [comment]
> Have you tried running the updated example code on your machine?

Yes, you can see an example run here. https://colab.research.google.com/drive/1fj0cDs53vDODESuCFW2AfigrvzcIuIxj?usp=sharing. The explanations generated after making the change are better than earlier. This is evident from the color of important edges.

Why is CI jenkins build being aborted ?

**Comment by mufeili** [comment]
> > Have you tried running the updated example code on your machine?
> 
> Yes, you can see an example run here. https://colab.research.google.com/drive/1fj0cDs53vDODESuCFW2AfigrvzcIuIxj?usp=sharing. The explanations generated after making the change are better than earlier. This is evident from the color of important edges.
> 
> Why is CI jenkins build being aborted ?

Thanks. We will handle the CI part.

**Pull request merged**
