### PR TITLE
[Readability] Auto fix view.py.

### PR DESCRIPTION
**Pull request by frozenbugs**
## Description
Auto fix view.py to conform to the PEP 8 style guide.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by jermainewang** [comment]
What tools are you using?

**Comment by jermainewang** [comment]
BTW, the current setup for max line length is 100 characters, slightly larger than a typical 80-character-line.

https://github.com/dmlc/dgl/blob/ea6195c2536a6951387e22a0baff82ff9ed8bcec/tests/lint/pylintrc#L339-L341

**Comment by frozenbugs** [comment]
> 

What's the reason that we decided to use 100 instead of 80?

**Comment by frozenbugs** [comment]
> What tools are you using?

https://github.com/hhatto/autopep8

**Comment by jermainewang** [comment]
No particular reason. Just a convention we have stick with for a long time.

**Comment by frozenbugs** [comment]
> 

One of the reason that many prefer 80 because they are fan of split view for code review. Our screen has limited width.

**Review by jermainewang — APPROVED** [review]

**Pull request merged**
