### PR TITLE
[Example] RGCN Heterograph Link Prediction Example

### PR DESCRIPTION
**Pull request by classicsong**
## Description
Here we give an example of how to implement RGCN Link Prediction using Heterograph APIs.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR

### CODE REVIEW

**Comment by FlashXT** [comment]
from entity_classify_mb import RelGraphConvHetero, RelGraphEmbed
ImportError: cannot import name 'RelGraphConvHetero'

**Comment by classicsong** [comment]
> ```
> from entity_classify_mb import RelGraphConvHetero, RelGraphEmbed
> ```
> 
> ImportError: cannot import name 'RelGraphConvHetero'

Did you update dgl to 0.4.3?

**Comment by classicsong** [comment]
> ```
> from entity_classify_mb import RelGraphConvHetero, RelGraphEmbed
> ```
> 
> ImportError: cannot import name 'RelGraphConvHetero'

I have updated the PR, now it can work with RelGraphConvHetero. But as it is WIP, some part may broken right now. (I am still tuning the fullgraph_eval)

**Comment by BarclayII** [comment]
Are you still working on it?  Is it ready for review?

**Pull request closed without merging**
