### PR TITLE
Upgrade libxsmm

### PR DESCRIPTION
**Pull request by anko-intel**
## Description

Upgrade libxsmm to a newer version  ([80090603e](https://github.com/libxsmm/libxsmm/commit/80090603e43f6ddc870cc42e1403dd0af07744cc)).
As far as I have checked, this will not result in performance improvements or regressions, but it is the first step to improve spmm in the near future.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [ ] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Review by itaraban — APPROVED** [review]

**Comment by frozenbugs** [comment]
@Rhett-Ying do we have any existing regression test related to libxsmm that can be kicked off for this PR?

**Review by frozenbugs — APPROVED** [review]

**Comment by anko-intel** [comment]
model_speed benchmark results comparison - measured on r6i.16xlarge:

measurement: | before 1 | before 2 | before 3 | after 1 | after 2 | after 3 | average | norm     before 1 | norm     before 2 | norm     before 3 | norm     after  1 | norm     after 2 | norm     after 3
-- | --:| --:| --:| --:| --:| --:| --:| --:| --:| --:| --:| --:| --:
bench_gat |   |   |   |   |   |   |   |   |   |   |   |   |  
cora | 0.01024 | 0.00998 | 0.01018 | 0.01030 | 0.01025 | 0.01065 | 0.01027 | 1.00 | 0.97 | 0.99 | 1.00 | 1.00 | 1.04
pubmed | 0.02502 | 0.02481 | 0.02481 | 0.02551 | 0.02522 | 0.02544 | 0.02513 | 1.00 | 0.99 | 0.99 | 1.01 | 1.00 | 1.01
  |   |   |   |   |   |   |   |   |   |   |   |   |  
bench_gat_ns |   |   |   |   |   |   |   |   |   |   |   |   |  
reddit | 0.18059 | 0.19042 | 0.18632 | 0.18783 | 0.18489 | 0.18476 | 0.18580 | 0.97 | 1.02 | 1.00 | 1.01 | 1.00 | 0.99
ogbn-products | 0.14602 | 0.15572 | 0.15408 | 0.14738 | 0.15401 | 0.15504 | 0.15204 | 0.96 | 1.02 | 1.01 | 0.97 | 1.01 | 1.02
  |   |   |   |   |   |   |   |   |   |   |   |   |  
bench_gcn_udf |   |   |   |   |   |   |   |   |   |   |   |   |  
cora | 0.07316 | 0.07355 | 0.07409 | 0.07673 | 0.07742 | 0.07453 | 0.07491 | 0.98 | 0.98 | 0.99 | 1.02 | 1.03 | 0.99
pubmed | 0.29299 | 0.29790 | 0.29712 | 0.30024 | 0.30462 | 0.29558 | 0.29808 | 0.98 | 1.00 | 1.00 | 1.01 | 1.02 | 0.99
  |   |   |   |   |   |   |   |   |   |   |   |   |  
bench_rgcn_base |   |   |   |   |   |   |   |   |   |   |   |   |  
aifb | 0.04329 | 0.04359 | 0.04246 | 0.04370 | 0.04420 | 0.04396 | 0.04353 | 0.99 | 1.00 | 0.98 | 1.00 | 1.02 | 1.01
am | 10.37056 | 10.09430 | 10.08628 | 10.22588 | 10.18912 | 10.11450 | 10.18011 | 1.02 | 0.99 | 0.99 | 1.00 | 1.00 | 0.99
  |   |   |   |   |   |   |   |   |   |   |   |   |  
bench_rgcn_hetero_ns |   |   |   |   |   |   |   |   |   |   |   |   |  
ogbn-mag | 0.05138 | 0.05330 | 0.05449 | 0.05622 | 0.05399 | 0.05393 | 0.05388 | 0.95 | 0.99 | 1.01 | 1.04 | 1.00 | 1.00
  |   |   |   |   |   |   |   |   |   |   |   |   |  
bench_rgcn_homogeneous_ns |   |   |   |   |   |   |   |   |   |   |   |   |  
am | 0.04285 | 0.04330 | 0.04761 | 0.05277 | 0.04385 | 0.04528 | 0.04594 | 0.93 | 0.94 | 1.04 | 1.15 | 0.95 | 0.99
ogbn-mag | 0.25833 | 0.25994 | 0.26225 | 0.27063 | 0.27175 | 0.26653 | 0.26490 | 0.98 | 0.98 | 0.99 | 1.02 | 1.03 | 1.01
  |   |   |   |   |   |   |   |   |   |   |   |   |  
bench_sage |   |   |   |   |   |   |   |   |   |   |   |   |  
cora | 0.00587 | 0.00580 | 0.00590 | 0.00544 | 0.00617 | 0.00610 | 0.00588 | 1.00 | 0.99 | 1.00 | 0.93 | 1.05 | 1.04
pubmed | 0.01603 | 0.01557 | 0.01539 | 0.01587 | 0.01563 | 0.01558 | 0.01568 | 1.02 | 0.99 | 0.98 | 1.01 | 1.00 | 0.99
  |   |   |   |   |   |   |   |   |   |   |   |   |  
bench_sage_ns |   |   |   |   |   |   |   |   |   |   |   |   |  
reddit | 0.06692 | 0.06176 | 0.06148 | 0.06193 | 0.06195 | 0.06421 | 0.06304 | 1.06 | 0.98 | 0.98 | 0.98 | 0.98 | 1.02
ogbn-products | 0.04192 | 0.04435 | 0.03661 | 0.04042 | 0.03592 | 0.04288 | 0.04035 | 1.04 | 1.10 | 0.91 | 1.00 | 0.89 | 1.06
  |   |   |   |   |   |   |   |   |   |   |   |   |  
bench_sage_unsupervised_ns |   |   |   |   |   |   |   |   |   |   |   |   |  
data num_negs batch_size |   |   |   |   |   |   |   |   |   |   |   |   |  
reddit 2 1024 | 0.11821 | 0.11685 | 0.11432 | 0.12712 | 0.13065 | 0.12333 | 0.12175 | 0.97 | 0.96 | 0.94 | 1.04 | 1.07 | 1.01
reddit 2 2048 | 0.18127 | 0.18031 | 0.16444 | 0.17690 | 0.18323 | 0.15626 | 0.17373 | 1.04 | 1.04 | 0.95 | 1.02 | 1.05 | 0.90
reddit 2 8192 | 0.30967 | 0.33396 | 0.32851 | 0.31851 | 0.31305 | 0.32724 | 0.32182 | 0.96 | 1.04 | 1.02 | 0.99 | 0.97 | 1.02
reddit 8 1024 | 0.13431 | 0.13038 | 0.12919 | 0.12307 | 0.13011 | 0.11825 | 0.12755 | 1.05 | 1.02 | 1.01 | 0.96 | 1.02 | 0.93
reddit 8 2048 | 0.18101 | 0.18233 | 0.18684 | 0.17120 | 0.18257 | 0.16623 | 0.17836 | 1.01 | 1.02 | 1.05 | 0.96 | 1.02 | 0.93
reddit 8 8192 | 0.32082 | 0.30227 | 0.34359 | 0.33585 | 0.30942 | 0.33261 | 0.32409 | 0.99 | 0.93 | 1.06 | 1.04 | 0.95 | 1.03
reddit 32 1024 | 0.12201 | 0.10646 | 0.12281 | 0.11819 | 0.11648 | 0.12170 | 0.11794 | 1.03 | 0.90 | 1.04 | 1.00 | 0.99 | 1.03
reddit 32 2048 | 0.18263 | 0.17405 | 0.17880 | 0.17810 | 0.17057 | 0.17413 | 0.17638 | 1.04 | 0.99 | 1.01 | 1.01 | 0.97 | 0.99
reddit 32 8192 | 0.30220 | 0.30273 | 0.31293 | 0.30121 | 0.32689 | 0.34095 | 0.31449 | 0.96 | 0.96 | 1.00 | 0.96 | 1.04 | 1.08

**Comment by Rhett-Ying** [comment]
@anko-intel  Thanks for your detailed benchmark. so you run the benchmark tests(`//benchmarks/bencmarks/model_speed/`) manually 3 times for `before` and `after`? what does the `norm` mean?

**Comment by Rhett-Ying** [comment]
@dgl-bot run r6i.16xlarge kernel dmlc/master

**Comment by Rhett-Ying** [comment]
@dgl-bot run r6i.16xlarge kernel dmlc/master

**Comment by anko-intel** [comment]
> @anko-intel Thanks for your detailed benchmark. so you run the benchmark tests(`//benchmarks/bencmarks/model_speed/`) manually 3 times for `before` and `after`? what does the `norm` mean?

Exactly, "norm" is the normalized against the average of all measurements, so 
"norm before 1" =  6 * "before 1" / ("before 1" + "before 2" + "before 3" + "after 1" + "after 2" + "after 3")

**Comment by anko-intel** [comment]
@Rhett-Ying , you can see below my results for kernel (left  side "before" and right side "after"). There are some differences but when comparing two runs for the same dgl version measurement noise seems to be similar. Maybe you have some advice on how to achieve more stable results.

· Running '/home/ubuntu/miniconda3/envs/dgl/bin/python -c import sys; print(str(sys.version_info[0]) + "." + str(sys.version_info[1]))' | = | · Running '/home/ubuntu/miniconda3/envs/dgl/bin/python -c import sys; print(str(sys.version_info[0]) + "." + str(sys.version_info[1]))'
-- | -- | --
OUTPUT --------> |   | OUTPUT -------->
3.11 |   | 3.11
· Discovering benchmarks |   | · Discovering benchmarks
·· Running '/home/ubuntu/miniconda3/envs/dgl/lib/python3.11/site-packages/asv/benchmark.py discover /home/ubuntu/dgl/benchmarks/benchmarks /tmp/tmpafl9_0yp/result.json' in existing-py_home_ubuntu_miniconda3_envs_dgl_bin_python | <> | ·· Running '/home/ubuntu/miniconda3/envs/dgl/lib/python3.11/site-packages/asv/benchmark.py discover /home/ubuntu/dgl/benchmarks/benchmarks /tmp/tmp4q2u3ppn/result.json' in existing-py_home_ubuntu_miniconda3_envs_dgl_bin_python
·· Running '/home/ubuntu/miniconda3/envs/dgl/bin/python /home/ubuntu/miniconda3/envs/dgl/lib/python3.11/site-packages/asv/benchmark.py discover /home/ubuntu/dgl/benchmarks/benchmarks /tmp/tmpafl9_0yp/result.json' |   | ·· Running '/home/ubuntu/miniconda3/envs/dgl/bin/python /home/ubuntu/miniconda3/envs/dgl/lib/python3.11/site-packages/asv/benchmark.py discover /home/ubuntu/dgl/benchmarks/benchmarks /tmp/tmp4q2u3ppn/result.json'
OUTPUT --------> | = | OUTPUT -------->
WARNING:root:No regression test conf file specified |   | WARNING:root:No regression test conf file specified
Skip track_time |   | Skip track_time
Skip track_time |   | Skip track_time
· Running 4 total benchmarks (1 commits * 1 environments * 4 benchmarks) |   | · Running 4 total benchmarks (1 commits * 1 environments * 4 benchmarks)
[  0.00%] ·· Benchmarking existing-py_home_ubuntu_miniconda3_envs_dgl_bin_python |   | [  0.00%] ·· Benchmarking existing-py_home_ubuntu_miniconda3_envs_dgl_bin_python
[  0.00%] ··· Running '/home/ubuntu/miniconda3/envs/dgl/lib/python3.11/site-packages/asv/benchmark.py run_server /home/ubuntu/dgl/benchmarks/benchmarks /tmp/asv-forkserver-89h2x5ax/socket' in existing-py_home_ubuntu_miniconda3_envs_dgl_bin_python | <> | [  0.00%] ··· Running '/home/ubuntu/miniconda3/envs/dgl/lib/python3.11/site-packages/asv/benchmark.py run_server /home/ubuntu/dgl/benchmarks/benchmarks /tmp/asv-forkserver-ww_we49w/socket' in existing-py_home_ubuntu_miniconda3_envs_dgl_bin_python
[  0.00%] ··· Running '/home/ubuntu/miniconda3/envs/dgl/bin/python /home/ubuntu/miniconda3/envs/dgl/lib/python3.11/site-packages/asv/benchmark.py run_server /home/ubuntu/dgl/benchmarks/benchmarks /tmp/asv-forkserver-89h2x5ax/socket' |   | [  0.00%] ··· Running '/home/ubuntu/miniconda3/envs/dgl/bin/python /home/ubuntu/miniconda3/envs/dgl/lib/python3.11/site-packages/asv/benchmark.py run_server /home/ubuntu/dgl/benchmarks/benchmarks /tmp/asv-forkserver-ww_we49w/socket'
[  0.00%] ··· Importing benchmark suite produced output: | = | [  0.00%] ··· Importing benchmark suite produced output:
[  0.00%] ···· WARNING:root:No regression test conf file specified |   | [  0.00%] ···· WARNING:root:No regression test conf file specified
Skip track_time |   | Skip track_time
Skip track_time |   | Skip track_time
  |   |  
[ 25.00%] ··· kernel.bench_edgesoftmax.track_time                             ok |   | [ 25.00%] ··· kernel.bench_edgesoftmax.track_time                             ok
[ 25.00%] ··· ============ =========== ======================== |   | [ 25.00%] ··· ============ =========== ========================
graph      num_heads |   | graph      num_heads
------------ ----------- ------------------------ |   | ------------ ----------- ------------------------
ogbn-arxiv       1       0.0011310587500338442 | <> | ogbn-arxiv       1       0.0011382399099238683
ogbn-arxiv       4        0.004254575899976771 |   | ogbn-arxiv       4       0.0031023316900245846
ogbn-arxiv       8        0.00875412162997236 |   | ogbn-arxiv       8        0.008733313990087482
reddit         1        0.11246175466003479 |   | reddit         1        0.11392187857010867
reddit         4         0.446870473040035 |   | reddit         4         0.4465752463199897
reddit         8         0.9219349361099012 |   | reddit         8         0.9194804022800236
cora          1       0.00010186715997406281 |   | cora          1       9.789346004254184e-05
cora          4       0.00011752254999009892 |   | cora          4       0.0001176776499778498
cora          8       0.00013455052001518197 |   | cora          8       0.00013412340995273554
pubmed         1       0.00017928322005900555 |   | pubmed         1       0.00017482308991020545
pubmed         4       0.0002805396598705556 |   | pubmed         4       0.0002886389500054065
pubmed         8       0.00044040321008651515 |   | pubmed         8       0.00044198404997587205
============ =========== ======================== | = | ============ =========== ========================
  |   |  
[ 50.00%] ··· kernel.bench_gsddmm_u_dot_v.track_flops                         ok |   | [ 50.00%] ··· kernel.bench_gsddmm_u_dot_v.track_flops                         ok
[ 50.00%] ··· =============== =========== ======= ======= ======= |   | [ 50.00%] ··· =============== =========== ======= ======= =======
--                                 num_heads |   | --                                 num_heads
--------------------------- ----------------------- |   | --------------------------- -----------------------
graph       feat_size     0       1       4 |   | graph       feat_size     0       1       4
=============== =========== ======= ======= ======= |   | =============== =========== ======= ======= =======
ogbn-arxiv        4       17.99   18.81    6.5 | <> | ogbn-arxiv        4       18.26   18.23    6.64
ogbn-arxiv        32      49.27   48.94   34.04 |   | ogbn-arxiv        32      48.41   32.23   33.56
ogbn-arxiv       256      43.23    43.3    45.8 |   | ogbn-arxiv       256      44.67   44.73   47.44
reddit          4       19.56   19.32    7.05 |   | reddit          4       18.87   18.84    6.99
reddit          32      55.25   56.53   39.46 |   | reddit          32      54.68   54.75    38.3
reddit         256      49.89   49.45   56.17 |   | reddit         256      49.43   49.49    55.4
ogbn-proteins       4       21.81    21.8    7.17 |   | ogbn-proteins       4       21.64   21.79    7.19
ogbn-proteins       32      76.73    75.9   46.39 |   | ogbn-proteins       32      75.47   76.06   46.17
ogbn-proteins      256      60.79   60.57   75.79 |   | ogbn-proteins      256      60.49    60.6    75.5
=============== =========== ======= ======= ======= | = | =============== =========== ======= ======= =======
  |   |  
[ 75.00%] ··· kernel.bench_gspmm_copy_u.track_flops                           ok |   | [ 75.00%] ··· kernel.bench_gspmm_copy_u.track_flops                           ok
[ 75.00%] ··· =============== =========== ======== ======== |   | [ 75.00%] ··· =============== =========== ======== ========
--                               reducer |   | --                               reducer
--------------------------- ----------------- |   | --------------------------- -----------------
graph       feat_size    sum      max |   | graph       feat_size    sum      max
=============== =========== ======== ======== |   | =============== =========== ======== ========
ogbn-arxiv        4        9.77     6.15 | <> | ogbn-arxiv        4       10.28     6.84
ogbn-arxiv        32      35.71     5.23 |   | ogbn-arxiv        32      30.96     4.99
ogbn-arxiv       256      13.58     4.24 |   | ogbn-arxiv       256       13.6     4.31
reddit          4       28.81    22.77 |   | reddit          4       28.67    22.66
reddit          32      122.58   85.87 |   | reddit          32      121.92   82.71
reddit         256      59.64    48.34 |   | reddit         256      59.64    47.86
ogbn-proteins       4       45.85    39.78 |   | ogbn-proteins       4       44.51    38.14
ogbn-proteins       32      160.92   107.14 |   | ogbn-proteins       32      189.27   121.76
ogbn-proteins      256       86.3    68.74 |   | ogbn-proteins      256      95.55     78.0
=============== =========== ======== ======== | = | =============== =========== ======== ========
  |   |  
[100.00%] ··· kernel.bench_gspmm_u_mul_e_sum.track_flops                      ok |   | [100.00%] ··· kernel.bench_gspmm_u_mul_e_sum.track_flops                      ok
[100.00%] ··· =============== =========== ======= ======= ======= |   | [100.00%] ··· =============== =========== ======= ======= =======
--                                 num_heads |   | --                                 num_heads
--------------------------- ----------------------- |   | --------------------------- -----------------------
graph       feat_size     0       1       4 |   | graph       feat_size     0       1       4
=============== =========== ======= ======= ======= |   | =============== =========== ======= ======= =======
ogbn-arxiv        4        9.24    7.96    9.32 | <> | ogbn-arxiv        4       11.21    9.22   10.92
ogbn-arxiv        32      26.38   16.62   13.64 |   | ogbn-arxiv        32      27.66   18.41   14.59
ogbn-arxiv       256      19.86   14.83   14.16 |   | ogbn-arxiv       256       20.2   14.84   14.61
reddit          4       25.59    6.13   25.66 |   | reddit          4       25.57    6.08   25.66
reddit          32      53.87    10.6   10.16 |   | reddit          32      53.61   10.53   10.02
reddit         256      37.23   11.85   11.75 |   | reddit         256      37.31   11.72   11.68
ogbn-proteins       4       14.02    4.73   14.01 |   | ogbn-proteins       4        14.3    4.86   14.32
ogbn-proteins       32      52.76   12.27    9.94 |   | ogbn-proteins       32      52.82   12.34   10.12
ogbn-proteins      256      48.34   18.11   18.06 |   | ogbn-proteins      256      51.27   20.48   19.22
=============== =========== ======= ======= ======= | = | =============== =========== ======= ======= =======

**Comment by Rhett-Ying** [comment]
@dgl-bot run r6i.16xlarge kernel dmlc/master

**Comment by Rhett-Ying** [comment]
@frozenbugs @anko-intel As shown [here](https://github.com/dmlc/dgl/pull/5725#issuecomment-1560370505), performance result looks good to me.

**Review by Rhett-Ying — APPROVED** [review]

**Pull request merged**
