### PR TITLE
Removing warnings appearing in NN tests.

### PR DESCRIPTION
**Pull request by drivanov**
## Description

Removing the following warnings that appear in tests implemented in `test_nn.py`:
```
================================================================================================= warnings summary =================================================================================================
tests/python/pytorch/nn/test_nn.py: 11 warnings
  /usr/local/lib/python3.10/dist-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
    dgl_warning(

  /usr/local/lib/python3.10/dist-packages/dgl/heterograph.py:120: DGLWarning: Keyword arguments ['readonly'] are deprecated in v0.5, and can be safely removed in all cases.
    dgl_warning(

  /usr/local/lib/python3.10/dist-packages/dgl/dataloading/dataloader.py:1076: DGLWarning: Dataloader CPU affinity opt is not enabled, consider switching it on (see enable_cpu_affinity() or CPU best practices for DGL 

tests/python/pytorch/nn/test_nn.py::test_group_rev_res[idtype0]
  /usr/local/lib/python3.10/dist-packages/dgl/nn/pytorch/conv/grouprevres.py:35: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
    inputs[1].storage().resize_(0)

  /usr/local/lib/python3.10/dist-packages/dgl/transforms/module.py:507: DGLWarning: LaplacianPE will be deprecated. Use LapPE please.
    dgl_warning("LaplacianPE will be deprecated. Use LapPE please.")

tests/python/pytorch/nn/test_nn.py: 48 warnings
  /usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:218: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because num_head is odd
    warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")

```

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [x] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [x] All changes have test coverage
- [x] Code is well-documented
- [x] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by frozenbugs** [comment]
@dgl-bot

**Comment by frozenbugs** [comment]
=========================== short test summary info ============================
FAILED tests/python/pytorch/nn/test_nn.py::test_graph_conv0[1] - dgl._ffi.base.DGLError: Cannot assign node feature "h" on device cuda:0 to a graph on device cpu. Call DGLGraph.to() to copy the graph to the same device.
FAILED tests/python/pytorch/nn/test_nn.py::test_graph_conv0[2] - dgl._ffi.base.DGLError: Cannot assign node feature "h" on device cuda:0 to a graph on device cpu. Call DGLGraph.to() to copy the graph to the same device.
FAILED tests/python/pytorch/nn/test_nn.py::test_dense_cheb_conv[1] - TypeError: from_scipy() got an unexpected keyword argument 'readonly'
FAILED tests/python/pytorch/nn/test_nn.py::test_dense_cheb_conv[2] - TypeError: from_scipy() got an unexpected keyword argument 'readonly'
FAILED tests/python/pytorch/nn/test_nn.py::test_hgt[1-4-idtype0] - ValueError: num_workers must be 0 if graph and indices are on CUDA.
FAILED tests/python/pytorch/nn/test_nn.py::test_hgt[1-4-idtype1] - ValueError: num_workers must be 0 if graph and indices are on CUDA.
FAILED tests/python/pytorch/nn/test_nn.py::test_group_rev_res[idtype0] - AttributeError: 'Tensor' object has no attribute 'untyped_storage'
FAILED tests/python/pytorch/nn/test_nn.py::test_group_rev_res[idtype1] - AttributeError: 'Tensor' object has no attribute 'untyped_storage'
==== 8 failed, 4538 passed, 272 skipped, 125 warnings in 250.12s (0:04:10) =====

**Comment by drivanov** [comment]
The ussues mentioned [here](https://github.com/dmlc/dgl/pull/6109#issuecomment-1672443793) are fixed.

**Comment by frozenbugs** [comment]
@dgl-bot

**Review by frozenbugs — APPROVED** [review]

**Pull request merged**
