### PR TITLE
GeniePath model add a Tanh.

### PR DESCRIPTION
**Pull request by yinpeiqi**
## Description

According to the author paper, a tanh function is used after each GAT layer. Which here should consider.
image

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by yzh119** [comment]
@yinpeiqi it would great if you can report the new accuracy after the change.

**Comment by yinpeiqi** [comment]
The result of Pubmed showed no difference from the original one.

The result of PPI: (use Lazy, without residual, all other configs are default) 

In epoch 993, Train F1: 0.9883 | Train Loss: 0.0173; Valid F1: 0.9706 | Valid loss: 0.0928
In epoch 994, Train F1: 0.9884 | Train Loss: 0.0172; Valid F1: 0.9707 | Valid loss: 0.0929
In epoch 995, Train F1: 0.9884 | Train Loss: 0.0172; Valid F1: 0.9706 | Valid loss: 0.0931
In epoch 996, Train F1: 0.9884 | Train Loss: 0.0171; Valid F1: 0.9706 | Valid loss: 0.0933
In epoch 997, Train F1: 0.9884 | Train Loss: 0.0171; Valid F1: 0.9707 | Valid loss: 0.0930
In epoch 998, Train F1: 0.9884 | Train Loss: 0.0172; Valid F1: 0.9705 | Valid loss: 0.0934
In epoch 999, Train F1: 0.9884 | Train Loss: 0.0172; Valid F1: 0.9706 | Valid loss: 0.0928
Test F1: 0.9802 | Test loss: 0.0555

**Comment by yzh119** [comment]
@yinpeiqi thanks, please also update the numbers in README.

**Comment by yinpeiqi** [comment]
@yzh119 Ok, I'll update it after I run GeniePath, GeniePath-lazy, GeniePath-lazy-residual three tests that the author ran for the PPI dataset.

**Comment by yinpeiqi** [comment]
I have updated my result in README. 
Test F1: 0.9729 | Test loss: 0.0692 
Test F1: 0.9802 | Test loss: 0.0555
Test F1: 0.9798 | Test loss: 0.0573

**Review by yzh119 — APPROVED** [review]
LGTM

**Pull request merged**
