### PR TITLE
[Test] Add cpp test to CI

### PR DESCRIPTION
**Pull request by VoVAllen**
## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented
- [x] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR

### CODE REVIEW

**Comment by VoVAllen** [comment]
Also added timeout for mxnet unittest. 
Need help on Windows build. @BarclayII

**Comment by VoVAllen** [comment]
https://github.com/dmlc/dgl/blob/8f378d90adaf51c2773979500fadca428d736882/python/dgl/contrib/graph_store.py#L536
Seems need to change "localhost" to "127.0.0.1". Sometimes python cannot find `localhost`

**Comment by BarclayII** [comment]
It seems that the unit tests requires the `dgl::Graph` class to be exported as a library symbol.  Changing
```c++
class Graph : public GraphInterface {
```
to
```c++
class DGL_DLL Graph : public GraphInterface {
```
can solve the problem.  However I'm not sure if exporting a whole class is a good practice (@jermainewang ).

**Comment by VoVAllen** [comment]
How about `-DWINDOWS_EXPORT_ALL_SYMBOLS=True`?

**Comment by BarclayII** [comment]
That works.

**Comment by VoVAllen** [comment]
Ready to merge.

**Comment by jermainewang** [comment]
Where is `BUILD_CPP_TEST` being set in the CI?

**Comment by VoVAllen** [comment]
at `tests/scripts/task_cpp_unit_test.sh` and `tests/scripts/task_cpp_unit_test.bat`

**Comment by jermainewang** [comment]
@VoVAllen, could you enable this flag during the build phase? It's not a good idea to build it again during the test phase since the build time could be long in the future (w/ custom cuda kernel).

**Comment by VoVAllen** [comment]
Changed to compile only once.

**Pull request merged**
