### PR TITLE
[bugfix] Quick fix of #1547

### PR DESCRIPTION
**Pull request by yzh119**
## Description
Temporary fix of #1547 . Will support non-blocking later(I suppose it's only restricted to PyTorch).

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [ ] Code is well-documented
- [x] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [x] Related issue is referred in this PR

### CODE REVIEW

**Comment by VoVAllen** [comment]
You didn't even past the kwarg to the downside API `F.copy_to` and pytorch's `.to`functions

**Comment by ThierryDeruyttere** [comment]
To fix the issue mentioned by @VoVAllen, please do the following:

update in the file `graphs.py` the lines 3900-3904:

```
for k in self.ndata.keys():
   self.ndata[k] = F.copy_to(self.ndata[k], ctx)
for k in self.edata.keys():
   self.edata[k] = F.copy_to(self.edata[k], ctx)
return self
```

to

```
for k in self.ndata.keys():
   self.ndata[k] = F.copy_to(self.ndata[k], ctx, **kwargs)
for k in self.edata.keys():
   self.edata[k] = F.copy_to(self.edata[k], ctx, **kwargs)
return self
```

In file `python/dgl/backend/mxnet/tensor.py` update lines 118-119 to:
```
def copy_to(input, ctx, **kwargs):
    return input.as_in_context(ctx)
```

In file `python/dgl/backend/pytorch/tensor.py` update lines 90-98 to:
```
def copy_to(input, ctx, **kwargs):
    if ctx.type == 'cpu':
        return input.cpu()
    elif ctx.type == 'cuda':
        if ctx.index is not None:
            th.cuda.set_device(ctx.index)
        return input.cuda(**kwargs)
    else:
        raise RuntimeError('Invalid context', ctx)
```

In file `python/dgl/backend/tensorflow/tensor.py` update lines 132-135 to:
```
def copy_to(input, ctx, **kwargs):
    with tf.device(ctx):
        new_tensor = tf.identity(input)
    return new_tensor
```

In file `python/dgl/backend/numpy/tensor.py` update lines 77-78 to:
```
def copy_to(input, ctx, **kwargs):
    return input
```

**Comment by jermainewang** [comment]
@yzh119 remember to add unittests too.

**Comment by yzh119** [comment]
@ThierryDeruyttere @VoVAllen thanks for your suggestions.
Yes it's a workaround to make it compatible with pytorch-lighting. Have updated accordingly.

**Comment by ThierryDeruyttere** [comment]
@yzh119

Yes, i had the same issue with pytorch-lightning.
Thanks for opening this pull request!

**Pull request merged**
