### PR TITLE
[CUDA] Add CUDA11 support

### PR DESCRIPTION
**Pull request by jermainewang**
## Description

Previously DGL cannot work with CUDA 11.0 due to a bug in the CUB library which was fixed in [11.1](https://github.com/NVIDIA/cub/commit/9143e47e048641aa0e6ddfd645bcd54ff1059939). This adds a workaround to use latest CUB/Thrust library instead of the official one for CUDA <= 11.0. Also fix a compatibility issue with the latest PyTorch 1.8.0 nightly build.

Credits to @nv-dlasalle for figuring out the root problem.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented
- [x] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [x] Related issue is referred in this PR

### CODE REVIEW

**Comment by BarclayII** [comment]
Is the spurious out-of-memory problem in the GCN example code also resolved?

**Comment by jermainewang** [comment]
> Is the spurious out-of-memory problem in the GCN example code also resolved?

yes

**Comment by yzh119** [comment]
@BarclayII is there a link to the OOM issue?

**Review by yzh119 — APPROVED** [review]
LGTM

**Pull request merged**
