### PR TITLE
Reactivation of one of the GPU tests.

### PR DESCRIPTION
**Pull request by drivanov**
## Description

The `test_batch-heterograph.py::test_batch_netypes` has no problems anymore and is ready to be reactivated. I tried running this test on 5 different machines with different GPU cards.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [x] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ]

### CODE REVIEW

**Comment by frozenbugs** [comment]
@dgl-bot

**Comment by frozenbugs** [comment]
@dgl-bot

**Comment by frozenbugs** [comment]
@dgl-bot

**Comment by Rhett-Ying** [comment]
@dgl-bot

**Pull request merged**
