### PR TITLE
[Feature] Allow batching readonly graphs

### PR DESCRIPTION
**Pull request by mufeili**
## Description
See #502.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented
- [x] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [x] Related issue is referred in this PR

### CODE REVIEW

**Comment by zheng-da** [comment]
can we make the batched graph use CSR format? It's readonly. It should be more efficient to use CSR format.

**Comment by mufeili** [comment]
@zheng-da I assume you mean for the graph index part we can first retrieve the topology of graphs in csr format, merge them to get a csr format batched graph topology and create a graph index from it?

**Comment by jermainewang** [comment]
I agree with @zheng-da. Perhaps a better way to solve it is changing the `DisjointUnion` function to return a CSR-based `ImmutableGraph`.

**Comment by mufeili** [comment]
Close this PR as @VoVAllen is working on a more efficient implementation.

**Pull request closed without merging**
