### PR TITLE
[NN] Update gatv2conv.py doc string 

### PR DESCRIPTION
**Pull request by shakedbr**
## Description
Small update in gatv2conv.py docstring

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] Code is well-documented
- [x] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change

### CODE REVIEW

**Review by mufeili — APPROVED** [review]
LGTM

**Comment by shakedbr** [comment]
@mufeili 
 It can't be rendered successfully ([https://docs.dgl.ai/en/latest/api/python/nn.pytorch.html#gatv2conv](https://docs.dgl.ai/en/latest/api/python/nn.pytorch.html#gatv2conv)).

I suspect it's because of ` \vec{a}^T^{(l)}` (dobule superscript)
We can fix that by changing to ` \vec{a}^{T(l)}`

What do you think?

**Comment by mufeili** [comment]
@shakedbr 

Let me try building the doc locally and see if the fix works.

**Comment by mufeili** [comment]
The issue is fixed in #3491 .

**Pull request merged**
