### PR TITLE
[Example] NGCF

### PR DESCRIPTION
**Pull request by KounianhuaDu**
## Description
This is the implementation of Neural Graph Collaborative Filtering.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by KounianhuaDu** [comment]
This is the new pr for NGCF. @zhjwy9343

**Comment by KounianhuaDu** [comment]
I compute the norm and store them before the NGCFLayer to avoid repeated computation. This will save about 100s for a training epoch (380s->280s) when the batch size is 1024. The instance is a g4dn16x.

**Comment by KounianhuaDu** [comment]
The author implementation uses the matrix form model. So it maybe more efficient.

**Comment by KounianhuaDu** [comment]
The data is uploaded to s3. Run the sh file in the Data folder will get the data.

**Review by yzh119 — APPROVED** [review]
LGTM. @KounianhuaDu thanks for your contribution!

**Pull request merged**
