### PR TITLE
[Bug fix] Fix concurrency bug reported at issue#755

### PR DESCRIPTION
**Pull request by classicsong**
## Description
Fix concurrency bug of test_shared_mem_store.py reported at #755. 
Also make test_shared_mem_store.py more deterministic by:
1. use sync flags instead of time.sleep(n) for server start.
2. use conditional variable instead of time.sleep(n) for test_copy_shared_mem

**How bug occurs?**
Please refer to https://github.com/dmlc/dgl/issues/755#issuecomment-526917724 for how the problem occurs.

**Solution**
The solution is to add a _sync_barrier(60) at L71 to force current threads to sync before executing following test codes.

#755 
@zheng-da @aksnzhy 

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented
- [x] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [x] Related issue is referred in this PR

### CODE REVIEW

**Comment by yzh119** [comment]
Could you please explain how the problem occurs and how do you solve it?

**Comment by classicsong** [comment]
> Could you please explain how the problem occurs and how do you solve it?

**Comment by futurely** [comment]
Only the tests have bug or the shared memory store also has bug?

https://github.com/dmlc/dgl/pull/521

**Comment by BarclayII** [comment]
What is the status of this PR?

**Comment by classicsong** [comment]
> What is the status of this PR?

The PR need some one to review.

**Comment by zheng-da** [comment]
let me review this. I always wanted to follow up but didn't get time.

**Pull request merged**
