### PR TITLE
[Misc] Remove blank files.

### PR DESCRIPTION
**Pull request by frozenbugs**
## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [ ] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by frozenbugs** [comment]
@BarclayII please check whether dglgo/dglgo/utils/optimizer_config.py is safe to remove.

**Review by Rhett-Ying — APPROVED** [review]

**Comment by Rhett-Ying** [comment]
`DGLGO` is out of maintain? DGLGO CI has already been disabled.

**Comment by frozenbugs** [comment]
> `DGLGO` is out of maintain? DGLGO CI has already been disabled.

Yes, I just noticed the empty file, if it is safe to remove, I will remove it in the PR.

**Comment by frozenbugs** [comment]
> Commit ID: [375c315](https://github.com/dmlc/dgl/commit/375c31521c5ce5a3ac60412fdbc22652b9f0eb36)
> 
> Build ID: 1
> 
> Status: ❌ CI test failed in Stage [CPU Build].
> 
> Report path: [link](https://dgl-ci-result.s3.us-west-2.amazonaws.com/dgl/PR-6126/1/1/logs/report.html)
> 
> Full logs path: [link](https://dgl-ci-result.s3.us-west-2.amazonaws.com/dgl/PR-6126/1/1/logs/cireport.log)

manually killed ci, since no need to run.

**Pull request merged**
