### PR TITLE
[Model] Fix output dimensions of residual connection for GATv2Conv

### PR DESCRIPTION
**Pull request by schmidt-ju**
## Description
Number of heads needs to be considered for the transformation of the destination features. Otherwise this will crash if residual==True.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [x] Code is well-documented
- [x] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by schmidt-ju** [comment]
The error of the cid should not be related to my change.
Is there a way to retrigger the cid?

**Review by mufeili — APPROVED** [review]
LGTM. Thx!

**Comment by mufeili** [comment]
> The error of the cid should not be related to my change. Is there a way to retrigger the cid?

You can make an empty commit as follows.

```
git commit -m 'Update' --allow-empty
```

**Comment by schmidt-ju** [comment]
@mufeili thank you!
CID now ran through. Feel free to merge ;)

**Pull request merged**
