### PR TITLE
Use torch core instead of torchdata modules.

### PR DESCRIPTION
**Pull request by frozenbugs**
## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [ ] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by mfbalin** [comment]
@frozenbugs wouldn't they remove these too?

**Comment by mfbalin** [comment]
@frozenbugs Andrew Kho, the main torchdata developer said that the datapipes in torch.utils.data are most likely to be deprecated and removed as well.

**Comment by frozenbugs** [comment]
Currently we are rely on functional_datapipe from torch.data package as well, it could break us if they remove datapipe from core entirely. Also the torchdata module seems rely on torch.data for many of the modules, if they remove the code from torch core, how would the dependency look like?

**Comment by mfbalin** [comment]
> Currently we are rely on functional_datapipe from torch.data package as well, it could break us if they remove datapipe from core entirely. Also the torchdata module seems rely on torch.data for many of the modules, if they remove the code from torch core, how would the dependency look like?

I asked that now. I asked if we pin torchdata<0.8.0, whether we can update to later torch versions.

**Comment by frozenbugs** [comment]
For reference: https://github.com/pytorch/data/issues/1196

**Comment by mfbalin** [comment]
They said this:

0.8.0 will still have datapipes, but generally we won’t be able to continuously support all cross versioning so at some point it will probably break, and you’ll probably need to set up your package manager appropriately to try it out

**Comment by mfbalin** [comment]
@frozenbugs

image

**Comment by frozenbugs** [comment]
From the announcement, it seems that they haven't made the decision on remove datapipe from torch core. That says we can merge this PR first and get rid of `import torchdata.dataloader2.graph as dp_utils`. @mfbalin

**Review by mfbalin — APPROVED** [review]

**Pull request merged**
