### PR TITLE
Update gatconv.py -  to extract attention weights to check them at individual level.

### PR DESCRIPTION
**Pull request by shakshi12**
## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Comment by VoVAllen** [comment]
Why would you like to change the default parameter to True?

**Comment by shakshi12** [comment]
> Why would you like to change the default parameter to True?

In order to visualize and then use those attention weights as edge weights to my graph.

**Comment by BarclayII** [comment]
> > Why would you like to change the default parameter to True?
> 
> In order to visualize and then use those attention weights as edge weights to my graph.

What prevents you from setting the argument to True in your user code (i.e. outside DGL)?

**Comment by decoherencer** [comment]
I think we can close this, as the user side setting works fine and default `False` is good.

**Pull request closed without merging**
