### PR TITLE
[Test] Pinsage speed regression test

### PR DESCRIPTION
**Pull request by classicsong**
## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [x] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR

### CODE REVIEW

**Comment by jermainewang** [comment]
Unassigned myself. Assigned @BarclayII for review.

**Comment by BarclayII** [comment]
Is this benchmarking end-to-end PinSage training?

**Comment by classicsong** [comment]
> Is this benchmarking end-to-end PinSage training? I'm good if this is the case. Also how do we make sure if the examples and benchmarks have the same code?

Yes, it is end2end PinSage training.
For second question, if you do modify the pinsage code, you need to update this test code.

**Comment by BarclayII** [comment]
K.  Sounds good to me.

**Review by BarclayII — APPROVED** [review]

**Pull request merged**
