### PR TITLE
[Doc] Implementation Index Page

### PR DESCRIPTION
**Pull request by mufeili**
## Description
This PR adds an index page for all papers with official examples/modules.

- @zheng-da @classicsong @aksnzhy I also added entries for DGL-KE, see if you want to modify them.
- @VoVAllen Can we update the PR template and ask people to add entries in the index page if the PR is for a model/module?
- @jermainewang Can we deprecate the performance table under `examples/pytorch` [here](https://github.com/dmlc/dgl/tree/master/examples/pytorch)?

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR

### CODE REVIEW

**Comment by mufeili** [comment]
@zhjwy9343 I've changed the order of the papers.
@hetong007 I've removed the links to the modules except for three papers without examples.

**Review by hetong007 — APPROVED** [review]
LGTM

**Comment by jermainewang** [comment]
> Can we deprecate the performance table under examples/pytorch here?

Yes

**Comment by jermainewang** [comment]
Shall we organize them in chronological order? I think users will look up categories first.

**Comment by mufeili** [comment]
> > Can we deprecate the performance table under examples/pytorch here?
> 
> Yes

Done

**Comment by mufeili** [comment]
> chronological order

It's now the inverse chronological order, starting from papers in 2020.

**Pull request merged**
