### PR TITLE
[Dev] Change CXX standard to 17

### PR DESCRIPTION
**Pull request by mfbalin**
## Description
Changing CXX standard to 17 hoping that issues similar to #6135 will be resolved.

### CODE REVIEW

**Comment by mfbalin** [comment]
@Rhett-Ying I don't know why we still need to pass the `-std=c++17` flag to NVCC manually, but let's see if everything will work with this patch. If CI passes, we can check if #6135 is resolved also.

**Comment by mfbalin** [comment]
Surprisingly, this patch doesn't have the problem in #6065 .

**Comment by Rhett-Ying** [comment]
let me try with this PR on windows

**Comment by Rhett-Ying** [comment]
same issue on windows + vs2019 with this PR's branch
image


image

**Comment by mfbalin** [comment]
@Rhett-Ying could you try with the newly added commits also? Also, if there is a chance I can setup the same windows build environment, how can I do that?

**Comment by mfbalin** [comment]
Also, are we sure that the changes here enable c++17 compilation for the windows build as well?

**Comment by mfbalin** [comment]
We need to revert #5648 to fix #6135. But this PR can still be merged if we want to upgrade to CXX17.

**Comment by Rhett-Ying** [comment]
> We need to revert #5648 to fix #6135. But this PR will fix the static_assert issue encountered on the Windows build without modifying the labor sampling code. Also, it can still be merged if we want to upgrade to CXX17. @Rhett-Ying

Reverting #5648 is the only way to fix the build issue on windows_cuda? I hit this issue when cutting a new release, and for this release, I think it's ok to not cherry-pick #5648 . 

As for this PR, I tried it on windows+cu118, and it failed due to the #5648 . So if we revert it, this PR should be fine on windows.

**Comment by mfbalin** [comment]
I suggested we revert it because I couldn't find a way to fix the build error on Windows+cuda case. If you think windows+cuda release can simply exclude #5648 , that sounds alright. I think they will add windows CI to the CCCL repository (thrust, cub and libcudacxx now lives there) soon so we can update CCCL and windows build should start working.

**Comment by Rhett-Ying** [comment]
As discussed above, let's merge this into master and to see if CCCL resolves the build issue on windows+cuda.

**Review by Rhett-Ying — APPROVED** [review]

**Pull request merged**
