### PR TITLE
[Example][Bug] Fix GCMC examples

### LINKED ISSUE #4019: Running error on one example case within: examples/pytorch/gcmc (ml-100k, with feature)
## 🐛 Bug

API incompatible when using latest torchtext

## To Reproduce
Run the second example (ml-100k, with features) in examples/pytorch/gcmc

1.python3 train.py --data_name=ml-100k --gcn_agg_accum=stack

Traceback (most recent call last):
  File "/workspace/examples/gcmc/train.py", line 241, in <module>
    train(args)
  File "/workspace/examples/gcmc/train.py", line 71, in train
    dataset = MovieLens(args.data_name, args.device, use_one_hot_fea=args.use_one_hot_fea, symm=args.gcn_agg_norm_symm,
  File "/workspace/examples/gcmc/data.py", line 175, in __init__
    self.movie_feature = th.FloatTensor(self._process_movie_fea()).to(self._device)
  File "/workspace/examples/gcmc/data.py", line 518, in _process_movie_fea
    TEXT = torchtext.legacy.data.Field(tokenize='spacy', tokenizer_language='en_core_web_sm')
AttributeError: module 'torchtext' has no attribute 'legacy'

## Expected behavior

The case should run through.

## Environment

 - DGL Version (e.g., 1.0): 0.9
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): 1.12
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): 
 - Python version: 3.8.13
 - CUDA/cuDNN version (if applicable): 11.7
 - GPU models and configuration (e.g. V100): A100
 - Any other relevant information:
torchtext 0.13.0a0

## Additional context

It seems the legacy API of torchtext has been deprecated in later versions. 
Needs to migrate to new API

### PR DESCRIPTION
**Pull request by chang-l**
## Description
To fix #4019 
Updated the API of accessing tokenizer in the latest version of torchtext. Using module _torchtext.legacy_ causes the crash with torchtext 0.13.

However, with this fix, I have not tested the backward compatibility, i.e., torchtext 0.9-0.12.

### CODE REVIEW

**Comment by mufeili** [comment]
Could you update the README file for the version requirement of `torchtext`?

**Comment by chang-l** [comment]
> Could you update the README file for the version requirement of `torchtext`?

The new torchtext API, introduced in torchtext 0.9, should be backward-compatible, i.e., good for 0.9+. Thus, the version requirement in the README file should be fine, I think.  It seems torchtext supports both legacy api and new api ever since 0.9; but recently they decided to deprecate legacy API in their latest release, which causes the issue in the script.  Sorry for any confusion in earlier post.

**Comment by chang-l** [comment]
>

**Comment by chang-l** [comment]
I have tested the updated API with past torchtext versions (0.9-0.12), and they can pass this case successfully. 
Note that the old legacy API works fine if torchtext>=0.9 && torchtext<=0.11.

**Comment by mufeili** [comment]
I tried running the GCMC example in this PR with the latest version of PyTorch, DGL and TorchText, but encountered the following error messages. Did you encounter that?

```
../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [16,0,0] Asserti
on `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [17,0,0] Asserti
on `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [19,0,0] Asserti
on `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [20,0,0] Asserti
on `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [22,0,0] Asserti
on `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [23,0,0] Asserti
on `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [24,0,0] Asserti
on `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [25,0,0] Asserti
on `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [26,0,0] Asserti
on `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [27,0,0] Asserti
on `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [28,0,0] Asserti
on `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [30,0,0] Asserti
on `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [31,0,0] Asserti
on `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "train.py", line 241, in <module>
    train(args)
  File "train.py", line 124, in train
    count_loss += loss.item()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by TristonC** [comment]
@BarclayII The error @mufeili mentioned maybe introduced after 0.8.0post2.

**Comment by chang-l** [comment]
> I tried running the GCMC example in this PR with the latest version of PyTorch, DGL and TorchText, but encountered the following error messages. Did you encounter that?
> 
> ```
> ../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [16,0,0] Asserti
> on `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [17,0,0] Asserti
> on `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [19,0,0] Asserti
> on `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [20,0,0] Asserti
> on `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [22,0,0] Asserti
> on `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [23,0,0] Asserti
> on `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [24,0,0] Asserti
> on `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [25,0,0] Asserti
> on `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [26,0,0] Asserti
> on `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [27,0,0] Asserti
> on `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [28,0,0] Asserti
> on `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [30,0,0] Asserti
> on `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:257: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [31,0,0] Asserti
> on `t >= 0 && t < n_classes` failed.
> Traceback (most recent call last):
>   File "train.py", line 241, in <module>
>     train(args)
>   File "train.py", line 124, in train
>     count_loss += loss.item()
> RuntimeError: CUDA error: device-side assert triggered
> CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> ```

Yes, I can reproduce this issue, if I sync-up and use the latest dgl-master code. 
We should have this fixed before merging this branch...
Tracking the file history, if we revert this commit change 74f01405337f861c38c55d9a2e528600583ae30b (05/10/2022) for gcmc/model.py file, the gcmc example tests can run through.  Could you please help verify?

**Comment by mufeili** [comment]
> 

Yes, I confirm reverting that addresses the issue.

**Comment by mufeili** [comment]
@chang-l Could you revert the commit for gcmc/model.py file?

**Comment by chang-l** [comment]
> @chang-l Could you revert the commit for gcmc/model.py file?

Sure. I just updated the branch. Let me know if it doesn't work.

**Comment by mufeili** [comment]
@chang-l Thanks. It seems that this PR now contains many file changes beyond the GCMC example. Perhaps we should have separate PR(s) for these non-GCMC file changes.

**Comment by chang-l** [comment]
@mufeili Not sure why there are many unrelated file changes... Maybe I messed up when I was rebasing the branch on top of master. I will try to clean this up tomorrow. Sorry for any inconvenience.

**Comment by mufeili** [comment]
> @mufeili Not sure why there are many unrelated file changes... Maybe I messed up when I was rebasing the branch on top of master. I will try to clean this up tomorrow. Sorry for any inconvenience.

No worries. It happens and thanks for the extra efforts.

**Comment by mufeili** [comment]
It seems that many of these file changes are from other merged PRs. As you mentioned, this might be caused by rebasing. In that case, I think it might be a good idea to re-create a branch from the latest DGL master branch and open a new PR instead. What do you think?

**Pull request closed without merging**
