### PR TITLE
[GraphBolt][CUDA] Force CUDA version if torch is.

### LINKED ISSUE #7512: AttributeError: '_OpNamespace' 'graphbolt' object has no attribute 'set_max_uva_threads'
## Code

```python3
class SAGE(nn.Module):
    def __init__(self, in_size, hidden_size):
        super().__init__()
        self.layers = nn.ModuleList()
        self.layers.append(SAGEConv(in_size, hidden_size, "mean"))
        self.layers.append(SAGEConv(hidden_size, hidden_size, "mean"))
        self.hidden_size = hidden_size
        self.predictor = nn.Sequential(
            nn.Linear(hidden_size, hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, 1),
        )

    def forward(self, blocks, x):
        hidden_x = x
        for layer_idx, (layer, block) in enumerate(zip(self.layers, blocks)):
            hidden_x = layer(block, hidden_x)
            is_last_layer = layer_idx == len(self.layers) - 1
            if not is_last_layer:
                hidden_x = F.relu(hidden_x)
        return hidden_x

dataset = gb.BuiltinDataset("cora-seeds").load()

graph = dataset.graph
feature = dataset.feature
train_set = dataset.tasks[1].train_set
test_set = dataset.tasks[1].test_set
task_name = dataset.tasks[1].metadata["name"]
print(f"Task: {task_name}")

device = torch.device("cuda")

datapipe = gb.ItemSampler(train_set, batch_size=256, shuffle=True)
datapipe = datapipe.copy_to(device)
datapipe = datapipe.sample_uniform_negative(graph, 5)
datapipe = datapipe.sample_neighbor(graph, [5, 5])
datapipe = datapipe.transform(partial(gb.exclude_seed_edges, include_reverse_edges=True))
datapipe = datapipe.fetch_feature(feature, node_feature_keys=["feat"])
train_dataloader = gb.DataLoader(datapipe)
```

```
Traceback (most recent call last):
  File "/home/yoochan/GNN/dgl/./train.py", line 57, in <module>
    train_dataloader = gb.DataLoader(datapipe)
  File "/home/yoochan/.local/lib/python3.10/site-packages/dgl/graphbolt/dataloader.py", line 203, in __init__
    torch.ops.graphbolt.set_max_uva_threads(max_uva_threads)
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 921, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'graphbolt' object has no attribute 'set_max_uva_threads'
```

## Comment

This code is an example using graphbolt from the official documentation. I tried it with another torch (2.2.0) version and dgl, but I still get the same error. (I also tried it with colab from https://docs.dgl.ai/en/2.0.x/api/python/dgl.graphbolt.html, but dgl is not imported there at all.)

Additionally, if I directly edit the dataloader code and comment out the part where set_max_uva_threads is called, I get an error saying "RuntimeError: unique_and_compact is only available on CUDA device."

## Environment
 - DGL Version (e.g., 1.0): 2.3.0
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): 2.3.1+cu121
 - OS (e.g., Linux): Ubuntu 22.04
 - How you installed DGL (`conda`, `pip`, source): pip
 - Python version: 3.10.12
 - CUDA/cuDNN version (if applicable): 12.1
 - GPU models and configuration (e.g. V100): rtx2080 super

### PR DESCRIPTION
**Pull request by mfbalin**
## Description
Force the user to reinstall if the user has a GPU, installed the CUDA version of torch but installs the CPU version of GraphBolt.

Feel free to close the PR if we do not want that. This mismatch causes problems for them so I thought not even letting them use it is the best way to resolve these issues.

Fixes #7512 and #7494

## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [ ] I've leverage the [tools](https://docs.google.com/document/d/1iHyj7zlmygKSk5gBPsqIqL5ASPzJSPREaNT_QdsiYA4/edit) to beautify the python and c++ code.
- [ ] The PR is complete and small, read the [Google eng practice (CL equals to PR)](https://google.github.io/eng-practices/review/developer/small-cls.html) to understand more about small PR. In DGL, we consider PRs with less than 200 lines of core code change are small (example, test and documentation could be exempted).
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Review by Skeleton003 — COMMENTED** [review]
ImportError or RuntimeError?

**Comment by mfbalin** [comment]
> ImportError or RuntimeError?

Import error because the code runs while importing the graphbolt module. When the module fails to load, it should throw ImportError.

**Comment by mfbalin** [comment]
@frozenbugs @Rhett-Ying this PR needs to move forward because if users have installed the wrong version, they won't even be able to run our examples or anywhere we use `torch.cuda.is_available()` in our code, the wrong branch is going to be taken. If `torch.cuda.is_available()` returns true, it needs to be true for GraphBolt too.

**Comment by frozenbugs** [comment]
Just wondering, what if we add an check at this line to prevent calling cuda specific feature if not installed?

https://github.com/dmlc/dgl/blob/4d497d17829addfcb0178874ae3dc88b59c5b425/python/dgl/graphbolt/dataloader.py#L201

**Review by frozenbugs — APPROVED** [review]

**Comment by mfbalin** [comment]
> Just wondering, what if we add an check at this line to prevent calling cuda specific feature if not installed?
> 
> https://github.com/dmlc/dgl/blob/4d497d17829addfcb0178874ae3dc88b59c5b425/python/dgl/graphbolt/dataloader.py#L201

We can do that. But GraphBolt is a torch library, and if `torch.cuda.is_available()` is true, then it should be true for graphbolt as well. I can not think of any user who wouldn't expect the same.

**Comment by mfbalin** [comment]
Merging this as it is easily revertible in a later PR if an issue is discovered.

**Pull request merged**
