### PR TITLE
[Feature] Rework Dataloader cpu affinitization as helper method

### PR DESCRIPTION
**Pull request by daniil-sizov**
## Description
Rework Dataloader cpu affinitization to affinitize compute threads as well by default, making it a context manager helper method

The feature enables dataloading worker threads affinitization and separates them from compute threads. In general it is expected to give significant performance gain (measured +37% on ogbn-products/graphsage)

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [] All changes have test coverage
- [x] Code is well-documented
- [x] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [] Related issue is referred in this PR

## Changes
- [x] Change default cores used for dataloading/compute from all available to NUMA node 0 cores only
- [x] Modify benchmarks to include enabled optimization
- [x] Add docs

### CODE REVIEW

**Comment by mufeili** [comment]
Could you provide more context in a separate github issue regarding the motivation and example user experience?

**Comment by BarclayII** [comment]
@mufeili The PR is about setting affinitization of CPU sampling workers so that the worker processes stays on the same CPU throughout the process to avoid overhead of context switches.  Previously #3723 was merged but with two extra optional arguments.  This PR aims to give default values to those arguments so that users won't have to specify them.  More like performance optimization.

**Comment by mufeili** [comment]
> @mufeili The PR is about setting affinitization of CPU sampling workers so that the worker processes stays on the same CPU throughout the process to avoid overhead of context switches. Previously #3723 was merged but with two extra optional arguments. This PR aims to give default values to those arguments so that users won't have to specify them. More like performance optimization.

Thanks for the explanation.

**Comment by daniil-sizov** [comment]
@mufeili @BarclayII 
The feature enables CPU affinity optimization for dataloader. Since both dataloading and training on CPU devices happen on the same device, unlike on GPU, locking worker threads to particular CPU cores and separating compute cores gives significant performance gain

**Comment by daniil-sizov** [comment]
Perf measurements on DGL benchmarks (Ice Lake, 32 cores, single socket):

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/dsizov/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/dsizov/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#1155CC" vlink="#1155CC">

  |   | CPU affinity off | CPU affinity on | diff
-- | -- | -- | -- | --
bench_gat_ns.track_time | reddit | 0.44 | 0.304 | -30.9%
  | ogbn-products | 0.264 | 0.255 | -3.4%
bench_rgcn_hetero_ns.track_time | ogbn-mag | 0.642 | 0.219 | -65.9%
bench_rgcn_homogeneous_ns.track_time | ogbn-mag | 0.928 | 0.517 | -44.3%
bench_sage_ns.track_time | reddit | 0.29 | 0.092 | -68.3%
  | ogbn-products | 0.167 | 0.064 | -61.7%
  |   |   |   | -45.75%
</body>
</html>

**Review by BarclayII — APPROVED** [review]

**Pull request merged**
