### PR TITLE
[Performance] improve coo2csr space complexity when row is not sorted

### PR DESCRIPTION
**Pull request by Rhett-Ying**
## Description

fix the potential huge memory consumption issue when converting coo to csr. refer to https://github.com/dmlc/dgl/issues/3307 for more details.

Implementation and Complexity details. N: num_nodes, NNZ: num_edges, P:
num_threads.
  1. If row is sorted in COO, SortedCOOToCSR<> is applied. Time: O(NNZ/P).
Space: O(1).
  2. If row is NOT sorted in COO and graph is sparse (low average degree),
UnSortedSparseCOOToCSR<> is applied. Time: O(NNZ/P + N/P + P^2), space O(NNZ +
P^2).
  3. If row is NOT sorted in COO and graph is dense (medium/high average
degree), UnSortedDenseCOOToCSR<> is applied. Time: O(NNZ/P + N/P), space O(NNZ +
N*P).

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [NN], [Model], [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented
- [x] To the best of my knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [x] Related issue is referred in this PR
- [x] If the PR is for a new model/paper, I've updated the example index [here](../examples/README.md).

### CODE REVIEW

**Review by nv-dlasalle — APPROVED** [review]
This looks good to me. Should we we run the regression tests?

**Comment by Rhett-Ying** [comment]
@dgl-bot run c5.9xlarge api dmlc/master

**Comment by BarclayII** [comment]
@dgl-bot run c5.9xlarge api dmlc/master

**Comment by Rhett-Ying** [comment]
@nv-dlasalle regression test has been triggered. In your perspective, which benchmarks should we pay attention to? random_walk? seems no specific benchmark for coo2csr.

**Comment by Rhett-Ying** [comment]
@dgl-bot run c5.9xlarge bench_format_conv dmlc/master

**Comment by Rhett-Ying** [comment]
@dgl-bot run c5.24xlarge bench_format_conv dmlc/master

**Comment by Rhett-Ying** [comment]
@dgl-bot run m6i.16xlarge bench_format_conv dmlc/master

**Comment by Rhett-Ying** [comment]
Result table is at https://dgl-asv-data.s3-us-west-2.amazonaws.com/c38597e6f75059f851f9a45494fad0a85b63867f_m6i16xlarge/results/result.csv. 

Perf results of current impl is much worse than original one( **-20% even more**), though I have already improved it via **replacing std::vector<> by NDArray**. This replacement really helps a lot. If we analyze deeper, this degrade is reasonable. What's worse, such perf degrade could be worse for datasets with larger average degree and imbalance in row_idx.

Below is the time/space details for original and current impl. let's assume N and NNZ is much larger than P. `P=32` in test.

Original_time: `2*NNZ/P + N/P + N`
Current_time: `4*NNZ/P + 3*N/P`
Original_space: `2*NNZ + N*P`
Current_space: `4*NNZ`

The N, NNZ info of the datasets we used for perf test is shown below.
`friendster:     N ~ 124M,  NNZ ~ 1.8B
livejournal:     N ~ 4.8M, NNZ ~ 70M`

we can find that `NNZ` is much larger than `N` which results in increase in time. And such average degree is common? So , current impl outperforms for the case in https://github.com/dmlc/dgl/issues/3307 both in time and space complexity. But in most scenarios, original impl is much better and more stable in time and space.

as for the fix, https://github.com/dmlc/dgl/pull/3320 is the simplest one. Also, we could merge these 2 PRs together.

 @nv-dlasalle How do you think about it?

**Comment by nv-dlasalle** [comment]
@Rhett-Ying Merging the two PRs is an option, but limit parallelism may be painful when working with very large graphs on a multi-socket system. Could we combine the old method and new method?
```
if (num_threads * N > 2*NNZ) {
  // perform new method
  ...
} else {
  // perform old method
  ...
}
```
To keep the function to a reasonable length, moving each one to its own function (e.g. `_UnsortedCOOToCSRLargeNumNodes()` and `_UnsortedCOOToCSRLargeNumEdges()`) might be a good idea.

**Comment by Rhett-Ying** [comment]
@dgl-bot run m6i.16xlarge bench_format_conv dmlc/master

**Comment by Rhett-Ying** [comment]
@dgl-bot run m6i.16xlarge bench_format_conv dmlc/master

**Comment by Rhett-Ying** [comment]
@dgl-bot run m6i.16xlarge bench_format_conv dmlc/master

**Comment by Rhett-Ying** [comment]
@nv-dlasalle Both methods are combined. pls help review it. thanks.

**Review by nv-dlasalle — APPROVED** [review]

**Pull request merged**
